Repository getodk/collect, pull requests merged in 2018-07, with the labels that each got.

#2338 Server settings path changes updated but not immediately shown
  collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java
Labels: behavior verified

#2334 Use start button to start ranking instead of double tap AND add numbers on the left
  collect_app/src/main/java/org/odk/collect/android/widgets/RankingWidget.java
  collect_app/src/main/res/layout/ranking_widget.xml
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#2331 Update properties when needed
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ResetUtility.java
  collect_app/src/main/java/org/odk/collect/android/utilities/SharedPreferencesUtils.java
Labels: behavior verified

#2347 Fix crash previously fixed in d14ed91. Fixes #2270
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/ViewFormHierarchyActivity.java
Labels: high priority

#2320 Camera permisssion
  collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieActivityNewApi.java
  collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieVideoActivityNewApi.java
  collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/Camera2VideoFragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java
  collect_app/src/main/java/org/odk/collect/android/utilities/PermissionUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWebViewWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
  collect_app/src/main/res/drawable/ic_photo_camera.xml
  collect_app/src/main/res/values-ar/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-hi/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-mr/strings.xml
  collect_app/src/main/res/values-ne-rNP/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-sq/strings.xml
  collect_app/src/main/res/values-sv-rSE/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#2354 Fixed Barcode Scanner
  collect_app/src/main/res/layout/custom_barcode_scanner.xml
Labels: behavior verified

#2352 Full message from the newest notification is visible even if the userclicks on the older notification
  collect_app/src/main/java/org/odk/collect/android/receivers/NetworkReceiver.java
  collect_app/src/main/java/org/odk/collect/android/tasks/ServerPollingJob.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationConstants.java
Labels: behavior verified

#2361 SelfieImageWidget and SelfieVideoWIdget crashes after multitapping (a few quick taps)
  collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieVideoActivity.java
  collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/Camera2VideoFragment.java
Labels: behavior verified

#2358 Handle location permissions
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointOsmMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeGoogleMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeOsmMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceGoogleMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceOsmMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/utilities/PermissionUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoPointWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoShapeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoTraceWidget.java
  collect_app/src/main/res/values/strings.xml
  collect_app/src/test/java/org/odk/collect/android/location/activities/BaseGeoActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/location/activities/GeoPointActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/location/activities/GeoPointMapActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/location/activities/GeoPointOsmMapActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/location/activities/GeoShapeGoogleMapActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/location/activities/GeoTraceGoogleMapActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/location/activities/GeoTraceOsmMapActivityTest.java
Labels: behavior verified

#2367 Handle Record audio permission
  collect_app/src/main/java/org/odk/collect/android/utilities/PermissionUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/main/res/drawable/ic_mic.xml
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#2351 Use uri_data key in intent appearance as intent data
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
Labels: behavior verified

#2363 RankWidget in a dialog
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/adapters/RankingListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/RankingWidgetDialog.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormEntryPromptUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ThemeUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/RankingWidget.java
  collect_app/src/main/res/layout/ranking_item.xml
  collect_app/src/main/res/values/attrs.xml
  collect_app/src/main/res/values/colors.xml
  collect_app/src/main/res/values/strings.xml
  collect_app/src/main/res/values/theme.xml
Labels: behavior verified

#2302 Encrypt an instance during scanning if needed
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceSyncTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java
Labels: behavior verified

#2348 Add intent to enable form download from an external app
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/jobs/CollectJobCreator.java
  collect_app/src/main/java/org/odk/collect/android/services/FormDownloadService.java
  collect_app/src/main/java/org/odk/collect/android/tasks/FormDownloadJob.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationConstants.java
Labels: behavior verified

#2377 Resolved SMS/internet submission status issue
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderList.java
  collect_app/src/main/java/org/odk/collect/android/adapters/InstanceUploaderAdapter.java
  collect_app/src/main/java/org/odk/collect/android/tasks/sms/SmsNotificationReceiver.java
  collect_app/src/main/java/org/odk/collect/android/tasks/sms/SmsSender.java
  collect_app/src/main/java/org/odk/collect/android/tasks/sms/SmsService.java
Labels: behavior verified

#2386 Support implicit intents using any kind of uri
  collect_app/src/main/java/org/odk/collect/android/external/ExternalAppsUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
Labels: behavior verified, high priority

#2403 Fixed Attempt to invoke getLocale() on null reference
  collect_app/src/main/java/org/odk/collect/android/utilities/FormEntryPromptUtils.java
Labels: behavior verified, high priority

#2404 Default accent color
  collect_app/src/main/java/org/odk/collect/android/adapters/RankingListAdapter.java
  collect_app/src/main/res/drawable-hdpi/ic_assignment.png
  collect_app/src/main/res/drawable-hdpi/ic_cloud.png
  collect_app/src/main/res/drawable-hdpi/ic_face.png
  collect_app/src/main/res/drawable-hdpi/ic_phonelink_setup.png
  collect_app/src/main/res/drawable-mdpi/ic_assignment.png
  collect_app/src/main/res/drawable-mdpi/ic_cloud.png
  collect_app/src/main/res/drawable-mdpi/ic_face.png
  collect_app/src/main/res/drawable-mdpi/ic_phonelink_setup.png
  collect_app/src/main/res/drawable-xhdpi/ic_assignment.png
  collect_app/src/main/res/drawable-xhdpi/ic_cloud.png
  collect_app/src/main/res/drawable-xhdpi/ic_face.png
  collect_app/src/main/res/drawable-xhdpi/ic_phonelink_setup.png
  collect_app/src/main/res/drawable-xxhdpi/ic_assignment.png
  collect_app/src/main/res/drawable-xxhdpi/ic_cloud.png
  collect_app/src/main/res/drawable-xxhdpi/ic_face.png
  collect_app/src/main/res/drawable-xxhdpi/ic_phonelink_setup.png
  collect_app/src/main/res/drawable-xxxhdpi/ic_assignment.png
  collect_app/src/main/res/drawable-xxxhdpi/ic_cloud.png
  collect_app/src/main/res/drawable-xxxhdpi/ic_face.png
  collect_app/src/main/res/drawable-xxxhdpi/ic_phonelink_setup.png
  collect_app/src/main/res/drawable/ic_assignment.xml
  collect_app/src/main/res/drawable/ic_cloud.xml
  collect_app/src/main/res/drawable/ic_face.xml
  collect_app/src/main/res/drawable/ic_phonelink_setup.xml
  collect_app/src/main/res/values/colors.xml
  collect_app/src/main/res/values/theme.xml
Labels: behavior verified, high priority

#2406 Choice filter analytics
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
Labels: high priority

#2405 Fixed null date issue and stream error handling
  collect_app/src/main/java/org/odk/collect/android/events/SmsRxEvent.java
  collect_app/src/main/java/org/odk/collect/android/tasks/sms/SmsService.java
Labels: high priority, needs testing

#2427 Hide "Submission transport" server settings
  collect_app/src/main/java/org/odk/collect/android/preferences/AdminKeys.java
  collect_app/src/main/java/org/odk/collect/android/preferences/BasePreferenceFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/ExtendedCheckboxPreference.java
  collect_app/src/main/java/org/odk/collect/android/preferences/PreferenceKeys.java
  collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferences.java
  collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java
  collect_app/src/main/res/values/strings.xml
  collect_app/src/main/res/values/untranslated.xml
  collect_app/src/main/res/xml/aggregate_preferences.xml
  collect_app/src/main/res/xml/google_preferences.xml
  collect_app/src/main/res/xml/user_settings_access_preferences.xml
Labels: behavior verified

#2323 Inflate MediaLayout using xml
  collect_app/src/main/java/org/odk/collect/android/views/AudioButton.java
  collect_app/src/main/java/org/odk/collect/android/views/MediaLayout.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectWidget.java
  collect_app/src/main/res/layout/media_layout.xml
  collect_app/src/main/res/values/attrs.xml
  collect_app/src/main/res/values/style.xml
  collect_app/src/main/res/values/theme.xml
  collect_app/src/test/java/org/odk/collect/android/views/MediaLayoutTest.java
Labels: behavior verified

#2395 Add dividers to SelectMultipleAutocompleteWidget
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectMultipleAutocompleteWidget.java
Labels: behavior verified
