Repository getodk/collect, pull requests merged in 2018-09, with the labels that each got.

#2488 Add test runs and regression risks to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs discussion

#2482 Fixes Issue#2158: Collect crashes when user changes device orientation during loading image to any of Image Widget
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/fragments/ImageLoadingFragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/ProgressDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/tasks/ImageLoadingTask.java
Labels: behavior verified

#2483 Google account dialog no longer visible on send screen & account removal crash resolved
  collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/receivers/NetworkReceiver.java
  collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java
  collect_app/src/main/res/values/strings.xml
  collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java
Labels: behavior verified

#2524 Display warning dialog for current() predicate
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/main/res/values/strings.xml
Labels: high priority, needs testing

#2506 Handle READ_PHONE_STATE permission
  collect_app/build.gradle
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderList.java
  collect_app/src/main/java/org/odk/collect/android/events/ReadPhoneStatePermissionRxEvent.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppComponent.java
  collect_app/src/main/java/org/odk/collect/android/logic/PropertyManager.java
  collect_app/src/main/java/org/odk/collect/android/preferences/FormMetadataFragment.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceServerUploader.java
  collect_app/src/main/java/org/odk/collect/android/utilities/PermissionUtils.java
  collect_app/src/main/res/drawable/ic_phone.xml
  collect_app/src/main/res/values/strings.xml
  config/lint.xml
Labels: behavior verified

#2461 Expose instance uploader activity to external apps
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceServerUploader.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploader.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationConstants.java
  collect_app/src/main/java/org/odk/collect/android/utilities/AuthDialogUtility.java
  collect_app/src/main/java/org/odk/collect/android/utilities/WebCredentialsUtils.java
Labels: behavior verified, high priority

#2463 External app form download request fixes & additions
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppComponent.java
  collect_app/src/main/java/org/odk/collect/android/jobs/CollectJobCreator.java
  collect_app/src/main/java/org/odk/collect/android/services/FormDownloadService.java
  collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormsTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/FormDownloadJob.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationConstants.java
  collect_app/src/main/java/org/odk/collect/android/utilities/DownloadFormListUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/WebCredentialsUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/WebUtils.java
Labels: behavior verified, high priority

#2513 Implemented RecyclerView to improve selectOne widgets
  collect_app/src/main/java/org/odk/collect/android/adapters/SelectOneListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/views/MediaLayout.java
  collect_app/src/main/java/org/odk/collect/android/views/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AbstractSelectOneWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectOneSearchWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectTextWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectWidget.java
  collect_app/src/main/res/layout/nested_scroll_view.xml
  collect_app/src/main/res/layout/quick_select_layout.xml
Labels: high priority, needs testing

#2540 Separate out search and search() appearances
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
Labels: behavior verified, high priority

#2545 Add or improve analytics for audit logging, form updates, servers, external apps and external CSV features
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
  collect_app/src/main/java/org/odk/collect/android/external/ExternalDataUtil.java
  collect_app/src/main/java/org/odk/collect/android/external/handler/ExternalDataHandlerPull.java
  collect_app/src/main/java/org/odk/collect/android/logic/FormController.java
  collect_app/src/main/java/org/odk/collect/android/preferences/FormManagementPreferences.java
  collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
Labels: high priority

#2539 Credentials authentication fix
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java
  collect_app/src/main/java/org/odk/collect/android/utilities/AuthDialogUtility.java
  collect_app/src/main/java/org/odk/collect/android/utilities/WebCredentialsUtils.java
Labels: high priority, needs testing

#2547 Reimplement select multi widgets using recycler view
  collect_app/src/main/java/org/odk/collect/android/adapters/AbstractSelectListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/adapters/SelectMultipleListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/adapters/SelectOneListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormEntryPromptUtils.java
  collect_app/src/main/java/org/odk/collect/android/views/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AbstractSelectOneWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectMultipleAutocompleteWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectTextWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectWidget.java
  collect_app/src/main/res/layout/recycler_view.xml
Labels: behavior verified, high priority

#2566 App crashes on Selfie video widget if microphone permissions are not set
  collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieVideoActivityNewApi.java
  collect_app/src/main/java/org/odk/collect/android/utilities/PermissionUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
Labels: behavior verified, high priority

#2561 Support readOnly option in the ArbitraryWidget
  collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.java
Labels: behavior verified, high priority

#2555 Read only is ignored for rank
  collect_app/src/main/java/org/odk/collect/android/widgets/RankingWidget.java
Labels: behavior verified, high priority

#2559 Support readOnly option in SelectMap widgets
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectImageMapWidget.java
Labels: behavior verified, high priority

#2556 Non-question object at form index when rank questions are in field-list
  collect_app/src/main/java/org/odk/collect/android/adapters/RankingListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/RankingWidgetDialog.java
  collect_app/src/main/java/org/odk/collect/android/widgets/RankingWidget.java
Labels: behavior verified, high priority

#2578 Fixed android.view.WindowManager: Unable to add window -- token android.os.BinderProxy@a68b01e is not valid
  collect_app/src/main/java/org/odk/collect/android/utilities/PermissionUtils.java
Labels: behavior verified, high priority

#2580 Fixed java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
  collect_app/src/main/java/org/odk/collect/android/tasks/ImageLoadingTask.java
Labels: high priority

#2582 Fixed Fatal Exception: java.lang.StringIndexOutOfBoundsException: length=0; index=0
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
Labels: high priority

#2584 Fixed: attempt to re-open an already-closed object
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java
Labels: high priority

#2594 Save HttpContext between requests
  collect_app/src/main/java/org/odk/collect/android/http/HttpClientConnection.java
Labels: high priority

#2591 Strip out the search() appearance/function before identifying select appearance
  collect_app/src/main/java/org/odk/collect/android/external/ExternalDataUtil.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
Labels: high priority, needs testing
