Repository getodk/collect, pull requests merged in 2018-06, with the labels that each got.

#2261 FIx #2258 The user is not able to add files from Google Drive to File…
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
Labels: behavior verified

#2248 Show form version and form id when deleting blank forms #2173
  collect_app/src/main/java/org/odk/collect/android/fragments/FormManagerList.java
  collect_app/src/main/java/org/odk/collect/android/utilities/VersionHidingCursorAdapter.java
  collect_app/src/main/res/layout/two_item_multiple_choice.xml
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#2246 Message won't be disappeared after canceling and refreshing connection to the server
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java
  collect_app/src/main/java/org/odk/collect/android/adapters/FormDownloadListAdapter.java
Labels: behavior verified

#2236 Replace the activity we show after clicking on a notification with a dailog
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/NotificationActivity.java
  collect_app/src/main/java/org/odk/collect/android/receivers/NetworkReceiver.java
  collect_app/src/main/java/org/odk/collect/android/tasks/ServerPollingJob.java
  collect_app/src/main/res/layout/notification_layout.xml
Labels: behavior verified

#2251 Display warning about spaces in underlying values for multiple selection questions. Fixes #1964
  collect_app/src/main/java/org/odk/collect/android/utilities/UnderlyingValuesConcat.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GridMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/LabelWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectMultiImageMapWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectMultipleAutocompleteWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/warnings/SpacesInUnderlyingValuesWarning.java
  collect_app/src/main/res/layout/help_text_layout.xml
  collect_app/src/main/res/values/attrs.xml
  collect_app/src/main/res/values/theme.xml
  collect_app/src/test/java/org/odk/collect/android/widgets/warnings/SpacesInUnderlyingValuesTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/warnings/SpacesInUnderlyingValuesWarningTest.java
Labels: behavior verified, needs discussion

#2273 Issue #2264 None translatable string-array time_scale in GeoTrace
  collect_app/src/main/res/values/arrays.xml
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#2128 Refactored the HierarchyView
  collect_app/src/main/java/org/odk/collect/android/activities/EditFormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/ViewFormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/adapters/HierarchyListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/views/HierarchyElementView.java
  collect_app/src/main/res/layout/hierarchy_element.xml
  collect_app/src/main/res/layout/hierarchy_layout.xml
Labels: behavior verified

#2282 Closes#2195: Replaced the icons in DrawView with Vectors.
  collect_app/src/main/res/drawable-hdpi/ic_add_white.png
  collect_app/src/main/res/drawable-hdpi/ic_clear_white.png
  collect_app/src/main/res/drawable-hdpi/ic_color_lens_white.png
  collect_app/src/main/res/drawable-hdpi/ic_save_white.png
  collect_app/src/main/res/drawable-mdpi/ic_add_white.png
  collect_app/src/main/res/drawable-mdpi/ic_clear_white.png
  collect_app/src/main/res/drawable-mdpi/ic_color_lens_white.png
  collect_app/src/main/res/drawable-mdpi/ic_save_white.png
  collect_app/src/main/res/drawable-xhdpi/ic_add_white.png
  collect_app/src/main/res/drawable-xhdpi/ic_clear_white.png
  collect_app/src/main/res/drawable-xhdpi/ic_color_lens_white.png
  collect_app/src/main/res/drawable-xhdpi/ic_save_white.png
  collect_app/src/main/res/drawable-xxhdpi/ic_add_white.png
  collect_app/src/main/res/drawable-xxhdpi/ic_clear_white.png
  collect_app/src/main/res/drawable-xxhdpi/ic_color_lens_white.png
  collect_app/src/main/res/drawable-xxhdpi/ic_save_white.png
  collect_app/src/main/res/drawable-xxxhdpi/ic_add_white.png
  collect_app/src/main/res/drawable-xxxhdpi/ic_clear_white.png
  collect_app/src/main/res/drawable-xxxhdpi/ic_color_lens_white.png
  collect_app/src/main/res/drawable-xxxhdpi/ic_save_white.png
  collect_app/src/main/res/drawable/ic_add_white.xml
  collect_app/src/main/res/drawable/ic_clear_white.xml
  collect_app/src/main/res/drawable/ic_color_lens_white.xml
  collect_app/src/main/res/drawable/ic_save_white.xml
Labels: behavior verified

#2281 Fixed SQL injection vulnerability
  collect_app/src/main/java/org/odk/collect/android/provider/FormsProvider.java
  collect_app/src/main/java/org/odk/collect/android/provider/InstanceProvider.java
Labels: behavior verified, high priority

#2285 Remove toast informing about spaces in underlying values
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectMultiWidget.java
Labels: behavior verified

#2289 Removed unused ic_menu_forward.png icon
  collect_app/src/main/res/drawable-hdpi/ic_menu_forward.png
  collect_app/src/main/res/drawable-ldpi/ic_menu_forward.png
  collect_app/src/main/res/drawable-mdpi/ic_menu_forward.png
  collect_app/src/main/res/drawable-xhdpi/ic_menu_forward.png
  collect_app/src/main/res/layout/two_item_image.xml
Labels: behavior verified

#2245 Dark theme is not applied to the main menu when user load settings from collect.settings file
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
Labels: behavior verified

#2288 Replaced png icons with vectors
  collect_app/src/main/java/org/odk/collect/android/widgets/AbstractSelectOneWidget.java
  collect_app/src/main/res/drawable-hdpi/expander_ic_maximized.png
  collect_app/src/main/res/drawable-hdpi/expander_ic_minimized.png
  collect_app/src/main/res/drawable-hdpi/expander_ic_right.png
  collect_app/src/main/res/drawable-ldpi/expander_ic_maximized.png
  collect_app/src/main/res/drawable-ldpi/expander_ic_minimized.png
  collect_app/src/main/res/drawable-ldpi/expander_ic_right.png
  collect_app/src/main/res/drawable-mdpi/expander_ic_maximized.png
  collect_app/src/main/res/drawable-mdpi/expander_ic_minimized.png
  collect_app/src/main/res/drawable-mdpi/expander_ic_right.png
  collect_app/src/main/res/drawable-xhdpi/expander_ic_maximized.9.png
  collect_app/src/main/res/drawable-xhdpi/expander_ic_minimized.9.png
  collect_app/src/main/res/drawable-xhdpi/expander_ic_right.png
  collect_app/src/main/res/drawable/expander_ic_maximized.xml
  collect_app/src/main/res/drawable/expander_ic_minimized.xml
  collect_app/src/main/res/drawable/expander_ic_right.xml
  collect_app/src/main/res/layout/hierarchy_element.xml
Labels: behavior verified

#2293 GeoPointMapActivity crash when map isn't ready resolved
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java
  config/pmd-ruleset.xml
Labels: behavior verified

#2272 FileProvider Integration for external file permissions
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
  collect_app/src/main/res/xml/provider_paths.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: behavior verified

#2299 Changing device orientation affects the appearance in RTL languages on Android 8.1
  collect_app/src/main/java/org/odk/collect/android/activities/CollectAbstractActivity.java
  collect_app/src/main/java/org/odk/collect/android/utilities/LocaleHelper.java
Labels: behavior verified

#1649 Make offline basemaps available from general settings
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointOsmMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeGoogleMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeOsmMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceGoogleMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceOsmMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/preferences/UserInterfacePreferences.java
  collect_app/src/main/java/org/odk/collect/android/spatial/MapHelper.java
Labels: behavior verified

#2283 The user sees success information in notification even if an error occurs
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java
  collect_app/src/main/java/org/odk/collect/android/receivers/NetworkReceiver.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceGoogleSheetsUploader.java
  collect_app/src/main/java/org/odk/collect/android/tasks/ServerPollingJob.java
  collect_app/src/main/java/org/odk/collect/android/utilities/InstanceUploaderUtils.java
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified
