Repository getodk/collect, pull requests merged in 2018-04, with the labels that each got.

#2020 Adds some tests for bitmap scaling utility method and code refactoring
  collect_app/src/androidTest/java/org/odk/collect/android/utilities/BitmapScaledToDisplayTest.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
  collect_app/src/main/java/org/odk/collect/android/views/DrawView.java
  collect_app/src/main/java/org/odk/collect/android/views/MediaLayout.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GridMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GridWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/LabelWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ListMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ListWidget.java
Labels: behavior verified, needs review

#2027 Upgrade to Firebase Crashlytics from Firebase Crash Reporting
  build.gradle
  collect_app/build.gradle
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/assets/open_source_licenses.html
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
  config/lint.xml
Labels: reviewed

#2117 Fixed toast on Android 8.1 and refactored the code using ToastUtils class
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java
  collect_app/src/main/res/layout/toast_view.xml
  collect_app/src/main/res/values/colors.xml
Labels: needs testing

#2116 Do not display the min value if it's not needed
  collect_app/src/main/java/org/odk/collect/android/widgets/RangeWidget.java
Labels: behavior verified

#2053 Media files are lost when user changes them but then ignores the changes
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java
  collect_app/src/main/java/org/odk/collect/android/utilities/MediaManager.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWebViewWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
Labels: behavior verified

#2102 new-front is preferred appearance name
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
Labels: behavior verified

#2045 Escape markdown characters using backslashes
  collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java
  collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java
Labels: behavior verified

#2098 Fix TextView and EditText in RTL languages (higher than API 16), fix #1981
  collect_app/src/main/res/values/theme.xml
Labels: behavior verified

#2108 Add onClick attribute only for elements that exist in the dataset
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectImageMapWidget.java
Labels: behavior verified

#2110 Pull data newline char fix
  collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java
Labels: behavior verified

#2126 Issue#1976 There are no separator lines in SelectOneSearchWidget
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectOneSearchWidget.java
Labels: behavior verified

#2094 Refactor to Geo Layout with Scroll Buttons, fix #1181.
  collect_app/src/main/res/layout/activity_geo.xml
  collect_app/src/main/res/layout/geopoint_layout.xml
  collect_app/src/main/res/layout/geopoint_osm_layout.xml
  collect_app/src/main/res/layout/geoshape_google_layout.xml
  collect_app/src/main/res/layout/geoshape_osm_layout.xml
Labels: behavior verified

#2132 Fixed bugs related to collecting events for audit.csv
  collect_app/src/main/java/org/odk/collect/android/activities/EditFormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/utilities/TimerLogger.java
Labels: behavior verified

#2133 Fixed toggleButton in Get Blank Forms page, fix #2131
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java
Labels: behavior verified

#2155 New color picker
  collect_app/build.gradle
  collect_app/src/main/java/org/odk/collect/android/activities/DrawActivity.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ColorPickerDialog.java
  collect_app/src/main/res/values-af/strings.xml
  collect_app/src/main/res/values-am/strings.xml
  collect_app/src/main/res/values-ar/strings.xml
  collect_app/src/main/res/values-bn/strings.xml
  collect_app/src/main/res/values-ca/strings.xml
  collect_app/src/main/res/values-cs/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-et/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-hi/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-it/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-ka/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-lo-rLA/strings.xml
  collect_app/src/main/res/values-lt/strings.xml
  collect_app/src/main/res/values-mr/strings.xml
  collect_app/src/main/res/values-my/strings.xml
  collect_app/src/main/res/values-ne-rNP/strings.xml
  collect_app/src/main/res/values-nl/strings.xml
  collect_app/src/main/res/values-no/strings.xml
  collect_app/src/main/res/values-pl/strings.xml
  collect_app/src/main/res/values-pt/strings.xml
  collect_app/src/main/res/values-ro/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-sl/strings.xml
  collect_app/src/main/res/values-sq/strings.xml
  collect_app/src/main/res/values-sv-rSE/strings.xml
  collect_app/src/main/res/values-sw-rKE/strings.xml
  collect_app/src/main/res/values-sw/strings.xml
  collect_app/src/main/res/values-th-rTH/strings.xml
  collect_app/src/main/res/values-tl-rPH/strings.xml
  collect_app/src/main/res/values-tl/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values-ur-rPK/strings.xml
  collect_app/src/main/res/values-ur/strings.xml
  collect_app/src/main/res/values-vi/strings.xml
  collect_app/src/main/res/values-zh/strings.xml
  collect_app/src/main/res/values-zu/strings.xml
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#1831 Cancel Google sheet form upload when activity destroyed
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceGoogleSheetsUploader.java
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified
