Repository getodk/collect, pull requests merged in 2018-03, with the labels that each got.

#1874 Fix: Automatic keyboard visiblility (#1864)
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
Labels: needs testing, reviewed

#1953 Use auto-send attribute instead of auto-submit
  collect_app/src/main/java/org/odk/collect/android/database/helpers/FormsDatabaseHelper.java
  collect_app/src/main/java/org/odk/collect/android/provider/FormsProvider.java
  collect_app/src/main/java/org/odk/collect/android/provider/FormsProviderAPI.java
  collect_app/src/main/java/org/odk/collect/android/receivers/NetworkReceiver.java
  collect_app/src/main/java/org/odk/collect/android/tasks/DiskSyncTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormsTask.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
Labels: behavior verified, reviewed

#1955 Make Spinner widget open from start-of-list when nothing is selected
  collect_app/src/main/java/org/odk/collect/android/views/ScrolledToTopSpinner.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerWidget.java
  collect_app/src/main/res/layout/spinner_layout.xml
Labels: behavior verified, reviewed

#1940 Deleted OpenSourceLicensesActivity
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/AboutActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/OpenSourceLicensesActivity.java
  collect_app/src/main/res/layout/activity_open_source_licenses.xml
Labels: behavior verified, reviewed

#1962 Collect 1961
  collect_app/src/androidTest/java/org/odk/collect/android/tasks/InstanceServerUploaderTest.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceServerUploader.java
Labels: reviewed

#1951 Implementations for range widgets tests
  collect_app/src/androidTest/assets/all_widgets.xml
  collect_app/src/androidTest/java/org/odk/collect/android/AllWidgetsFormTest.java
Labels: reviewed

#1908 Better Labels in About Activity ( as seen in #1846)
  collect_app/src/main/java/org/odk/collect/android/activities/AboutActivity.java
  collect_app/src/main/res/values/strings.xml
Labels: reviewed

#1929 debounce AboutActivity. Fix #1917.
  collect_app/src/main/java/org/odk/collect/android/activities/AboutActivity.java
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
Labels: behavior verified, reviewed

#1963 Fixed current value not appearing when tapping on the min value
  collect_app/src/main/java/org/odk/collect/android/widgets/RangeWidget.java
Labels: behavior verified, reviewed

#1967 Update javarosa
  collect_app/build.gradle
Labels: behavior verified, reviewed

#1880 Reuse the last generated QR Code if the settings have not changed
  collect_app/src/androidTest/java/org/odk/collect/android/settings/QrCodeTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java
  collect_app/src/main/java/org/odk/collect/android/listeners/ActionListener.java
  collect_app/src/main/java/org/odk/collect/android/preferences/GeneralSharedPreferences.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/SharedPreferencesUtils.java
  collect_app/src/main/res/layout/show_qrcode_fragment.xml
  collect_app/src/test/java/org/odk/collect/android/utilities/QRCodeUtilsTest.java
Labels: behavior verified

#1947 Refactors FormEntryActivity
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/dao/helpers/ContentResolverHelper.java
  collect_app/src/main/java/org/odk/collect/android/dao/helpers/FormsDaoHelper.java
  collect_app/src/main/java/org/odk/collect/android/dao/helpers/InstancesDaoHelper.java
  collect_app/src/main/java/org/odk/collect/android/logic/FormInfo.java
Labels: behavior verified, reviewed

#1968 Fix : Error logs in code segments
  collect_app/src/main/java/org/odk/collect/android/activities/AboutActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/DrawActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/EditFormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/SplashScreenActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/ViewFormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/external/ExternalDataUtil.java
  collect_app/src/main/java/org/odk/collect/android/logic/FormController.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
  collect_app/src/main/java/org/odk/collect/android/views/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
Labels: reviewed

#1821 Nested groups with `field-list` appearance
  collect_app/src/androidTest/assets/forms/formNavigationTestForms/fieldListInFieldList.xml
  collect_app/src/androidTest/assets/forms/formNavigationTestForms/fieldListWithQuestionAndRegularGroupInside.xml
  collect_app/src/androidTest/assets/forms/formNavigationTestForms/fieldListWithQuestionsAndRegularGroupsInside.xml
  collect_app/src/androidTest/assets/forms/formNavigationTestForms/regularGroupWithFieldListGroupInside.xml
  collect_app/src/androidTest/assets/forms/formNavigationTestForms/regularGroupWithQuestionAndRegularGroupInside.xml
  collect_app/src/androidTest/assets/forms/formNavigationTestForms/regularGroupWithQuestionsAndRegularGroupInside.xml
  collect_app/src/androidTest/assets/forms/formNavigationTestForms/simpleFieldList.xml
  collect_app/src/androidTest/assets/forms/formNavigationTestForms/threeNestedFieldListGroups.xml
  collect_app/src/androidTest/assets/forms/formNavigationTestForms/twoNestedRegularGroups.xml
  collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java
  collect_app/src/main/java/org/odk/collect/android/logic/FormController.java
Labels: behavior verified

#1974 Fixed java.lang.IllegalArgumentException
  collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferences.java
  collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceServerUploader.java
  collect_app/src/main/java/org/odk/collect/android/utilities/WebUtils.java
Labels: behavior verified, reviewed

#1993 Update jacoco to latest release v0.8.0
  build.gradle
  collect_app/build.gradle
  config/quality.gradle
Labels: reviewed

#1994 Reset shared preferences before starting the QRCodeUtils tests
  collect_app/src/test/java/org/odk/collect/android/utilities/QRCodeUtilsTest.java
Labels: reviewed

#1829 Save cached form asynchronously
  collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/listeners/FormLoaderListener.java
  collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormDefCache.java
Labels: needs testing

#1991 Updated dependencies that do not need Play Services Update (Fixed #1990)
  collect_app/build.gradle
Labels: reviewed

#1995 Exclude auto-generated classes by ButterKnife and Dagger from findbugs and code coverage
  collect_app/build.gradle
  config/checkstyle.xml
  config/findbugs-filter.xml
  config/jacoco.gradle
  config/lint.xml
  config/pmd-ruleset.xml
  config/quality.gradle
Labels: reviewed

#1988 Support ImageMap widgets on Android 4
  collect_app/src/main/assets/svg_map_helper.js
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectImageMapWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
Labels: behavior verified, reviewed

#1986 Fixed inconsistency geopoint widgets button name
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoPointWidget.java
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified, reviewed

#1987 Background color change can be removed. Fix #1975
  collect_app/src/main/java/org/odk/collect/android/views/MediaLayout.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectWidget.java
Labels: behavior verified

#1989 Removed Menu from Get Blank Form Activity. Fixes #1937
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java
Labels: behavior verified, reviewed

#2001 Fixed NullPointerException: Attempt to get length of null array
  collect_app/src/main/java/org/odk/collect/android/provider/FormsProvider.java
Labels: reviewed

#1998 Fixed NullPointerException when formController.getInstancePath() is null
  collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormIndexSavepointTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/dao/helpers/InstancesDaoHelper.java
  collect_app/src/main/java/org/odk/collect/android/database/ActivityLogger.java
  collect_app/src/main/java/org/odk/collect/android/external/ExternalAppsUtils.java
  collect_app/src/main/java/org/odk/collect/android/logic/FormController.java
  collect_app/src/main/java/org/odk/collect/android/tasks/SaveFormIndexTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/SavePointTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java
  collect_app/src/main/java/org/odk/collect/android/widgets/OSMWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/test/java/org/odk/collect/android/widgets/OSMWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/FileWidgetTest.java
Labels: reviewed

#1970 Google drive dynamic search bar
  collect_app/src/main/java/org/odk/collect/android/activities/AppListActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java
  collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java
  collect_app/src/main/res/drawable-mdpi/ic_action_action_search.png
  collect_app/src/main/res/drawable-xhdpi/ic_action_action_search.png
  collect_app/src/main/res/layout/drive_layout.xml
  collect_app/src/main/res/values-af/strings.xml
  collect_app/src/main/res/values-am/strings.xml
  collect_app/src/main/res/values-ar/strings.xml
  collect_app/src/main/res/values-ca/strings.xml
  collect_app/src/main/res/values-cs/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-et/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-hi/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-it/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-ka/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-lo-rLA/strings.xml
  collect_app/src/main/res/values-mr/strings.xml
  collect_app/src/main/res/values-ne-rNP/strings.xml
  collect_app/src/main/res/values-nl/strings.xml
  collect_app/src/main/res/values-no/strings.xml
  collect_app/src/main/res/values-pl/strings.xml
  collect_app/src/main/res/values-pt/strings.xml
  collect_app/src/main/res/values-ro/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-sq/strings.xml
  collect_app/src/main/res/values-sv-rSE/strings.xml
  collect_app/src/main/res/values-th-rTH/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified, reviewed

#1982 Introduce string resources for format arguments of activity_not_found resource string
  collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java
  collect_app/src/main/java/org/odk/collect/android/views/MediaLayout.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DrawWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWebViewWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SignatureWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
  collect_app/src/main/res/values/strings.xml
Labels: needs review

#2017 Removed unused string resource. Fixed #2011
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values/strings.xml
Labels: reviewed

#1966 Add tests for ArrayUtils
  collect_app/src/test/java/org/odk/collect/android/utilities/ArrayUtilsTest.java
Labels: reviewed

#2034 change save icon to vector (#1858)
  collect_app/src/main/res/drawable-hdpi/ic_menu_save.png
  collect_app/src/main/res/drawable-ldpi/ic_menu_save.png
  collect_app/src/main/res/drawable-mdpi/ic_menu_save.png
  collect_app/src/main/res/drawable-xhdpi/ic_menu_save.png
  collect_app/src/main/res/drawable/ic_save_black_32dp.xml
  collect_app/src/main/res/menu/form_menu.xml
Labels: needs review

#1851 Support repeats in Google Sheets
  collect_app/src/androidTest/java/org/odk/collect/android/tasks/InstanceServerUploaderTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java
  collect_app/src/main/java/org/odk/collect/android/logic/FormController.java
  collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceGoogleSheetsUploader.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceServerUploader.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploader.java
  collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/SheetsHelper.java
  collect_app/src/main/res/values-af/strings.xml
  collect_app/src/main/res/values-am/strings.xml
  collect_app/src/main/res/values-ar/strings.xml
  collect_app/src/main/res/values-ca/strings.xml
  collect_app/src/main/res/values-cs/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-et/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-hi/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-it/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-lo-rLA/strings.xml
  collect_app/src/main/res/values-mr/strings.xml
  collect_app/src/main/res/values-ne-rNP/strings.xml
  collect_app/src/main/res/values-nl/strings.xml
  collect_app/src/main/res/values-no/strings.xml
  collect_app/src/main/res/values-pl/strings.xml
  collect_app/src/main/res/values-pt/strings.xml
  collect_app/src/main/res/values-ro/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-sq/strings.xml
  collect_app/src/main/res/values-sv-rSE/strings.xml
  collect_app/src/main/res/values-th-rTH/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values/strings.xml
  collect_app/src/test/java/org/odk/collect/android/utilities/InstanceGoogleSheetsUploaderTest.java
  collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/SheetsHelperTest.java
Labels: behavior verified, reviewed

#2026 Address inconsistency between SelectOne widgets ,fix issue #1855
  collect_app/src/main/assets/svg_map_helper.js
Labels: behavior verified, reviewed

#2021 Don't use GoogleLocationClient even if Play Services available.
  collect_app/src/main/java/org/odk/collect/android/location/client/LocationClients.java
Labels: needs review, needs testing

#2040 Upgrade Javarosa
  collect_app/build.gradle
Labels: needs testing

#1969 Refactored Itemset widget
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/dao/ItemsetDao.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormEntryPromptUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AbstractSelectOneWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ItemsetWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectImageMapWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectMultipleAutocompleteWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectOneAutoAdvanceWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectOneSearchWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectOneWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectTextWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ItemsetWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/SelectOneAutoAdvanceWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/SelectOneWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/QuestionWidgetTest.java
Labels: behavior verified, reviewed

#2033 Removes wrapper class for Base64
  collect_app/src/main/java/org/odk/collect/android/utilities/Base64Wrapper.java
  collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java
  collect_app/src/main/res/values-ar/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-et/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-hi/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-it/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-mr/strings.xml
  collect_app/src/main/res/values-pl/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-sq/strings.xml
  collect_app/src/main/res/values-sv-rSE/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified, reviewed

#2024 Display warning in SelectMultiWidget when select_multiple names have spaces in them #1964
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectMultiWidget.java
  collect_app/src/main/res/values/strings.xml
Labels: needs discussion

#1985 video widget with selfie/new-front appearance
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieVideoActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieVideoActivityNewApi.java
  collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/Camera2VideoFragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/ErrorDialog.java
  collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java
  collect_app/src/main/java/org/odk/collect/android/views/CameraPreview.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
  collect_app/src/main/res/layout/activity_capture_selfie_video_new_api.xml
  collect_app/src/main/res/layout/fragment_camera2video.xml
  collect_app/src/main/res/values/strings.xml
Labels: needs review, needs testing

#2051 Toggle button text fix #2039
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java
Labels: behavior verified

#2055 Fix required dateTime
  collect_app/src/main/java/org/odk/collect/android/widgets/DateTimeWidget.java
Labels: behavior verified

#2066 Last fixes for repeatable groups
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceGoogleSheetsUploader.java
Labels: behavior verified

#2050 Addressed rotation problems in RangeWidget under RTL languages. Fix #1983
  collect_app/src/main/java/org/odk/collect/android/widgets/RangeWidget.java
  collect_app/src/main/res/layout-v17/range_widget_horizontal.xml
Labels: behavior verified, needs review

#2082 Forms are not marked when user scrolls up and down
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java
  collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java
Labels: behavior verified
