Repository getodk/collect, pull requests merged in 2018-05, with the labels that each got.

#2157 Toggle button in "Send Finalized Form" and "Delete Saved Form"
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderList.java
  collect_app/src/main/java/org/odk/collect/android/fragments/FileManagerFragment.java
Labels: behavior verified

#2139 Arbitrary file widget
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationConstants.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/main/res/drawable/ic_attachment.xml
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#2166 Undo our failed attempt at reliable asynchronous FormDef cache saving
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormDefCache.java
Labels: behavior verified, high priority

#2170 'Connecting to Server' dialog closes when screen orientation changes
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java
Labels: behavior verified

#2105 Guidance hint solution that resolves #2007
  collect_app/src/androidTest/assets/guidance_hint_form.xml
  collect_app/src/androidTest/java/org/odk/collect/android/GuidanceHintFormTest.java
  collect_app/src/main/java/org/odk/collect/android/listeners/Result.java
  collect_app/src/main/java/org/odk/collect/android/preferences/FormManagementPreferences.java
  collect_app/src/main/java/org/odk/collect/android/preferences/GuidanceHint.java
  collect_app/src/main/java/org/odk/collect/android/preferences/PreferenceKeys.java
  collect_app/src/main/java/org/odk/collect/android/utilities/AnimateUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/UiUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DateTimeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/res/drawable/information_outline.xml
  collect_app/src/main/res/layout/help_text_layout.xml
  collect_app/src/main/res/values/arrays.xml
  collect_app/src/main/res/values/colors.xml
  collect_app/src/main/res/values/strings.xml
  collect_app/src/main/res/xml/form_management_preferences.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: behavior verified

#2148 Scrolling to the current question doesn't work after opening the HierarchyView if a question is in a field-list
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/logic/FormController.java
Labels: behavior verified

#2121 Fixes #1052 - Lack of altitude and accuracy when we use location
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceGoogleSheetsUploader.java
Labels: behavior verified, needs review

#2169 Resolved crash when downloading forms from Google Server
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java
Labels: behavior verified

#2119 Storage runtime permissions resolves #644
  collect_app/build.gradle
  collect_app/src/androidTest/java/org/odk/collect/android/AllWidgetsFormTest.java
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/CollectAbstractActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormChooserList.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderList.java
  collect_app/src/main/java/org/odk/collect/android/activities/SplashScreenActivity.java
  collect_app/src/main/java/org/odk/collect/android/listeners/PermissionListener.java
  collect_app/src/main/java/org/odk/collect/android/provider/FormsProvider.java
  collect_app/src/main/java/org/odk/collect/android/provider/InstanceProvider.java
  collect_app/src/main/java/org/odk/collect/android/utilities/PermissionUtils.java
  collect_app/src/main/res/drawable/sd.xml
  collect_app/src/main/res/values/strings.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: behavior verified

#2186 Respect short label forms
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
Labels: behavior verified

#2182 Capitalize 'gps' in user-facing notifications. Closes #2156.
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointOsmMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/utilities/GeoPointUtils.java
  collect_app/src/test/java/org/odk/collect/android/utilities/GeoPointUtilsTest.java
Labels: behavior verified

#2161 Issue #943 widget redundancy
  collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DrawWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SignatureWidget.java
Labels: behavior verified

#2192 Fixed crash in Import/Export settings
  collect_app/src/main/res/menu/settings_menu.xml
Labels: behavior verified

#2172 List items added to selectedInstances when 'Select all' is clicked
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderList.java
  collect_app/src/main/java/org/odk/collect/android/fragments/DataManagerList.java
  collect_app/src/main/java/org/odk/collect/android/fragments/FormManagerList.java
Labels: behavior verified

#2201 Fixed dropdown icon
  collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java
  collect_app/src/main/res/drawable-hdpi/ic_arrow_drop_down.png
  collect_app/src/main/res/drawable-mdpi/ic_arrow_drop_down.png
  collect_app/src/main/res/drawable-xhdpi/ic_arrow_drop_down.png
  collect_app/src/main/res/drawable-xxhdpi/ic_arrow_drop_down.png
  collect_app/src/main/res/drawable-xxxhdpi/ic_arrow_drop_down.png
  collect_app/src/main/res/drawable/ic_arrow_drop_down.xml
Labels: behavior verified

#2223 Revert using hyperlink for gsheets attachments
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceGoogleSheetsUploader.java
Labels: behavior verified, high priority

#2216 Hide old form versions
  collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormUtilsTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormChooserList.java
  collect_app/src/main/java/org/odk/collect/android/dao/FormsDao.java
  collect_app/src/main/java/org/odk/collect/android/dto/Form.java
  collect_app/src/main/java/org/odk/collect/android/preferences/AdminKeys.java
  collect_app/src/main/java/org/odk/collect/android/preferences/PreferenceKeys.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormUtils.java
  collect_app/src/main/res/values/strings.xml
  collect_app/src/main/res/xml/form_management_preferences.xml
  collect_app/src/main/res/xml/user_settings_access_preferences.xml
Labels: behavior verified, high priority

#2227 Fixed notification icon
  collect_app/src/main/java/org/odk/collect/android/receivers/NetworkReceiver.java
  collect_app/src/main/java/org/odk/collect/android/tasks/ServerPollingJob.java
  collect_app/src/main/java/org/odk/collect/android/utilities/IconUtils.java
  collect_app/src/main/res/drawable-mdpi/ic_notes_white_png.png
  collect_app/src/main/res/drawable/ic_notes_white.xml
Labels: behavior verified

#2220 Lighten the color of popup dialog of Spinner widget for dark theme
  collect_app/src/main/java/org/odk/collect/android/utilities/ThemeUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerWidget.java
  collect_app/src/main/res/values/colors.xml
Labels: behavior verified

#2184 Highlight question that has caused validation error in field list
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
  collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/utilities/SoftKeyboardUtils.java
  collect_app/src/main/java/org/odk/collect/android/views/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AbstractDateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BearingWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BooleanWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DateTimeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoPointWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoShapeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoTraceWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GridMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GridWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWebViewWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/LabelWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ListMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ListWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/OSMWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/RangeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectMultipleAutocompleteWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectOneSearchWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/StringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/TimeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/TriggerWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
  collect_app/src/main/res/layout/reset_dialog_layout.xml
  collect_app/src/main/res/values/colors.xml
Labels: behavior verified

#2123 Fixed Media Layout in RTL, fix #2101.
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/views/MediaLayout.java
  collect_app/src/main/java/org/odk/collect/android/views/ODKView.java
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#2162 Fixed invalid shapes and lines in GeoWidget, fix #1124
  collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeGoogleMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeOsmMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceGoogleMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceOsmMapActivity.java
  collect_app/src/main/res/values-am/strings.xml
  collect_app/src/main/res/values-ar/strings.xml
  collect_app/src/main/res/values-ca/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-et/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-hi/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-it/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-mr/strings.xml
  collect_app/src/main/res/values-pl/strings.xml
  collect_app/src/main/res/values-pt/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-sq/strings.xml
  collect_app/src/main/res/values-sv-rSE/strings.xml
  collect_app/src/main/res/values-sw-rKE/strings.xml
  collect_app/src/main/res/values-th-rTH/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values/strings.xml
Labels: needs testing

#2234 Resolved error that caused FormEntryActivity to go to the FormChooser List
  collect_app/src/main/java/org/odk/collect/android/activities/FormChooserList.java
Labels: behavior verified, high priority

#2239 Fixed problem with vector drawables
  collect_app/src/main/java/org/odk/collect/android/activities/EditFormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointOsmMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeOsmMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceOsmMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/ViewFormHierarchyActivity.java
Labels: behavior verified, high priority

#2189 FIx #2159 The user is not able to add audio and video from Google Drive.
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
Labels: behavior verified

#2260 Using 'maps placement-map' appearance has unexpected effect
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoPointWidget.java
Labels: behavior verified

#2242 Dark mode improvements
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointOsmMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeGoogleMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeOsmMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceGoogleMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceOsmMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ThemeUtils.java
  collect_app/src/main/java/org/odk/collect/android/views/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectOneSearchWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectWidget.java
  collect_app/src/main/res/drawable/ic_place_black.xml
  collect_app/src/main/res/drawable/polygon.xml
  collect_app/src/main/res/drawable/polyline.xml
  collect_app/src/main/res/layout/geo_zoom_dialog.xml
  collect_app/src/main/res/layout/geoshape_zoom_dialog.xml
  collect_app/src/main/res/layout/polygon_polyline_dialog.xml
Labels: behavior verified

#2237 Fixed RadioButtons and CheckBoxes in Dark Theme.
  collect_app/src/main/java/org/odk/collect/android/preferences/BasePreferenceFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/DisabledPreferencesRemover.java
  collect_app/src/main/java/org/odk/collect/android/preferences/GeneralPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/IdentityPreferences.java
  collect_app/src/main/java/org/odk/collect/android/preferences/PreferencesActivity.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AbstractSelectOneWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BooleanWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ListMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ListWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/TriggerWidget.java
  collect_app/src/main/res/xml/form_management_preference_headers.xml
  collect_app/src/main/res/xml/general_preference_headers.xml
  collect_app/src/main/res/xml/general_preferences.xml
  collect_app/src/main/res/xml/identity_preferences.xml
  collect_app/src/main/res/xml/server_preference_headers.xml
  collect_app/src/main/res/xml/user_device_identity_preference_header.xml
  collect_app/src/main/res/xml/user_interface_preference_headers.xml
Labels: behavior verified
