Repository getodk/collect, pull requests merged in 2018-10, with the labels that each got.

#2598 Fixed PxUsage lint
  collect_app/src/main/res/layout/media_layout.xml
  collect_app/src/main/res/values/style.xml
  config/lint.xml
Labels: behavior verified

#2533 App crashes when the user tries to open `Admin Settings` if targetSdkVersion is set to 24
  collect_app/build.gradle
  collect_app/src/main/java/org/odk/collect/android/preferences/AdminPreferencesFragment.java
Labels: behavior verified

#2606 Add permission checks in FormDownloadList & InstanceUploaderActivity
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/SplashScreenActivity.java
  collect_app/src/main/java/org/odk/collect/android/utilities/DialogUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/PermissionUtils.java
Labels: high priority

#2608 Fixed the text color of the Submission transport setting
  collect_app/src/main/java/org/odk/collect/android/preferences/ExtendedCheckboxPreference.java
Labels: behavior verified

#2553 Merge GeoTrace{Google,Osm}MapActivity into GeoTraceActivity; add polyline support to MapFragment.
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceGoogleMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceOsmMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/map/GoogleMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/map/MapFragment.java
  collect_app/src/main/java/org/odk/collect/android/map/MapPoint.java
  collect_app/src/main/java/org/odk/collect/android/map/OsmMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoTraceWidget.java
  collect_app/src/main/res/layout/geotrace_google_layout.xml
  collect_app/src/main/res/layout/geotrace_layout.xml
  collect_app/src/main/res/layout/geotrace_osm_layout.xml
  collect_app/src/main/res/values-ar/strings.xml
  collect_app/src/main/res/values-bn/strings.xml
  collect_app/src/main/res/values-ca/strings.xml
  collect_app/src/main/res/values-cs/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-et/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-hi/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-it/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-mr/strings.xml
  collect_app/src/main/res/values-ne-rNP/strings.xml
  collect_app/src/main/res/values-pl/strings.xml
  collect_app/src/main/res/values-pt/strings.xml
  collect_app/src/main/res/values-ro/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-sl/strings.xml
  collect_app/src/main/res/values-sq/strings.xml
  collect_app/src/main/res/values-sv-rSE/strings.xml
  collect_app/src/main/res/values-sw/strings.xml
  collect_app/src/main/res/values-th-rTH/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values-ur/strings.xml
  collect_app/src/main/res/values/strings.xml
  collect_app/src/test/java/org/odk/collect/android/location/activities/GeoTraceActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/location/activities/GeoTraceGoogleMapActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/location/activities/GeoTraceOsmMapActivityTest.java
Labels: behavior verified

#2600 Use FileProvider to access video files
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
Labels: behavior verified

#2602 Use FileProvider to access image files (qr code)
  collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java
Labels: behavior verified

#2605 Use FileProvider to open image/video in MediaLayout
  collect_app/src/main/java/org/odk/collect/android/views/MediaLayout.java
Labels: behavior verified

#2563 Hide buttons if a question is readonly
  collect_app/src/main/java/org/odk/collect/android/widgets/AbstractDateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BearingWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DrawWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExPrinterWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoPointWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoShapeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoTraceWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWebViewWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/OSMWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/RangeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SignatureWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/TimeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
Labels: behavior verified

#2612 Loading form didn't end when it contained an empty field-list group
  collect_app/src/main/java/org/odk/collect/android/logic/FormController.java
Labels: behavior verified

#2627 Fixed bug in filtering items that caused crashes
  collect_app/src/main/java/org/odk/collect/android/adapters/AbstractSelectListAdapter.java
Labels: behavior verified

#2613 Get audio file from uri using ContentResolver
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
Labels: behavior verified

#2569 Fix crash when changing device orientation while choosing a big audio, video or arbitrary file
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/fragments/MediaLoadingFragment.java
  collect_app/src/main/java/org/odk/collect/android/tasks/MediaLoadingTask.java
  collect_app/src/main/res/values-cs/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-sw/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values-ur/strings.xml
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#2651 Remember selected date
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/CustomDatePickerDialog.java
Labels: behavior verified

#2653 Replace newline with space instead of clearing form name
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
Labels: behavior verified

#2648 Update error message for missing submission URL in Google Sheets uploader
  collect_app/src/main/java/org/odk/collect/android/utilities/UrlUtils.java
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified, high priority

#2664 Set OSM map allowable min zoom to 2, max zoom to 22.
  collect_app/src/main/java/org/odk/collect/android/map/OsmMapFragment.java
Labels: behavior verified, high priority

#2682 Fixed a bug in SelectmultipleWidget with autocomplete appearance
  collect_app/src/main/java/org/odk/collect/android/adapters/SelectMultipleListAdapter.java
Labels: behavior verified, high priority

#2668 Remove current() warning
  collect_app/build.gradle
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/main/res/values-af/strings.xml
  collect_app/src/main/res/values-am/strings.xml
  collect_app/src/main/res/values-ar/strings.xml
  collect_app/src/main/res/values-bn/strings.xml
  collect_app/src/main/res/values-ca/strings.xml
  collect_app/src/main/res/values-cs/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-et/strings.xml
  collect_app/src/main/res/values-fa/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-ha/strings.xml
  collect_app/src/main/res/values-hi/strings.xml
  collect_app/src/main/res/values-hu/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-it/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-ka/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-ln/strings.xml
  collect_app/src/main/res/values-lo-rLA/strings.xml
  collect_app/src/main/res/values-lt/strings.xml
  collect_app/src/main/res/values-mg/strings.xml
  collect_app/src/main/res/values-ml/strings.xml
  collect_app/src/main/res/values-mr/strings.xml
  collect_app/src/main/res/values-my/strings.xml
  collect_app/src/main/res/values-nb/strings.xml
  collect_app/src/main/res/values-ne-rNP/strings.xml
  collect_app/src/main/res/values-nl/strings.xml
  collect_app/src/main/res/values-no/strings.xml
  collect_app/src/main/res/values-pl/strings.xml
  collect_app/src/main/res/values-ps/strings.xml
  collect_app/src/main/res/values-pt/strings.xml
  collect_app/src/main/res/values-ro/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-si/strings.xml
  collect_app/src/main/res/values-sl/strings.xml
  collect_app/src/main/res/values-so/strings.xml
  collect_app/src/main/res/values-sq/strings.xml
  collect_app/src/main/res/values-sv-rSE/strings.xml
  collect_app/src/main/res/values-sw-rKE/strings.xml
  collect_app/src/main/res/values-sw/strings.xml
  collect_app/src/main/res/values-ta/strings.xml
  collect_app/src/main/res/values-th-rTH/strings.xml
  collect_app/src/main/res/values-ti/strings.xml
  collect_app/src/main/res/values-tl/strings.xml
  collect_app/src/main/res/values-tr/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values-ur-rPK/strings.xml
  collect_app/src/main/res/values-ur/strings.xml
  collect_app/src/main/res/values-uz/strings.xml
  collect_app/src/main/res/values-vi/strings.xml
  collect_app/src/main/res/values-zh/strings.xml
  collect_app/src/main/res/values-zu/strings.xml
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified, high priority

#2691 Use query to get latest versions of forms
  collect_app/src/androidTest/java/org/odk/collect/android/utilities/FormUtilsTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormChooserList.java
  collect_app/src/main/java/org/odk/collect/android/dao/FormsDao.java
  collect_app/src/main/java/org/odk/collect/android/provider/FormsProvider.java
  collect_app/src/main/java/org/odk/collect/android/provider/FormsProviderAPI.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormUtils.java
Labels: behavior verified, high priority
