Repository getodk/collect, pull requests merged in 2018-02, with the labels that each got.

#1841 fix: Selected text invisible for empty selections
  collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerMultiWidget.java
Labels: reviewed

#1845 Adding more devices
  README.md
Labels: reviewed

#1843 Switching between drives displays content properly
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java
Labels: reviewed

#1847 Update test device
  README.md
Labels: reviewed

#1852 Describe tags used on PRs
  CONTRIBUTING.md
Labels: reviewed

#1828 Mark required questions using an asterisk
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormEntryPromptUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
Labels: behavior verified, reviewed

#1840 View comma separated values for SelectMultiple in Hierarchy view
  collect_app/src/main/java/org/odk/collect/android/utilities/FormEntryPromptUtils.java
Labels: behavior verified, reviewed

#1865 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: reviewed

#1825 Blank space is visible after removing an image answer
  collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DrawWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SignatureWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/main/java/org/odk/collect/android/widgets/interfaces/BaseImageWidget.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ImageWidgetTest.java
Labels: behavior verified, needs discussion, needs information, reviewed

#1872 Don't require answer for trigger
  collect_app/src/androidTest/assets/all_widgets.xml
Labels: reviewed

#1863 Issue Fixed: Popup menu in Import/Export Settings exists only for one item
  collect_app/src/main/res/drawable/ic_menu_share.xml
  collect_app/src/main/res/menu/settings_menu.xml
Labels: behavior verified, reviewed

#1860 Set default OSM Basemap
  collect_app/src/main/java/org/odk/collect/android/preferences/PreferenceKeys.java
Labels: behavior verified

#1866 Removed no-value log from FormEntryActivity
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
Labels: reviewed

#1873 Remove "Choose" from image, audio, video prompts #108
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
Labels: behavior verified, reviewed

#1802 Adds icons to the About Activity
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/AboutActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/java/org/odk/collect/android/adapters/AboutListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/preferences/AboutPreferencesActivity.java
  collect_app/src/main/java/org/odk/collect/android/preferences/AboutPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/utilities/CustomTabHelper.java
  collect_app/src/main/res/drawable/ic_forum.xml
  collect_app/src/main/res/drawable/ic_review_rate.xml
  collect_app/src/main/res/drawable/ic_share.xml
  collect_app/src/main/res/drawable/ic_stars.xml
  collect_app/src/main/res/drawable/ic_website.xml
  collect_app/src/main/res/layout/about_item_layout.xml
  collect_app/src/main/res/layout/about_layout.xml
  collect_app/src/main/res/xml/about_preferences.xml
  collect_app/src/test/java/org/odk/collect/android/activities/MainActivityTest.java
Labels: behavior verified, reviewed

#1867 Form are selected after pressing clear all button
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderList.java
  collect_app/src/main/java/org/odk/collect/android/fragments/DataManagerList.java
  collect_app/src/main/java/org/odk/collect/android/fragments/FormManagerList.java
Labels: behavior verified, reviewed

#1870 Fixed toggle button doesn't work as expected
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderList.java
  collect_app/src/main/java/org/odk/collect/android/fragments/FileManagerFragment.java
Labels: behavior verified, reviewed

#1886 Update build.gradle
  collect_app/build.gradle
Labels: reviewed

#1818 Resolved mismatch between DB and file system caused by download cancellation
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java
  collect_app/src/main/java/org/odk/collect/android/dao/FormsDao.java
  collect_app/src/main/java/org/odk/collect/android/listeners/FormDownloaderListener.java
  collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormsTask.java
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#1837 Disable reset button if nothing selected
  collect_app/src/main/java/org/odk/collect/android/preferences/ResetDialogPreference.java
  collect_app/src/main/res/values-ar/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-et/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-hi/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-it/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-mr/strings.xml
  collect_app/src/main/res/values-pl/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-sq/strings.xml
  collect_app/src/main/res/values-sv-rSE/strings.xml
  collect_app/src/main/res/values-th-rTH/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#1869 Fixed navigation back button after skipping a repeat group
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/logic/FormController.java
Labels: behavior verified, reviewed

#1877 Fix #1552. Pictures taken by the SelfieWidget are rotated incorrectly on some devices.
  collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java
Labels: needs discussion, needs testing, reviewed

#1895 updated SelectOneWidget for RTL languages
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectOneWidget.java
Labels: reviewed

#1893 Fixes code coverage report generation on CircleCI
  .circleci/config.yml
  build.gradle
  codecov.yml
  collect_app/build.gradle
  config/quality.gradle
Labels: reviewed

#1896 Update February translations
  collect_app/src/main/res/values-am/strings.xml
  collect_app/src/main/res/values-ar/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-et/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-hi/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-it/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-mr/strings.xml
  collect_app/src/main/res/values-nl/strings.xml
  collect_app/src/main/res/values-pl/strings.xml
  collect_app/src/main/res/values-pt/strings.xml
  collect_app/src/main/res/values-ro/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-sq/strings.xml
  collect_app/src/main/res/values-sv-rSE/strings.xml
  collect_app/src/main/res/values-th-rTH/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
Labels: reviewed

#1898 Turn off debuggable builds for release
  collect_app/build.gradle
Labels: reviewed

#1899 Downgrade jacoco to 0.7.4+
  config/quality.gradle
Labels: reviewed

#1902 Fixes the misleading error message as seen in #1811
  collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java
Labels: reviewed

#1904 Image select one widget does not allow answer to be removed
  collect_app/src/main/assets/svg_map_helper.js
Labels: behavior verified, reviewed

#1892 Update selectedInstances when toggle is clicked. Fix #1884
  collect_app/src/main/java/org/odk/collect/android/fragments/DataManagerList.java
  collect_app/src/main/java/org/odk/collect/android/fragments/FormManagerList.java
Labels: behavior verified

#1930 Prepare release
  collect_app/build.gradle
Labels: reviewed

#1931 Update February translations.
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-hu/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-ne-rNP/strings.xml
  collect_app/src/main/res/values-ro/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
Labels: reviewed

#1911 FIx #1900 Pictures taken by the SelfieWidget are rotated incorrectly …
  collect_app/src/main/java/org/odk/collect/android/activities/CaptureSelfieActivity.java
Labels: behavior verified, reviewed

#1923 Implementation for the testTriggerWidget
  collect_app/src/androidTest/java/org/odk/collect/android/AllWidgetsFormTest.java
Labels: reviewed

#1924 All files in Google Drive now showing when user clears search text. F…
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java
Labels: needs discussion, needs testing

#1943 Fix: Handle image chooser intent
  collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java
Labels: behavior verified, reviewed

#1938 Disabling "select all" button when there is nothing to show
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java
Labels: behavior verified, reviewed

#1925 Adds tests for url validation
  collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/tasks/DiskSyncTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormsTask.java
  collect_app/src/main/java/org/odk/collect/android/utilities/UrlUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/Validator.java
  collect_app/src/test/java/org/odk/collect/android/utilities/ValidatorTest.java
Labels: reviewed
