Repository getodk/collect, pull requests merged in 2018-11, with the labels that each got.

#2659 Fixed the trash button logic in GeoWidget, Fix #2633
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointOsmMapActivity.java
Labels: behavior verified

#2723 Fixed form styling in choices
  collect_app/src/main/java/org/odk/collect/android/utilities/FormEntryPromptUtils.java
Labels: behavior verified, high priority

#2707 Improve naming of filtered form list including only newest
  collect_app/src/main/java/org/odk/collect/android/activities/FormChooserList.java
  collect_app/src/main/java/org/odk/collect/android/dao/FormsDao.java
  collect_app/src/main/java/org/odk/collect/android/provider/FormsProvider.java
  collect_app/src/main/java/org/odk/collect/android/provider/FormsProviderAPI.java
Labels: behavior verified, high priority

#2727 Using highContrastHighlight and making RGB values obsolete in GridWidget Issue #2718
  collect_app/src/main/java/org/odk/collect/android/widgets/GridMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GridWidget.java
Labels: behavior verified

#2732 Bump Dexter dependency to 5.0.0
  collect_app/build.gradle
Labels: needs testing
