Repository getodk/collect, pull requests merged in 2019-05, with the labels that each got.

#3044 Add activity alias for backwards compatibility
  collect_app/src/main/AndroidManifest.xml
Labels: high priority

#3023 Updates in field lists
  collect_app/src/androidTest/assets/fieldlist-updates.xml
  collect_app/src/androidTest/assets/intent-group.xml
  collect_app/src/androidTest/java/org/odk/collect/android/AllWidgetsFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/BaseFormEntryActivityTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/FormNavigationTestCase.java
  collect_app/src/androidTest/java/org/odk/collect/android/GuidanceHintFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/SmsSubmissionMemoryTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/formfilling/FieldListUpdateTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/formfilling/FormNavigationButtonTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/formfilling/IntentGroupTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/test/CustomMatchers.java
  collect_app/src/androidTest/java/org/odk/collect/android/test/FormLoadingUtils.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/adapters/SelectMultipleListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/listeners/WidgetValueChangedListener.java
  collect_app/src/main/java/org/odk/collect/android/logic/FormController.java
  collect_app/src/main/java/org/odk/collect/android/logic/ImmutableDisplayableQuestion.java
  collect_app/src/main/java/org/odk/collect/android/tasks/MediaLoadingTask.java
  collect_app/src/main/java/org/odk/collect/android/utilities/SoftKeyboardUtils.java
  collect_app/src/main/java/org/odk/collect/android/views/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AbstractDateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AbstractSelectOneWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioController.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BearingWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BooleanWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DateTimeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DecimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DrawWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExDecimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExIntegerWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoPointWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoShapeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoTraceWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GridMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GridWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/IntegerWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ListMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ListWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/OSMWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/RangeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/RatingWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectImageMapWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SignatureWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SpinnerWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/StringNumberWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/StringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/TimeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/TriggerWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
Labels: needs testing

#2662 Myanmar calendar
  build.gradle
  collect_app/build.gradle
  collect_app/src/main/assets/open_source_licenses.html
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/CustomDatePickerDialog.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/MyanmarDatePickerDialog.java
  collect_app/src/main/java/org/odk/collect/android/logic/DatePickerDetails.java
  collect_app/src/main/java/org/odk/collect/android/utilities/DateTimeUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/MyanmarDateUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DateTimeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/MyanmarDateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/test/java/org/odk/collect/android/utilities/DateTimeUtilsTest.java
  collect_app/src/test/java/org/odk/collect/android/utilities/DaylightSavingTest.java
  collect_app/src/test/java/org/odk/collect/android/utilities/MyanmarDateUtilsTest.java
  collect_app/src/test/java/org/odk/collect/android/views/MediaLayoutTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/AudioWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/BarcodeWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/BooleanWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/DateTimeWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/DateWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/DecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExDecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExIntegerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExStringWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/GeoPointWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/GeoShapeWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/GeoTraceWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/GridMultiWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/GridWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ImageWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/IntegerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ItemsetWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ListMultiWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ListWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/RangeDecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/RangeIntegerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/SelectMultiWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/SelectOneSearchWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/SelectOneWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/SpinnerMultiWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/SpinnerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/StringNumberWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/StringWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/TimeWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/TriggerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/UrlWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/VideoWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/ButtonWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/GeneralSelectOneWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/QuestionWidgetTest.java
  config/findbugs-filter.xml
  config/quality.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: needs testing

#3067 Call GoogleAccountCredential.getToken() from non-UI thread
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java
Labels: behavior verified

#3078 Remove option to save geotrace as polygon
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPolyActivity.java
  collect_app/src/main/res/drawable/polygon.xml
  collect_app/src/main/res/drawable/polygon_wrapped.xml
  collect_app/src/main/res/drawable/polyline.xml
  collect_app/src/main/res/drawable/polyline_wrapped.xml
  collect_app/src/main/res/layout/polygon_polyline_dialog.xml
  collect_app/src/main/res/values-ar/strings.xml
  collect_app/src/main/res/values-ca/strings.xml
  collect_app/src/main/res/values-cs/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-et/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-hi/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-it/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-mr/strings.xml
  collect_app/src/main/res/values-ne-rNP/strings.xml
  collect_app/src/main/res/values-nl/strings.xml
  collect_app/src/main/res/values-pl/strings.xml
  collect_app/src/main/res/values-pt/strings.xml
  collect_app/src/main/res/values-ro/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-sq/strings.xml
  collect_app/src/main/res/values-sr/strings.xml
  collect_app/src/main/res/values-sv-rSE/strings.xml
  collect_app/src/main/res/values-sw/strings.xml
  collect_app/src/main/res/values-th-rTH/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values-ur/strings.xml
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#3072 Tracking answer changes in audit file
  collect_app/src/androidTest/java/org/odk/collect/android/tasks/AuditEventSaveTaskTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/logic/AuditConfig.java
  collect_app/src/main/java/org/odk/collect/android/logic/AuditEvent.java
  collect_app/src/main/java/org/odk/collect/android/logic/FormController.java
  collect_app/src/main/java/org/odk/collect/android/tasks/AuditEventSaveTask.java
  collect_app/src/main/java/org/odk/collect/android/utilities/AuditEventLogger.java
  collect_app/src/main/java/org/odk/collect/android/utilities/DialogUtils.java
  collect_app/src/main/java/org/odk/collect/android/views/ODKView.java
  collect_app/src/test/java/org/odk/collect/android/logic/AuditConfigTest.java
  collect_app/src/test/java/org/odk/collect/android/logic/AuditEventTest.java
  collect_app/src/test/java/org/odk/collect/android/utilities/AuditEventLoggerTest.java
Labels: needs testing

#3074 Add Mapbox SDK as a map display engine (online map support only)
  README.md
  collect_app/build.gradle
  collect_app/src/main/assets/open_source_licenses.html
  collect_app/src/main/java/org/odk/collect/android/activities/BaseGeoMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPolyActivity.java
  collect_app/src/main/java/org/odk/collect/android/map/GoogleMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/map/MapboxMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/map/OsmMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/mapboxsdk/MapFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/GeneralKeys.java
  collect_app/src/main/java/org/odk/collect/android/preferences/UserInterfacePreferences.java
  collect_app/src/main/java/org/odk/collect/android/spatial/MapHelper.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoPointWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoShapeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoTraceWidget.java
  collect_app/src/main/res/drawable/empty.xml
  collect_app/src/main/res/values/arrays.xml
  collect_app/src/main/res/values/strings.xml
  collect_app/src/main/res/xml/user_interface_preferences.xml
  collect_app/src/test/java/org/odk/collect/android/location/activities/BaseGeoActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/location/activities/GeoPointActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/location/activities/GeoPointMapActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/location/activities/GeoPolyActivityTest.java
Labels: behavior verified

#3113 Escape newlines and quotes for CSV output
  collect_app/src/androidTest/java/org/odk/collect/android/tasks/AuditEventSaveTaskTest.java
  collect_app/src/main/java/org/odk/collect/android/logic/AuditEvent.java
Labels: behavior verified

#3107 Update the widget button label when GeoTrace or GeoShape returns data.
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoShapeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoTraceWidget.java
Labels: behavior verified
