Repository getodk/collect, pull requests merged in 2019-03, with the labels that each got.

#2881 Fixed TriggerWidget
  collect_app/src/main/java/org/odk/collect/android/widgets/TriggerWidget.java
Labels: behavior verified

#2898 Display progress bar only form forms that are being sent via SMS
  collect_app/src/main/java/org/odk/collect/android/adapters/InstanceUploaderAdapter.java
Labels: behavior verified

#2864 Using string format to improve "⋮" under Android 4.4
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/res/values-cs/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-pl/strings.xml
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#2915 Findbugs improvements
  collect_app/src/main/java/org/odk/collect/android/activities/DrawActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceActivity.java
  collect_app/src/main/java/org/odk/collect/android/dao/FormsDao.java
  collect_app/src/main/java/org/odk/collect/android/location/client/GoogleLocationClient.java
  collect_app/src/main/java/org/odk/collect/android/tasks/ServerPollingJob.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationConstants.java
  collect_app/src/main/java/org/odk/collect/android/utilities/DownloadFormListUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormDownloader.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BearingWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  config/findbugs-filter.xml
Labels: needs testing

#2926 Fixed attempt to re-open an already-closed object
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java
Labels: behavior verified

#2879 Fixed the real cause of NPEs related to FormController.
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/FormLoadingDialogFragment.java
Labels: behavior verified

#2799 Fixed TransactionTooLargeException in FormDownloadList activity
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java
  collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormDownloadListViewModel.java
Labels: behavior verified

#2930 Fixed reading files from Downloads dir.
  collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java
Labels: behavior verified

#2919 Shorten sheet title if it's too long
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceGoogleSheetsUploader.java
  collect_app/src/main/java/org/odk/collect/android/utilities/TextUtils.java
  collect_app/src/test/java/org/odk/collect/android/utilities/TextUtilsTest.java
Labels: behavior verified

#2933 Geo: Use one activity for GeoTrace and GeoShape.
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPolyActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeActivity.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoShapeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoTraceWidget.java
  collect_app/src/main/res/layout/geopoly_dialog.xml
  collect_app/src/main/res/layout/geopoly_layout.xml
  collect_app/src/main/res/layout/geoshape_layout.xml
  collect_app/src/main/res/layout/polygon_polyline_dialog.xml
  collect_app/src/main/res/values-ar/strings.xml
  collect_app/src/main/res/values-ca/strings.xml
  collect_app/src/main/res/values-cs/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-et/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-hi/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-it/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-mr/strings.xml
  collect_app/src/main/res/values-ne-rNP/strings.xml
  collect_app/src/main/res/values-pl/strings.xml
  collect_app/src/main/res/values-pt/strings.xml
  collect_app/src/main/res/values-ro/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-sq/strings.xml
  collect_app/src/main/res/values-sv-rSE/strings.xml
  collect_app/src/main/res/values-sw/strings.xml
  collect_app/src/main/res/values-th-rTH/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values-ur/strings.xml
  collect_app/src/main/res/values/strings.xml
  collect_app/src/test/java/org/odk/collect/android/location/activities/GeoPolyActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/location/activities/GeoTraceActivityTest.java
Labels: behavior verified

#2943 Fixed the problem with finding an instance file during sending a form to GoogleSheets
  collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceGoogleSheetsUploader.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
Labels: behavior verified

#2951 Display progres dialog during reading files from GD
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#2769 New Dagger configuration
  CONTRIBUTING.md
  collect_app/build.gradle
  collect_app/src/androidTest/java/org/odk/collect/android/location/GeoActivityTest.java
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/CollectAbstractActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormChooserList.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderListActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/SplashScreenActivity.java
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
  collect_app/src/main/java/org/odk/collect/android/application/TestCollect.java
  collect_app/src/main/java/org/odk/collect/android/architecture/MVVMActivity.java
  collect_app/src/main/java/org/odk/collect/android/architecture/MVVMViewModel.java
  collect_app/src/main/java/org/odk/collect/android/architecture/rx/RxMVVMActivity.java
  collect_app/src/main/java/org/odk/collect/android/architecture/rx/RxMVVMViewModel.java
  collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java
  collect_app/src/main/java/org/odk/collect/android/injection/ActivityBuilder.java
  collect_app/src/main/java/org/odk/collect/android/injection/DaggerUtils.java
  collect_app/src/main/java/org/odk/collect/android/injection/ViewModelBuilder.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/architecture/ActivityViewModelProvider.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/architecture/ViewModelFactory.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/architecture/ViewModelFactoryModule.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/architecture/ViewModelKey.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/scopes/PerActivity.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/scopes/PerApplication.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/scopes/PerViewModel.java
  collect_app/src/main/java/org/odk/collect/android/location/GeoActivity.java
  collect_app/src/main/java/org/odk/collect/android/location/GeoViewModel.java
  collect_app/src/main/java/org/odk/collect/android/preferences/FormMetadataFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/tasks/sms/SmsNotificationReceiver.java
  collect_app/src/main/java/org/odk/collect/android/tasks/sms/models/SmsSubmission.java
  collect_app/src/main/java/org/odk/collect/android/utilities/PermissionUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoPointWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoShapeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoTraceWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWebViewWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
  collect_app/src/main/res/layout/activity_geo.xml
  collect_app/src/test/java/org/odk/collect/android/activities/InstanceUploaderListActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/activities/MainActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/http/CollectServerClientTest.java
  collect_app/src/test/java/org/odk/collect/android/injection/TestComponent.java
  collect_app/src/test/java/org/odk/collect/android/injection/TestModule.java
  collect_app/src/test/java/org/odk/collect/android/sms/SmsSenderJobTest.java
  collect_app/src/test/java/org/odk/collect/android/sms/SmsServiceTest.java
  collect_app/src/test/java/org/odk/collect/android/support/RobolectricHelpers.java
Labels: behavior verified

#2914 Fixed newlines visible in submission name
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/logic/FormController.java
  collect_app/src/main/java/org/odk/collect/android/utilities/RegexUtils.java
  collect_app/src/test/java/org/odk/collect/android/utilities/RegexUtilsTest.java
Labels: behavior verified

#2957 Fixed enabled but grayed out rows
  collect_app/src/main/java/org/odk/collect/android/adapters/InstanceListCursorAdapter.java
Labels: behavior verified

#2876 Fix: Don't step into very first group automatically
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
Labels: behavior verified

#2960 Fixes Main Menu Visibility for Admin Mode ( #2958 )
  collect_app/src/main/java/org/odk/collect/android/preferences/FormManagementPreferences.java
  collect_app/src/main/java/org/odk/collect/android/preferences/GeneralPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/IdentityPreferences.java
  collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferences.java
  collect_app/src/main/java/org/odk/collect/android/preferences/UserInterfacePreferences.java
Labels: behavior verified

#2953 Catch StackOverflowError
  collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#2964 Remove unused analytics
  collect_app/src/main/java/org/odk/collect/android/external/ExternalDataUtil.java
  collect_app/src/main/java/org/odk/collect/android/external/handler/ExternalDataHandlerPull.java
  collect_app/src/main/java/org/odk/collect/android/logic/FormController.java
  collect_app/src/main/java/org/odk/collect/android/preferences/UserInterfacePreferences.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
Labels: behavior verified

#2940 Geo: Use more precise map markers in geo activities.
  collect_app/src/main/java/org/odk/collect/android/map/GoogleMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/map/OsmMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/utilities/IconUtils.java
  collect_app/src/main/res/drawable/ic_crosshairs.xml
  collect_app/src/main/res/drawable/ic_map_point.xml
  collect_app/src/main/res/values/colors.xml
Labels: behavior verified

#2882 Remembering previously entered values (auto-fill)
  collect_app/src/main/java/org/odk/collect/android/logic/FormController.java
  collect_app/src/main/java/org/odk/collect/android/provider/FormsProvider.java
  collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceSyncTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceGoogleSheetsUploader.java
  collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/OSMWidget.java
Labels: behavior verified

#2976 Support long press to add points
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPolyActivity.java
Labels: behavior verified

#2974 Don't recenter the map if user is manually placing points
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPolyActivity.java
Labels: behavior verified, high priority
