Repository getodk/collect, pull requests merged in 2019-08, with the labels that each got.

#3269 Fixed header dates
  collect_app/src/main/java/org/odk/collect/android/http/OkHttpConnection.java
Labels: behavior verified

#3259 Make raster tiles 100% opaque on Mapbox maps.
  collect_app/src/main/java/org/odk/collect/android/geo/MapboxMapFragment.java
Labels: behavior verified

#3268 Added scrollbar in About View
  collect_app/src/main/res/layout/about_layout.xml
Labels: behavior verified

#3282 Upgrade OKHttp3 to allow unicode in headers
  build.gradle
Labels: needs testing

#3288 Upgrade to JavaRosa v2.15.1
  collect_app/build.gradle
Labels: needs testing

#3289 Ensure OpenRosa requests use correct auth schemes
  collect_app/src/main/java/org/odk/collect/android/http/OkHttpConnection.java
  collect_app/src/test/java/org/odk/collect/android/http/OpenRosaGetRequestTest.java
Labels: behavior verified, high priority

#3242 Sort the items in the Layer data file dialog.
  collect_app/src/main/java/org/odk/collect/android/preferences/CaptionedListPreference.java
  collect_app/src/main/java/org/odk/collect/android/preferences/MapsPreferences.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
Labels: behavior verified

#3278 Display whole labels in select_one minimal widget
  collect_app/src/androidTest/assets/forms/select_minimal.xml
  collect_app/src/androidTest/java/org/odk/collect/android/espressoutils/FormEntry.java
  collect_app/src/androidTest/java/org/odk/collect/android/formentry/SelectMinimalTest.java
  collect_app/src/main/java/org/odk/collect/android/adapters/SpinnerAdapter.java
Labels: behavior verified

#3217 Reorganize theme resources
  CONTRIBUTING.md
  collect_app/src/main/java/org/odk/collect/android/adapters/SpinnerAdapter.java
  collect_app/src/main/java/org/odk/collect/android/utilities/PermissionUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ThemeUtils.java
  collect_app/src/main/res/color/dark_theme_tint_list.xml
  collect_app/src/main/res/color/light_theme_tint_list.xml
  collect_app/src/main/res/drawable/ic_star_border.xml
  collect_app/src/main/res/layout/file_manager_list.xml
  collect_app/src/main/res/layout/form_chooser_list.xml
  collect_app/src/main/res/layout/form_chooser_list_item_text.xml
  collect_app/src/main/res/layout/form_download_list.xml
  collect_app/src/main/res/layout/google_drive_list.xml
  collect_app/src/main/res/layout/instance_uploader_list.xml
  collect_app/src/main/res/layout/main_menu.xml
  collect_app/src/main/res/layout/media_layout.xml
  collect_app/src/main/res/values-v21/theme.xml
  collect_app/src/main/res/values/attrs.xml
  collect_app/src/main/res/values/colors.xml
  collect_app/src/main/res/values/dark_theme.xml
  collect_app/src/main/res/values/form_entry_activity_theme.xml
  collect_app/src/main/res/values/light_theme.xml
  collect_app/src/main/res/values/permission_dialog_theme.xml
  collect_app/src/main/res/values/settings_theme.xml
  collect_app/src/main/res/values/style.xml
  collect_app/src/main/res/values/styles.xml
  collect_app/src/main/res/values/theme.xml
  collect_app/src/test/java/org/odk/collect/android/utilities/ThemeUtilsTests.java
Labels: behavior verified

#3302 Extract authentication and common headers from OkHttpConnection
  collect_app/src/androidTest/java/org/odk/collect/android/ServerNameIndicationTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/utilities/CollectServerClientTest.java
  collect_app/src/main/java/org/odk/collect/android/http/CollectServerClient.java
  collect_app/src/main/java/org/odk/collect/android/http/CollectThenSystemContentTypeMapper.java
  collect_app/src/main/java/org/odk/collect/android/http/okhttp/OkHttpConnection.java
  collect_app/src/main/java/org/odk/collect/android/http/okhttp/OkHttpOpenRosaServerClientFactory.java
  collect_app/src/main/java/org/odk/collect/android/http/openrosa/OpenRosaHttpInterface.java
  collect_app/src/main/java/org/odk/collect/android/http/openrosa/OpenRosaServerClient.java
  collect_app/src/main/java/org/odk/collect/android/http/openrosa/OpenRosaServerClientFactory.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceServerUploaderTask.java
  collect_app/src/main/java/org/odk/collect/android/upload/AutoSendWorker.java
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java
  collect_app/src/main/java/org/odk/collect/android/utilities/Clock.java
  collect_app/src/test/java/org/odk/collect/android/http/OkHttpConnectionGetRequestTest.java
  collect_app/src/test/java/org/odk/collect/android/http/OkHttpConnectionHeadRequestTest.java
  collect_app/src/test/java/org/odk/collect/android/http/OkHttpConnectionPostRequest.java
  collect_app/src/test/java/org/odk/collect/android/http/OkHttpOpenRosaServerClientFactoryTest.java
  collect_app/src/test/java/org/odk/collect/android/http/OpenRosaGetRequestTest.java
  collect_app/src/test/java/org/odk/collect/android/http/OpenRosaHeadRequestTest.java
  collect_app/src/test/java/org/odk/collect/android/http/OpenRosaPostRequestTest.java
  collect_app/src/test/java/org/odk/collect/android/http/OpenRosaServerClientFactoryTest.java
  collect_app/src/test/java/org/odk/collect/android/http/stub/StubOpenRosaHttpInterface.java
Labels: behavior verified

#3309 Fixed null provider in Mapbox
  collect_app/src/main/java/org/odk/collect/android/geo/MapboxMapFragment.java
Labels: behavior verified

#3311 Fix basemap attribution text disappearing
  collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java
Labels: behavior verified

#3272 Bypass caching of internal secondary instances for performance
  collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceGoogleSheetsUploader.java
Labels: behavior verified
