Repository getodk/collect, pull requests merged in 2019-02, with the labels that each got.

#2800 Removed unused widgets
  collect_app/src/main/java/org/odk/collect/android/tasks/MediaLoadingTask.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AlignedImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWebViewWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/main/res/values-cs/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-hi/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-ln/strings.xml
  collect_app/src/main/res/values-my/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-sl/strings.xml
  collect_app/src/main/res/values-sw/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values-ur/strings.xml
  collect_app/src/main/res/values/strings.xml
  collect_app/src/test/java/org/odk/collect/android/widgets/AlignedImageWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ImageWebViewWidgetTest.java
Labels: behavior verified

#2802 Removed setting textColor to primaryTextColor. Fix #2801
  collect_app/src/main/res/values/theme.xml
Labels: behavior verified

#2817 Moves media player related functionalities to Media Widget class
  collect_app/src/main/java/org/odk/collect/android/preferences/GuidanceHint.java
  collect_app/src/main/java/org/odk/collect/android/views/MediaLayout.java
  collect_app/src/main/java/org/odk/collect/android/views/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GridMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GridWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/MediaWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectWidget.java
  collect_app/src/test/java/org/odk/collect/android/views/MediaLayoutTest.java
Labels: behavior verified

#2860 Fixed the logic with icons next to options.
  collect_app/src/main/java/org/odk/collect/android/activities/DrawActivity.java
Labels: behavior verified

#2833 Keyboard appears and full submission name is not visible if submission name is not editable
  collect_app/src/main/res/layout/form_entry_end.xml
Labels: behavior verified

#2875 Include “Number Picker” in transifex
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/NumberPickerDialog.java
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#2848 Fixed the problem with finding an instance file during sending a form to GoogleSheets
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceGoogleSheetsUploader.java
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceUploader.java
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#2849 Issue #620 pr2 add okhttp3
  build.gradle
  collect_app/build.gradle
  collect_app/src/main/java/org/odk/collect/android/http/CollectServerClient.java
  collect_app/src/main/java/org/odk/collect/android/http/HttpClientConnection.java
  collect_app/src/main/java/org/odk/collect/android/http/HttpCredentials.java
  collect_app/src/main/java/org/odk/collect/android/http/HttpPostResult.java
  collect_app/src/main/java/org/odk/collect/android/http/OkHttpConnection.java
  collect_app/src/main/java/org/odk/collect/android/http/OpenRosaHttpInterface.java
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ResponseMessageParser.java
  collect_app/src/test/java/org/odk/collect/android/http/mock/MockHttpClientConnection.java
  collect_app/src/test/java/org/odk/collect/android/http/mock/MockHttpClientConnectionError.java
Labels: needs testing

#2825 Nicer looking, more consistent form/instance lists
  collect_app/src/main/java/org/odk/collect/android/activities/AppListActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FileManagerTabs.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormChooserList.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java
  collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java
  collect_app/src/main/java/org/odk/collect/android/adapters/FormDownloadListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/adapters/InstanceListCursorAdapter.java
  collect_app/src/main/java/org/odk/collect/android/adapters/InstanceUploaderAdapter.java
  collect_app/src/main/java/org/odk/collect/android/adapters/ViewSentListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/fragments/AppListFragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/DataManagerList.java
  collect_app/src/main/java/org/odk/collect/android/fragments/FileManagerFragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/FormManagerList.java
  collect_app/src/main/java/org/odk/collect/android/utilities/VersionHidingCursorAdapter.java
  collect_app/src/main/java/org/odk/collect/android/views/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/views/TwoItemMultipleChoiceView.java
  collect_app/src/main/res/drawable/check.xml
  collect_app/src/main/res/drawable/close_box_outline.xml
  collect_app/src/main/res/drawable/exclamation.xml
  collect_app/src/main/res/drawable/form_state_blank.xml
  collect_app/src/main/res/drawable/form_state_finalized.xml
  collect_app/src/main/res/drawable/form_state_saved.xml
  collect_app/src/main/res/drawable/form_state_sending.xml
  collect_app/src/main/res/drawable/form_state_submission_failed.xml
  collect_app/src/main/res/drawable/form_state_submitted.xml
  collect_app/src/main/res/drawable/ic_cancel.xml
  collect_app/src/main/res/drawable/ic_visibility_off.xml
  collect_app/src/main/res/drawable/instance_list_icon_background.xml
  collect_app/src/main/res/drawable/list_item_divider.xml
  collect_app/src/main/res/drawable/message_text_outline.xml
  collect_app/src/main/res/drawable/pencil.xml
  collect_app/src/main/res/layout/chooser_list_layout.xml
  collect_app/src/main/res/layout/drive_layout.xml
  collect_app/src/main/res/layout/file_manager_layout.xml
  collect_app/src/main/res/layout/file_manager_list.xml
  collect_app/src/main/res/layout/file_manager_tabs.xml
  collect_app/src/main/res/layout/form_chooser_list.xml
  collect_app/src/main/res/layout/form_chooser_list_item.xml
  collect_app/src/main/res/layout/form_chooser_list_item_icon.xml
  collect_app/src/main/res/layout/form_chooser_list_item_multiple_choice.xml
  collect_app/src/main/res/layout/form_chooser_list_item_text.xml
  collect_app/src/main/res/layout/form_download_list.xml
  collect_app/src/main/res/layout/google_drive_list.xml
  collect_app/src/main/res/layout/instance_upload_list_item.xml
  collect_app/src/main/res/layout/media_layout.xml
  collect_app/src/main/res/layout/remote_file_manage_list.xml
  collect_app/src/main/res/layout/reset_dialog_layout.xml
  collect_app/src/main/res/layout/tab_layout.xml
  collect_app/src/main/res/layout/two_item.xml
  collect_app/src/main/res/layout/two_item_image.xml
  collect_app/src/main/res/layout/two_item_multiple_choice.xml
  collect_app/src/main/res/values/attrs.xml
  collect_app/src/main/res/values/colors.xml
  collect_app/src/main/res/values/dimens.xml
  collect_app/src/main/res/values/style.xml
  collect_app/src/main/res/values/theme.xml
Labels: behavior verified

#2892 Disable SMS feature
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java
  collect_app/src/main/res/values/strings.xml
  config/lint.xml
Labels: behavior verified

#2894 Fixed text color in settings
  collect_app/src/main/java/org/odk/collect/android/utilities/PermissionUtils.java
  collect_app/src/main/res/values/theme.xml
Labels: behavior verified

#2897 Fixed sending forms with repeat groups to Google Sheets
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceGoogleSheetsUploader.java
Labels: behavior verified

#2891 GeoTrace: Add a selectable GPS accuracy threshold.
  collect_app/src/main/java/org/odk/collect/android/activities/BaseGeoMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceActivity.java
  collect_app/src/main/java/org/odk/collect/android/map/GoogleMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/map/MapFragment.java
  collect_app/src/main/java/org/odk/collect/android/map/OsmMapFragment.java
  collect_app/src/main/res/drawable/ic_backspace.xml
  collect_app/src/main/res/layout/geoshape_layout.xml
  collect_app/src/main/res/layout/geotrace_dialog.xml
  collect_app/src/main/res/layout/geotrace_layout.xml
  collect_app/src/main/res/values-am/strings.xml
  collect_app/src/main/res/values-ar/strings.xml
  collect_app/src/main/res/values-bn/strings.xml
  collect_app/src/main/res/values-ca/strings.xml
  collect_app/src/main/res/values-cs/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-et/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-hi/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-it/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-mr/strings.xml
  collect_app/src/main/res/values-ne-rNP/strings.xml
  collect_app/src/main/res/values-nl/strings.xml
  collect_app/src/main/res/values-pl/strings.xml
  collect_app/src/main/res/values-ps/strings.xml
  collect_app/src/main/res/values-pt/strings.xml
  collect_app/src/main/res/values-ro/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-sl/strings.xml
  collect_app/src/main/res/values-sq/strings.xml
  collect_app/src/main/res/values-sv-rSE/strings.xml
  collect_app/src/main/res/values-sw/strings.xml
  collect_app/src/main/res/values-th-rTH/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values-ur/strings.xml
  collect_app/src/main/res/values/arrays.xml
  collect_app/src/main/res/values/colors.xml
  collect_app/src/main/res/values/strings.xml
Labels: high priority, needs testing

#2902 Use our themes to fix the default tintMode to SRC_IN.
  collect_app/src/main/res/values/theme.xml
Labels: high priority, needs testing

#2904 Remove unnecessary padding below GeoTrace buttons.
  collect_app/src/main/res/layout/geotrace_layout.xml
Labels: behavior verified

#2910 GeoShape: Consolidate UI updates into updateUi().
  collect_app/src/main/java/org/odk/collect/android/activities/GeoShapeActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoTraceActivity.java
  collect_app/src/test/java/org/odk/collect/android/location/activities/GeoShapeActivityTest.java
Labels: behavior verified

#2907 Fixed validating Google Accounts
  collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java
Labels: behavior verified
