Repository getodk/collect, pull requests merged in 2019-04, with the labels that each got.

#2970 Clear the list if reading files canceled
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java
Labels: behavior verified

#2983 Fixed RankWidget
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/RankingWidgetDialog.java
Labels: behavior verified

#2982 Prevent NullPointerExceptions when the activity is null
  collect_app/src/main/java/org/odk/collect/android/map/GoogleMapFragment.java
Labels: behavior verified, high priority

#2985 Fixed OutOfMemoryError during importing settings
  collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java
Labels: behavior verified

#2994 Allow clicking on the marker
  collect_app/src/main/java/org/odk/collect/android/map/GoogleMapFragment.java
Labels: behavior verified

#2990 Don't display not relevant groups and groups that don't contain any relevant questions in hierarchy
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/logic/FormController.java
Labels: behavior verified

#2734 Add tests to verify launching intents in Widgets
  collect_app/src/main/java/org/odk/collect/android/utilities/PermissionUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/OSMWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
  collect_app/src/test/java/org/odk/collect/android/ShadowPlayServicesUtil.java
  collect_app/src/test/java/org/odk/collect/android/fakes/FakePermissionUtils.java
  collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/AudioWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/BarcodeWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/BearingWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/DrawWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/GeoPointWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/GeoShapeWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/GeoTraceWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ImageWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/OSMWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/SignatureWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/VideoWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/BinaryWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/ButtonWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/QuestionWidgetTest.java
Labels: behavior verified

#2999 Avoid NullPointerException in findExistingOrCreateNewUri() method
  collect_app/src/main/java/org/odk/collect/android/utilities/FormDownloader.java
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#2878 Refactor GoogleAccountsManager
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceGoogleSheetsUploaderTask.java
  collect_app/src/main/java/org/odk/collect/android/upload/AutoSendWorker.java
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceGoogleSheetsUploader.java
  collect_app/src/main/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManager.java
  collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/GoogleAccountsManagerTest.java
  collect_app/src/test/java/org/odk/collect/android/utilities/gdrive/TestGoogleAccountSelectionListener.java
Labels: behavior verified

#2981 New appearance of the button holder (form navigation)
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/res/drawable/ic_navigate_back.xml
  collect_app/src/main/res/drawable/ic_navigate_back_disabled.xml
  collect_app/src/main/res/drawable/ic_navigate_back_wrapped.xml
  collect_app/src/main/res/drawable/ic_navigate_forward.xml
  collect_app/src/main/res/drawable/ic_navigate_forward_disabled.xml
  collect_app/src/main/res/drawable/ic_navigate_forward_wrapped.xml
  collect_app/src/main/res/drawable/navigate_back_button.xml
  collect_app/src/main/res/drawable/navigate_forward_button.xml
  collect_app/src/main/res/drawable/shadow_up.xml
  collect_app/src/main/res/layout/form_entry.xml
  collect_app/src/main/res/values/strings.xml
Labels: behavior verified

#3010 Catch IllegalArgumentException in FormsProvider
  collect_app/src/main/java/org/odk/collect/android/provider/FormsProvider.java
Labels: behavior verified

#3031 Fixed icons in sorting dialog
  collect_app/src/main/java/org/odk/collect/android/activities/AppListActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormChooserList.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadList.java
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderListActivity.java
  collect_app/src/main/java/org/odk/collect/android/adapters/SortDialogAdapter.java
  collect_app/src/main/java/org/odk/collect/android/fragments/AppListFragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/FileManagerFragment.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationConstants.java
Labels: behavior verified

#3032 Don't allow opeaning more than one dialog in widgets if there are many widgets on one page
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
Labels: behavior verified

#3038 Remove check for Aggregate 0.9 legacy servers when adding media attachments
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java
Labels: high priority, needs testing

#3017 Fixed the case when last group in nested repeat group is removed
  collect_app/src/main/java/org/odk/collect/android/logic/FormController.java
Labels: behavior verified
