Repository getodk/collect, pull requests merged in 2019-12, with the labels that each got.

#3478 Fixed checkboxes in Reset Settings dialog
  collect_app/src/main/java/org/odk/collect/android/preferences/ResetDialogPreference.java
  collect_app/src/main/res/layout/reset_dialog_layout.xml
Labels: behavior verified

#3482 Fixed crash in Mapbox
  collect_app/src/main/java/org/odk/collect/android/geo/MapboxMapFragment.java
Labels: behavior verified

#3462 Disable automatic formatting only for questions that are formatting prone
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceGoogleSheetsUploader.java
  collect_app/src/test/java/org/odk/collect/android/utilities/InstanceGoogleSheetsUploaderTest.java
Labels: behavior verified

#3474 Fixed distorted buttons
  collect_app/src/main/res/drawable-v21/inset_check_box.xml
  collect_app/src/main/res/drawable-v21/inset_radio_button.xml
  collect_app/src/main/res/layout-v21/select_multi_item.xml
  collect_app/src/main/res/layout-v21/select_one_item.xml
  collect_app/src/main/res/layout/select_multi_item.xml
  collect_app/src/main/res/layout/select_one_item.xml
Labels: behavior verified

#3485 Clear credentials when settings are being reset
  collect_app/src/androidTest/java/org/odk/collect/android/ResetAppStateTest.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ResetUtility.java
  collect_app/src/main/java/org/odk/collect/android/utilities/WebCredentialsUtils.java
Labels: behavior verified

#3467 Avoid starting asynctask responsible for uploading forms to GS twice
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java
Labels: behavior verified

#3464 Add margins back into Text Widgets
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectMultipleAutocompleteWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectOneAutocompleteWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectTextWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/StringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/test/java/org/odk/collect/android/widgets/SelectOneAutocompleteWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/SelectOneSearchWidgetTest.java
Labels: behavior verified

#3492 Reduce select and question header padding
  collect_app/src/main/java/org/odk/collect/android/views/ODKView.java
  collect_app/src/main/res/layout/audio_video_image_text_label.xml
  collect_app/src/main/res/layout/question_long_text.xml
  collect_app/src/main/res/layout/quick_select_layout.xml
  collect_app/src/main/res/layout/select_multi_item.xml
  collect_app/src/main/res/layout/select_one_item.xml
Labels: behavior verified

#3505 Replace margin with padding to prevent RTL bug in Android 7
  collect_app/src/main/res/layout/help_text_layout.xml
Labels: behavior verified, high priority

#3512 Fixed audio_video_image_text_label layout
  collect_app/src/main/java/org/odk/collect/android/formentry/questions/AudioVideoImageTextLabel.java
  collect_app/src/main/res/layout/audio_video_image_text_label.xml
Labels: behavior verified, high priority

#3511 Clear geometry after encryption
  collect_app/src/main/java/org/odk/collect/android/instances/DatabaseInstancesRepository.java
  collect_app/src/main/java/org/odk/collect/android/instances/InstancesRepository.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceSyncTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/SaveToDiskTask.java
  collect_app/src/test/java/org/odk/collect/android/instances/TestInstancesRepository.java
Labels: behavior verified, high priority

#3516 Fixed paddings for select widgets with compact and columns no-buttons appearances
  collect_app/src/main/java/org/odk/collect/android/adapters/AbstractSelectListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BaseGridWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GridMultiWidget.java
Labels: behavior verified

#3520 Make sure save requests are cleared once they're dealt with
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/audit/ChangesReasonPromptViewModel.java
  collect_app/src/test/java/org/odk/collect/android/formentry/audit/ChangesReasonPromptViewModelTest.java
Labels: behavior verified, high priority

#3527 Fixed clicking on marker
  collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java
Labels: behavior verified, high priority

#3523 Set up the reference manager when doing form discovery parse
  collect_app/src/main/java/org/odk/collect/android/tasks/DiskSyncTask.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormDownloader.java
Labels: behavior verified, high priority

#3531 Fixed readOnly in select widgets
  collect_app/src/main/java/org/odk/collect/android/adapters/AbstractSelectListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/widgets/LikertWidget.java
Labels: high priority

#3537 On form download, only set up the reference manager if the form has media
  collect_app/src/main/java/org/odk/collect/android/utilities/FormDownloader.java
  collect_app/src/test/java/org/odk/collect/android/utilities/FormDownloaderTest.java
Labels: behavior verified, high priority

#3503 Don't allow selecting basemap that is unavailable
  collect_app/src/main/java/org/odk/collect/android/preferences/MapsPreferences.java
Labels: behavior verified, future release

#3487 Support items from search function in RankWidget
  collect_app/src/androidTest/assets/forms/ranking_widget.xml
  collect_app/src/androidTest/java/org/odk/collect/android/espressoutils/pages/FormEntryPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/espressoutils/pages/Page.java
  collect_app/src/androidTest/java/org/odk/collect/android/formentry/RankingWidgetWIthCSVTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/adapters/RankingListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/external/ExternalAnswerResolver.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/RankingWidgetDialog.java
  collect_app/src/main/java/org/odk/collect/android/widgets/RankingWidget.java
Labels: behavior verified, future release
