Repository getodk/collect, pull requests merged in 2020-03, with the labels that each got.

#3658 Fixed ImageView in audio_video_image_text_label layout
  collect_app/src/main/res/layout/audio_video_image_text_label.xml
Labels: behavior verified

#3637 Scan Qr code main menu button
  collect_app/src/androidTest/java/org/odk/collect/android/settings/MainMenuTest.java
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/ScanQRCodeActivity.java
  collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/AdminPasswordDialog.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/main/java/org/odk/collect/android/preferences/AdminKeys.java
  collect_app/src/main/res/menu/main_menu.xml
  collect_app/src/main/res/values-ar/strings.xml
  collect_app/src/main/res/values-ca/strings.xml
  collect_app/src/main/res/values-cs/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-fa/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-hi/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-it/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-mr/strings.xml
  collect_app/src/main/res/values-ne-rNP/strings.xml
  collect_app/src/main/res/values-nl/strings.xml
  collect_app/src/main/res/values-pl/strings.xml
  collect_app/src/main/res/values-pt/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-sq/strings.xml
  collect_app/src/main/res/values-sr/strings.xml
  collect_app/src/main/res/values-sv-rSE/strings.xml
  collect_app/src/main/res/values-sw/strings.xml
  collect_app/src/main/res/values-te/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values-ur/strings.xml
  collect_app/src/main/res/values/strings.xml
  collect_app/src/main/res/xml/admin_preferences.xml
  collect_app/src/main/res/xml/main_menu_access_preferences.xml
  collect_app/src/test/java/org/odk/collect/android/activities/MainActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/activities/MainMenuActivityTest.java
Labels: behavior verified

#3667 Fixed bug with radioButtons/CheckBoxes on Android 6
  collect_app/src/main/res/drawable/inset_check_box.xml
  collect_app/src/main/res/drawable/inset_radio_button.xml
  collect_app/src/main/res/layout/select_multi_item.xml
  collect_app/src/main/res/layout/select_one_item.xml
Labels: behavior verified

#3670 Open user-facing post with scoped storage migration details in browser
  collect_app/src/androidTest/java/org/odk/collect/android/storage/StorageMigrationTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/StorageMigrationDialogPage.java
  collect_app/src/main/java/org/odk/collect/android/storage/migration/StorageMigrationDialog.java
Labels: behavior verified

#3645 Define new Widget "framework"
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/TriggerWidget.java
  collect_app/src/main/res/layout/trigger_widget_answer.xml
  collect_app/src/test/java/org/odk/collect/android/support/MockFormEntryPromptBuilder.java
  collect_app/src/test/java/org/odk/collect/android/widgets/TriggerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/support/QuestionWidgetHelpers.java
  docs/CONTRIBUTING.md
  docs/STATE.md
  docs/WIDGETS.md
Labels: needs testing

#3671 Fixed RankingWidget layout
  collect_app/src/main/java/org/odk/collect/android/widgets/RankingWidget.java
Labels: behavior verified

#3652 Fix the form map crash by waiting until the map fragment is initialized to save it in the map field
  collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPolyActivity.java
  collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/geo/MapProvider.java
  collect_app/src/main/java/org/odk/collect/android/geo/MapboxMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/test/java/org/odk/collect/android/activities/FormMapActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/geo/TestMapFragment.java
  docs/CODE-GUIDELINES.md
Labels: behavior verified

#3666 Use an ingestion timestamp to detect whether the search/pulldata handler should re-process new data file
  collect_app/src/androidTest/assets/forms/simple-search-external-csv.xml
  collect_app/src/androidTest/assets/media/simple-search-external-csv-fruits.csv
  collect_app/src/androidTest/java/org/odk/collect/android/tasks/FormLoaderTaskTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/test/FormLoadingUtils.java
  collect_app/src/androidTest/java/org/odk/collect/android/utilities/CustomSQLiteQueryExecutionTest.java
  collect_app/src/main/java/org/odk/collect/android/external/ExternalDataReaderImpl.java
  collect_app/src/main/java/org/odk/collect/android/external/ExternalDataUtil.java
  collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java
  collect_app/src/main/java/org/odk/collect/android/utilities/CustomSQLiteQueryBuilder.java
  collect_app/src/main/java/org/odk/collect/android/utilities/CustomSQLiteQueryExecutor.java
  collect_app/src/main/java/org/odk/collect/android/utilities/SQLiteUtils.java
  collect_app/src/test/java/org/odk/collect/android/external/ExternalDataReaderTest.java
  collect_app/src/test/java/org/odk/collect/android/utilities/CustomSQLiteQueryBuilderTestCase.java
  collect_app/src/test/java/org/odk/collect/android/utilities/SQLiteUtilsTest.java
  collect_app/src/test/resources/forms/simple-search-external-csv.xml
  collect_app/src/test/resources/media/simple-search-external-csv-fruits.csv
Labels: behavior verified

#3681 Updated mapbox version to fix the crash
  collect_app/build.gradle
Labels: behavior verified

#3688 Avoid updating instance lastStatusChaneDate during migration
  collect_app/src/main/java/org/odk/collect/android/storage/migration/StorageMigrator.java
Labels: behavior verified

#3697 Fixed readonly option in SelectImageMapWidget
  collect_app/src/main/java/org/odk/collect/android/views/CustomWebView.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SelectImageMapWidget.java
  collect_app/src/test/java/org/odk/collect/android/widgets/SelectImageMapWidgetTest.java
Labels: behavior verified

#3698 Rebuild the mappable instance list when the map view is shown to reflect deleted geopoint
  collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormMapViewModel.java
  collect_app/src/test/java/org/odk/collect/android/activities/FormMapViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/instances/TestInstancesRepository.java
Labels: behavior verified

#3695 Use md5 hash to detect changes in search()/pulldata files
  collect_app/src/androidTest/java/org/odk/collect/android/tasks/FormLoaderTaskTest.java
  collect_app/src/main/java/org/odk/collect/android/external/ExternalDataUtil.java
  collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java
  collect_app/src/test/java/org/odk/collect/android/external/ExternalDataReaderTest.java
Labels: behavior verified

#3690 Fixed Save button in Reason for changes page does not work after rotating device orientation
  collect_app/src/androidTest/java/org/odk/collect/android/formentry/audit/TrackChangesReasonTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java
  collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java
Labels: behavior verified

#3702 Fixed canceling form loading
  collect_app/src/main/java/org/odk/collect/android/formentry/FormLoadingDialogFragment.java
  collect_app/src/test/java/org/odk/collect/android/formentry/FormLoadingDialogFragmentTest.java
Labels: behavior verified

#3720 Make sure dialog fragments aren't shown for destroyed Activity
  collect_app/src/main/java/org/odk/collect/android/utilities/DialogUtils.java
  collect_app/src/test/java/org/odk/collect/android/utilities/DialogUtilsTest.java
Labels: behavior verified, high priority

#3717 Fixed canceling form saving
  collect_app/src/main/java/org/odk/collect/android/formentry/SaveFormProgressDialogFragment.java
  collect_app/src/test/java/org/odk/collect/android/formentry/SaveFormProgressDialogFragmentTest.java
Labels: behavior verified

#3721 Factored out NetworkStateProvider class
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleDriveActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderListActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/java/org/odk/collect/android/adapters/FormDownloadListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
  collect_app/src/main/java/org/odk/collect/android/fragments/MediaLoadingFragment.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/network/ConnectivityProvider.java
  collect_app/src/main/java/org/odk/collect/android/network/NetworkStateProvider.java
  collect_app/src/main/java/org/odk/collect/android/tasks/MediaLoadingTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/ServerPollingJob.java
  collect_app/src/main/java/org/odk/collect/android/upload/AutoSendWorker.java
  collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/PermissionUtils.java
Labels: behavior verified

#3704 Refactored the way we deal with buttons visiblility in the main menu
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/MainMenuViewModel.java
  collect_app/src/test/java/org/odk/collect/android/activities/MainMenuButtonsVisibilityTest.java
Labels: behavior verified

#3699 Factored out MultiClickGuard class
  collect_app/src/main/java/org/odk/collect/android/activities/AboutActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormChooserListActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
  collect_app/src/main/java/org/odk/collect/android/formentry/questions/WidgetViewUtils.java
  collect_app/src/main/java/org/odk/collect/android/fragments/Camera2VideoFragment.java
  collect_app/src/main/java/org/odk/collect/android/storage/migration/StorageMigrationDialog.java
  collect_app/src/main/java/org/odk/collect/android/utilities/MultiClickGuard.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java
Labels: behavior verified

#3725 Added margin in Label Widget
  collect_app/src/main/res/layout/label_widget.xml
Labels: behavior verified

#3680 Use one app bar layout across the app
  collect_app/src/main/java/org/odk/collect/android/preferences/FormMetadataPreferencesActivity.java
  collect_app/src/main/res/drawable/action_bar_shadow.xml
  collect_app/src/main/res/layout/about_layout.xml
  collect_app/src/main/res/layout/activity_preferences_layout.xml
  collect_app/src/main/res/layout/androidx_preferences_activity.xml
  collect_app/src/main/res/layout/app_bar_layout.xml
  collect_app/src/main/res/layout/file_manager_tabs.xml
  collect_app/src/main/res/layout/form_chooser_list.xml
  collect_app/src/main/res/layout/form_download_list.xml
  collect_app/src/main/res/layout/form_entry.xml
  collect_app/src/main/res/layout/google_drive_list.xml
  collect_app/src/main/res/layout/hierarchy_layout.xml
  collect_app/src/main/res/layout/instance_uploader_list.xml
  collect_app/src/main/res/layout/main_menu.xml
  collect_app/src/main/res/layout/toolbar.xml
  collect_app/src/main/res/layout/toolbar_action_bar_shadow.xml
  collect_app/src/main/res/layout/toolbar_without_progressbar.xml
Labels: behavior verified

#3735 Fixed downloading forms with media files
  collect_app/src/main/java/org/odk/collect/android/utilities/FormDownloader.java
Labels: behavior verified

#3457 Upgrade to mapbox-android-plugin-annotation-v8:0.7.0.
  collect_app/build.gradle
  collect_app/src/main/java/org/odk/collect/android/geo/MapboxMapFragment.java
Labels: behavior verified

#3746 Fixed layers directory path
  collect_app/src/main/java/org/odk/collect/android/preferences/MapsPreferences.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
  collect_app/src/test/java/org/odk/collect/android/utilities/FileUtilsTest.java
Labels: behavior verified

#3728 Update dependencies
  build.gradle
  collect_app/build.gradle
  collect_app/libs/nbi-stubs-1.0.0.aar
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
  collect_app/src/main/java/org/odk/collect/android/application/TestCollect.java
  collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/geo/OsmMBTileModuleProvider.java
  collect_app/src/main/java/org/odk/collect/android/geo/OsmMBTileSource.java
  collect_app/src/main/java/org/odk/collect/android/geo/WebMapService.java
  config/jacoco.gradle
  config/pmd-ruleset.xml
  config/quality.gradle
  gradle/wrapper/gradle-wrapper.properties
  nbi-stubs/.gitignore
  nbi-stubs/README.md
  nbi-stubs/build.gradle
  nbi-stubs/consumer-rules.pro
  nbi-stubs/src/main/AndroidManifest.xml
  nbi-stubs/src/main/jniLibs/arm64-v8a/libstub.so
  nbi-stubs/src/main/jniLibs/armeabi-v7a/libstub.so
  nbi-stubs/src/main/jniLibs/armeabi/libstub.so
  nbi-stubs/src/main/jniLibs/x86/libstub.so
  nbi-stubs/src/main/jniLibs/x86_64/libstub.so
  settings.gradle
Labels: behavior verified
