Repository getodk/collect, pull requests merged in 2020-12, with the labels that each got.

#4222 Add AMR recordings
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recorder/MediaRecorderRecorder.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recorder/MediaRecorderWrapper.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recorder/Recorder.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recording/AudioRecorderViewModel.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recording/AudioRecorderViewModelFactory.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recording/internal/AudioRecorderService.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recording/internal/ForegroundServiceAudioRecorderViewModel.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/testsupport/StubAudioRecorderViewModel.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recorder/MediaRecorderRecorderTest.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recording/AudioRecorderViewModelTest.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recording/internal/AudioRecorderServiceTest.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recording/internal/ForegroundServiceAudioRecorderViewModelTest.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/support/FakeRecorder.kt
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/InternalRecordingRequester.java
  collect_app/src/test/java/org/odk/collect/android/widgets/utilities/InternalRecordingRequesterTest.java
Labels: behavior verified

#4243 Explicitly address repeat in field-list case
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/audit/AuditUtils.java
  collect_app/src/main/java/org/odk/collect/android/forms/FormDesignException.java
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/FormController.java
  collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java
Labels: behavior verified

#4225 Ensure all download errors result in a dialog
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java
Labels: behavior verified

#4242 Fixed: Minimal appearance doesn't work with "fast external itemsets"
  collect_app/src/androidTest/assets/forms/selectOneExternal.xml
  collect_app/src/androidTest/assets/media/selectOneExternal-media/itemsets.csv
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FastExternalItemsetTest.java
  collect_app/src/main/java/org/odk/collect/android/dao/ItemsetDao.java
  collect_app/src/main/java/org/odk/collect/android/fastexternalitemset/ItemsetDao.java
  collect_app/src/main/java/org/odk/collect/android/fastexternalitemset/ItemsetDbAdapter.java
  collect_app/src/main/java/org/odk/collect/android/fastexternalitemset/XPathParseTool.java
  collect_app/src/main/java/org/odk/collect/android/formentry/questions/ItemsetQuestionDetails.java
  collect_app/src/main/java/org/odk/collect/android/itemsets/Itemset.java
  collect_app/src/main/java/org/odk/collect/android/provider/FormsProvider.java
  collect_app/src/main/java/org/odk/collect/android/storage/migration/StorageEraser.java
  collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationResetter.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormEntryPromptUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/SelectOneWidgetUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/ItemsWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/ListWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneImageMapWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneMinimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneWidget.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/QuestionWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/ItemsetWidgetTest.java
Labels: behavior verified

#4252 Fixed closing cursor
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceSyncTask.java
Labels: behavior verified

#4244 Allow disabling external recording feature
  collect_app/src/main/java/org/odk/collect/android/preferences/AdminKeys.java
  collect_app/src/main/res/xml/user_settings_access_preferences.xml
  collect_app/src/test/java/org/odk/collect/android/preferences/FormManagementPreferencesTest.java
  collect_app/src/test/java/org/odk/collect/android/preferences/GeneralPreferencesFragmentTest.java
  collect_app/src/test/java/org/odk/collect/android/preferences/UserInterfacePreferencesFragmentTest.java
Labels: behavior verified

#4228 Fixed: Read-only binary questions have no spacing below the question text
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/IntentGroupTest.java
  collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/LabelWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/ListMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/ListWidget.java
  collect_app/src/main/res/layout/label_widget.xml
  collect_app/src/main/res/layout/question_widget.xml
  collect_app/src/test/java/org/odk/collect/android/widgets/base/QuestionWidgetTest.java
Labels: behavior verified

#4249 Unsaved recent files should be deleted if a user ignores changes
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.java
  collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java
Labels: behavior verified

#4277 Fixed: Collect crashes when user tries to download form via CollectTester if URL settings are not set
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/tasks/DownloadFormListTaskTest.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormsDetailsFetcher.java
  collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java
Labels: behavior verified

#4274 Fixed creating multiple files for recording selfie videos
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FieldListUpdateTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/DrawActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/fragments/Camera2Fragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/Camera2VideoFragment.java
  collect_app/src/main/java/org/odk/collect/android/storage/StoragePathProvider.java
  collect_app/src/main/java/org/odk/collect/android/utilities/CameraUtils.java
  collect_app/src/main/java/org/odk/collect/android/views/DrawView.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
Labels: behavior verified

#4257 Fixed: User is able to open two different views from the main screen
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/res/layout/main_menu.xml
  collect_app/src/test/java/org/odk/collect/android/activities/MainActivityTest.java
Labels: behavior verified

#4275 Add error handling for audio recording
  audiorecorder/build.gradle
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/DaggerSetup.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/mediarecorder/MediaRecorderRecordingResource.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recorder/Recorder.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recorder/RecordingResource.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recorder/RecordingResourceRecorder.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recording/AudioRecorderViewModel.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recording/internal/AudioRecorderService.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recording/internal/RecordingRepository.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/testsupport/StubAudioRecorderViewModel.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recorder/RecordingResourceRecorderTest.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recording/AudioRecorderViewModelTest.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recording/internal/AudioRecorderServiceTest.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recording/internal/ForegroundServiceAudioRecorderViewModelTest.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/support/FakeRecorder.kt
  build.gradle
  collect_app/build.gradle
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/AudioRecordingTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/audio/AudioRecordingControllerFragment.java
  collect_app/src/main/java/org/odk/collect/android/formentry/QuitFormDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/SaveAnswerFileErrorDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/SaveFormProgressDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/utilities/QuestionMediaManager.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/ExternalAppRecordingRequester.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/InternalRecordingRequester.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/RecordingRequester.java
  collect_app/src/main/java/org/odk/collect/utilities/Result.java
  collect_app/src/test/java/org/odk/collect/android/formentry/QuitFormDialogFragmentTest.java
  collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/support/RobolectricHelpers.java
  collect_app/src/test/java/org/odk/collect/android/widgets/AudioWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/support/FakeQuestionMediaManager.java
  collect_app/src/test/java/org/odk/collect/android/widgets/utilities/ExternalAppRecordingRequesterTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/utilities/InternalRecordingRequesterTest.java
  strings/src/main/res/values/strings.xml
Labels: needs testing

#4281 Always allow download of form with same formid/version
  collect_app/src/main/java/org/odk/collect/android/backgroundwork/AutoUpdateTaskSpec.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/FormDownloadException.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/FormDownloadExceptionMapper.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDownloader.java
  collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormsTask.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/FormDownloadExceptionMapperTest.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormDownloaderTest.java
  docs/STATE.md
Labels: behavior verified

#4289 Make sure screen reloads when preferences are changed
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryMenuDelegate.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationConstants.java
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryMenuDelegateTest.java
Labels: behavior verified

#4291 Fix crash when stop/pause pressed at the same time while recording
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recording/internal/AudioRecorderService.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recording/internal/AudioRecorderServiceTest.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/support/FakeRecorder.kt
  collect_app/src/test/java/org/odk/collect/android/activities/MainActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/application/RobolectricApplication.java
Labels: behavior verified

#4296 Fixed bugs in SelectMultiMinimalWidget
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectMultiMinimalWidget.java
Labels: behavior verified

#4304 Downgrade mapbox-android-plugin-annotation
  collect_app/build.gradle
  collect_app/src/main/java/org/odk/collect/android/geo/MapboxMapFragment.java
Labels: behavior verified

#4301 Show error when starting recording while mic in use
  .circleci/config.yml
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/mediarecorder/MediaRecorderRecordingResource.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recorder/Recorder.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recorder/RecordingResource.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recorder/RecordingResourceRecorder.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recording/AudioRecorderViewModel.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recording/internal/AudioRecorderService.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recording/internal/RecordingRepository.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/testsupport/StubAudioRecorderViewModel.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recorder/RecordingResourceRecorderTest.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recording/AudioRecorderViewModelTest.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recording/internal/AudioRecorderServiceTest.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recording/internal/ForegroundServiceAudioRecorderViewModelTest.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/support/FakeRecorder.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/AudioRecordingTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java
  collect_app/src/main/java/org/odk/collect/android/audio/AudioRecordingControllerFragment.java
  collect_app/src/main/java/org/odk/collect/android/audio/AudioRecordingErrorDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/InternalRecordingRequester.java
  collect_app/src/test/java/org/odk/collect/android/audio/AudioRecordingControllerFragmentTest.java
  collect_app/src/test/java/org/odk/collect/android/audio/AudioRecordingErrorDialogFragmentTest.java
  collect_app/src/test/java/org/odk/collect/android/support/RobolectricHelpers.java
  strings/src/main/res/values/strings.xml
Labels: behavior verified

#4316 Make sure external recording is blocked when internal recording in progress
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/ExternalAppRecordingRequester.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/InternalRecordingRequester.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/RecordingRequester.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/RecordingRequesterFactory.java
  collect_app/src/test/java/org/odk/collect/android/widgets/utilities/ExternalAppRecordingRequesterTest.java
Labels: behavior verified

#4318 Fixed generating QR codes
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ConfigureWithQRCodeTest.java
  collect_app/src/main/java/org/odk/collect/android/configure/qr/CachingQRCodeGenerator.java
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeGenerator.java
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeMenuDelegate.java
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeTabsActivity.java
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeViewModel.java
  collect_app/src/main/java/org/odk/collect/android/configure/qr/ShowQRCodeFragment.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/preferences/JsonPreferencesGenerator.java
  collect_app/src/main/java/org/odk/collect/android/utilities/SharedPreferencesUtils.java
  collect_app/src/test/java/org/odk/collect/android/configure/qr/QRCodeMenuDelegateTest.java
  collect_app/src/test/java/org/odk/collect/android/configure/qr/QRCodeViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/preferences/JsonPreferencesGeneratorTest.java
Labels: behavior verified

#4308 Do not show keyboard for readonly select widgets with autocomplete appearance
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/utilities/SoftKeyboardController.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/StringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/BaseSelectListWidget.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectMultiWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectOneWidgetTest.java
Labels: behavior verified

#4328 Temporarily pass in formController to navigation methods
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
Labels: high priority

#4325 Fix crash when media file download fails
  collect_app/src/main/java/org/odk/collect/android/forms/FormSource.java
  collect_app/src/main/java/org/odk/collect/android/openrosa/OpenRosaFormSource.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormDownloaderTest.java
  collect_app/src/test/java/org/odk/collect/android/openrosa/api/OpenRosaFormSourceTest.java
Labels: high priority
