Repository getodk/collect, pull requests merged in 2020-10, with the labels that each got.

#4067 Fixed getFileExtensionFromUri() method
  collect_app/src/main/java/org/odk/collect/android/dao/helpers/ContentResolverHelper.java
  collect_app/src/main/java/org/odk/collect/android/tasks/MediaLoadingTask.java
  collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java
Labels: behavior verified

#4112 Fixed padding in choices
  collect_app/src/main/res/layout/select_multi_item.xml
  collect_app/src/main/res/layout/select_one_item.xml
Labels: behavior verified

#4120 Handle multi-clicking on menu items
  collect_app/src/main/java/org/odk/collect/android/activities/AppListActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FillBlankFormActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderListActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeTabsActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryMenuDelegate.java
  collect_app/src/main/java/org/odk/collect/android/fragments/AppListFragment.java
Labels: behavior verified

#4025 Remove Answer Text View in Url Widget
  collect_app/src/main/java/org/odk/collect/android/analytics/AnalyticsEvents.java
  collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/formentry/media/PromptAutoplayer.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/BaseSelectListWidget.java
  collect_app/src/main/res/layout/url_widget_answer.xml
  collect_app/src/test/java/org/odk/collect/android/widgets/UrlWidgetTest.java
Labels: behavior verified

#4140 Fixed loading downloaded media files
  collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java
Labels: behavior verified

#4138 Fixed the form end screen
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/res/layout/form_entry.xml
Labels: behavior verified

#4144 Fixed crashes when a user changes Blank form update mode if one of related options is disabled in Admin settings
  collect_app/src/main/java/org/odk/collect/android/preferences/FormManagementPreferences.java
  collect_app/src/test/java/org/odk/collect/android/preferences/FormManagementPreferencesTest.java
Labels: behavior verified

#4148 Catch and display error when new repeat created
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryViewModelTest.java
Labels: behavior verified

#4158 Downgraded commons-io dependency
  collect_app/build.gradle
Labels: behavior verified

#3969 Reworking Range Widget
  collect_app/build.gradle
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/views/TrackingTouchSlider.java
  collect_app/src/main/java/org/odk/collect/android/widgets/RangeDecimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/RangeIntegerWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/RangePickerDecimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/RangePickerIntegerWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/RangeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/RangeWidgetUtils.java
  collect_app/src/main/res/color/slider_tick_tint_list.xml
  collect_app/src/main/res/color/slider_track_tint_list.xml
  collect_app/src/main/res/layout/range_picker_widget_answer.xml
  collect_app/src/main/res/layout/range_widget_horizontal.xml
  collect_app/src/main/res/layout/range_widget_vertical.xml
  collect_app/src/main/res/layout/url_widget_answer.xml
  collect_app/src/main/res/values/attrs.xml
  collect_app/src/main/res/values/dark_theme.xml
  collect_app/src/main/res/values/light_theme.xml
  collect_app/src/main/res/values/magenta_theme.xml
  collect_app/src/main/res/values/slider_theme.xml
  collect_app/src/main/res/values/styles.xml
  collect_app/src/test/java/org/odk/collect/android/support/MockFormEntryPromptBuilder.java
  collect_app/src/test/java/org/odk/collect/android/support/RobolectricHelpers.java
  collect_app/src/test/java/org/odk/collect/android/views/TrackingTouchSliderTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/RangeDecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/RangeIntegerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/RangePickerDecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/RangePickerIntegerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/RangeWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/support/QuestionWidgetHelpers.java
  collect_app/src/test/java/org/odk/collect/android/widgets/utilities/RangeWidgetUtilsTest.java
Labels: behavior verified

#4164 Fix Margin for Buttons in Audio and Barcode Widget
  collect_app/src/main/res/layout/audio_widget_answer.xml
  collect_app/src/main/res/layout/barcode_widget_answer.xml
Labels: behavior verified

#4141 Alternative fix for redownloading delete forms from Google Drive
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/DeleteBlankFormTest.java
  collect_app/src/main/java/org/odk/collect/android/gdrive/GoogleDriveActivity.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormsDirDiskFormsSynchronizer.java
Labels: behavior verified

#4065 Improved displaying choices with columns-pack appearance
  collect_app/src/main/java/org/odk/collect/android/adapters/AbstractSelectListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/adapters/SelectMultipleListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/adapters/SelectOneListAdapter.java
  collect_app/src/test/java/org/odk/collect/android/views/ChoicesRecyclerViewTest.java
Labels: behavior verified

#3922 Reworking GeoShape and GeoTraceWidget
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPolyActivity.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BaseGeoWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BearingWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DateTimeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExDecimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExIntegerWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExPrinterWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoPointMapWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoPointWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoShapeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoTraceWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/OSMWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/main/java/org/odk/collect/android/widgets/interfaces/GeoDataRequester.java
  collect_app/src/main/java/org/odk/collect/android/widgets/interfaces/GeoWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/interfaces/WidgetDataReceiver.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/RankingWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectMinimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectMultiMinimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneMinimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/ActivityGeoDataRequester.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoWidgetUtils.java
  collect_app/src/main/res/values/buttons.xml
  collect_app/src/main/res/values/strings.xml
  collect_app/src/test/java/org/odk/collect/android/location/activities/GeoPointActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/AudioWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/BarcodeWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/BearingWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/DateTimeWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/DateWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/GeoPointMapWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/GeoPointWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/GeoShapeWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/GeoTraceWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/BaseGeoWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/BinaryWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectMultiMinimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectOneMinimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/support/GeoWidgetHelpers.java
  collect_app/src/test/java/org/odk/collect/android/widgets/support/QuestionWidgetHelpers.java
  collect_app/src/test/java/org/odk/collect/android/widgets/utilities/ActivityGeoDataRequesterTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/utilities/GeoWidgetUtilsTest.java
Labels: behavior verified

#4175 Scale icons on form entry and hierarchy screens to match others
  collect_app/src/main/res/drawable/arrow_up.xml
  collect_app/src/main/res/drawable/ic_add_circle_24.xml
  collect_app/src/main/res/drawable/ic_delete_menu_24.xml
  collect_app/src/main/res/drawable/ic_menu_goto_24.xml
  collect_app/src/main/res/drawable/ic_save_menu_24.xml
  collect_app/src/main/res/menu/form_hierarchy_menu.xml
  collect_app/src/main/res/menu/form_menu.xml
Labels: behavior verified

#4182 Set main instance name to null when editing saved form
  collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java
Labels: behavior verified, high priority

#4187 Use JavaRosa v3.0.3 to fix bug in complex calculates
  collect_app/build.gradle
Labels: high priority, needs testing
