Repository getodk/collect, pull requests merged in 2020-09, with the labels that each got.

#4021 Use Expandable Notification for Match Exactly errors
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/MatchExactlyTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/ApplicationInitializer.java
  collect_app/src/main/java/org/odk/collect/android/notifications/NotificationManagerNotifier.java
  collect_app/src/main/java/org/odk/collect/android/utilities/NotificationUtils.java
Labels: behavior verified

#4028 Make sure soft-deleted form can be re-downloaded
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EncryptedFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/DeleteBlankFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/dao/InstancesDaoTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/tasks/InstanceServerUploaderTaskTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/InstanceUploaderUtilsTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java
  collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormMapViewModel.java
  collect_app/src/main/java/org/odk/collect/android/adapters/InstanceListCursorAdapter.java
  collect_app/src/main/java/org/odk/collect/android/adapters/InstanceUploaderAdapter.java
  collect_app/src/main/java/org/odk/collect/android/dao/FormsDao.java
  collect_app/src/main/java/org/odk/collect/android/dao/InstancesDao.java
  collect_app/src/main/java/org/odk/collect/android/dao/helpers/InstancesDaoHelper.java
  collect_app/src/main/java/org/odk/collect/android/database/DatabaseFormsRepository.java
  collect_app/src/main/java/org/odk/collect/android/database/DatabaseInstancesRepository.java
  collect_app/src/main/java/org/odk/collect/android/database/InstancesDatabaseHelper.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/FormDeleter.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormsDetailsFetcher.java
  collect_app/src/main/java/org/odk/collect/android/forms/FormsRepository.java
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceDeleter.java
  collect_app/src/main/java/org/odk/collect/android/instances/Instance.java
  collect_app/src/main/java/org/odk/collect/android/instances/InstancesRepository.java
  collect_app/src/main/java/org/odk/collect/android/provider/FormsProvider.java
  collect_app/src/main/java/org/odk/collect/android/provider/InstanceProvider.java
  collect_app/src/main/java/org/odk/collect/android/provider/InstanceProviderAPI.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceSyncTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/SaveFormToDisk.java
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceUploader.java
  collect_app/src/main/java/org/odk/collect/android/utilities/IconUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/MultiFormDownloader.java
  collect_app/src/test/java/org/odk/collect/android/activities/FormMapViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/FormDeleterTest.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormsDetailsFetcherTest.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormsSynchronizerTest.java
  collect_app/src/test/java/org/odk/collect/android/forms/FormsRepositoryTest.java
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/InstanceDeleterTest.java
  collect_app/src/test/java/org/odk/collect/android/support/InMemFormsRepository.java
  collect_app/src/test/java/org/odk/collect/android/support/InMemInstancesRepository.java
  collect_app/src/test/java/org/odk/collect/android/support/InstanceUtils.java
Labels: behavior verified

#4017 Fixed auto-delete and auto-sent options
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/InstanceUploaderUtilsTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GoogleSheetsUploaderActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java
  collect_app/src/main/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpec.java
  collect_app/src/main/java/org/odk/collect/android/dao/FormsDao.java
  collect_app/src/main/java/org/odk/collect/android/database/DatabaseInstancesRepository.java
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceSubmitter.java
  collect_app/src/main/java/org/odk/collect/android/instances/InstancesRepository.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceUploader.java
  collect_app/src/main/java/org/odk/collect/android/utilities/InstanceUploaderUtils.java
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/InstanceSubmitterTest.java
  collect_app/src/test/java/org/odk/collect/android/support/InMemInstancesRepository.java
  collect_app/src/test/java/org/odk/collect/android/utilities/InstanceUploaderUtilsTest.java
Labels: behavior verified

#4038 Match exactly tweaks and polish
  async/src/main/java/org/odk/collect/async/CoroutineAndWorkManagerScheduler.kt
  async/src/main/java/org/odk/collect/async/Scheduler.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/MatchExactlyTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/FormManagementSettingsTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/TestScheduler.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FillBlankFormPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/MainMenuPage.java
  collect_app/src/main/java/org/odk/collect/android/activities/FillBlankFormActivity.java
  collect_app/src/main/java/org/odk/collect/android/adapters/InstanceUploaderAdapter.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/BlankFormListMenuDelegate.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/BlankFormsListViewModel.java
  collect_app/src/main/java/org/odk/collect/android/preferences/FormManagementPreferences.java
  collect_app/src/main/java/org/odk/collect/android/views/InstanceUploaderProgressBar.java
  collect_app/src/main/java/org/odk/collect/android/views/ObviousProgressBar.java
  collect_app/src/main/res/drawable/ic_baseline_refresh_error_24.xml
  collect_app/src/main/res/drawable/ic_baseline_search_24.xml
  collect_app/src/main/res/drawable/ic_baseline_sort_24.xml
  collect_app/src/main/res/drawable/ic_search.xml
  collect_app/src/main/res/layout/app_bar_layout.xml
  collect_app/src/main/res/layout/form_chooser_list_item_text.xml
  collect_app/src/main/res/menu/list_menu.xml
  collect_app/src/main/res/menu/select_minimal_dialog_menu.xml
  collect_app/src/main/res/values/arrays.xml
  collect_app/src/main/res/values/strings.xml
  collect_app/src/test/java/org/odk/collect/android/formmanagement/BlankFormListMenuDelegateTest.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/BlankFormsListViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/notifications/NotificationManagerNotifierTest.java
  collect_app/src/test/java/org/odk/collect/android/preferences/FormManagementPreferencesTest.java
  collect_app/src/test/java/org/odk/collect/android/support/FakeScheduler.java
Labels: behavior verified

#4055 Do not save answers again after closing select minimal dialog to improve performance
  collect_app/src/main/java/org/odk/collect/android/adapters/AbstractSelectListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/adapters/SelectMultipleListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/adapters/SelectOneListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/SelectMinimalDialog.java
  collect_app/src/test/java/org/odk/collect/android/fragments/dialogs/SelectMinimalDialogTest.java
  collect_app/src/test/java/org/odk/collect/android/fragments/dialogs/SelectMultiMinimalDialogTest.java
  collect_app/src/test/java/org/odk/collect/android/fragments/dialogs/SelectOneMinimalDialogTest.java
  collect_app/src/test/java/org/odk/collect/android/views/ChoicesRecyclerViewTest.java
Labels: behavior verified

#4063 Fixed strange bug with mixing answers in field-list
  collect_app/src/main/res/layout/select_minimal_widget_answer.xml
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectOneMinimalWidgetTest.java
Labels: behavior verified

#4049 Fixed automatic location recording
  collect_app/src/main/java/org/odk/collect/android/geo/SettingsDialogFragment.java
  collect_app/src/test/java/org/odk/collect/android/geo/SettingsDialogFragmentTest.java
Labels: behavior verified

#4016 Adjusted gesture navigation
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/listeners/SwipeHandler.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ScreenUtils.java
Labels: needs testing

#4061 Fixed invisible radio buttons / checkboxes on android 5.0
  collect_app/src/main/res/drawable-v22/inset_check_box.xml
  collect_app/src/main/res/drawable-v22/inset_radio_button.xml
  collect_app/src/main/res/drawable/inset_check_box.xml
  collect_app/src/main/res/drawable/inset_radio_button.xml
Labels: needs testing

#4041 Improve match exactly error handling
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/FormApiExceptionMapper.java
  collect_app/src/main/java/org/odk/collect/android/openrosa/OpenRosaXmlFetcher.java
  collect_app/src/main/java/org/odk/collect/android/openrosa/api/FormApiException.java
  collect_app/src/main/java/org/odk/collect/android/openrosa/api/OpenRosaFormListApi.java
  collect_app/src/main/res/values/strings.xml
  collect_app/src/test/java/org/odk/collect/android/formmanagement/FormApiExceptionMapperTest.java
  collect_app/src/test/java/org/odk/collect/android/openrosa/api/OpenRosaFormListApiTest.java
Labels: needs testing

#4064 Show friendlier errors on form download failure
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/GetBlankFormsTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/StubOpenRosaServer.java
  collect_app/src/main/java/org/odk/collect/android/openrosa/OpenRosaXmlFetcher.java
  collect_app/src/main/java/org/odk/collect/android/openrosa/api/OpenRosaFormListApi.java
  collect_app/src/main/java/org/odk/collect/android/utilities/MultiFormDownloader.java
  collect_app/src/main/res/values-ar/strings.xml
  collect_app/src/main/res/values-cs/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-fa/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-pl/strings.xml
  collect_app/src/main/res/values-sr/strings.xml
  collect_app/src/main/res/values-te/strings.xml
  collect_app/src/main/res/values/strings.xml
  collect_app/src/test/java/org/odk/collect/android/openrosa/api/OpenRosaFormListApiTest.java
  collect_app/src/test/java/org/odk/collect/android/utilities/MultiFormDownloaderTest.java
Labels: needs testing

#4073 Fixed map layer dialog
  collect_app/src/main/java/org/odk/collect/android/preferences/CaptionedListPreference.java
  collect_app/src/main/java/org/odk/collect/android/preferences/MapsPreferences.java
  collect_app/src/main/res/layout/captioned_item.xml
Labels: behavior verified

#4081 Fixed changing languages
  collect_app/build.gradle
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/dao/FormsDaoTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/settings/ResetAppStateTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/ResetStateRule.java
  collect_app/src/main/java/org/odk/collect/android/activities/CollectAbstractActivity.java
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/ApplicationInitializer.java
  collect_app/src/main/java/org/odk/collect/android/preferences/ResetDialogPreferenceFragmentCompat.java
  collect_app/src/main/java/org/odk/collect/android/preferences/UserInterfacePreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationResetter.java
  collect_app/src/main/java/org/odk/collect/android/utilities/LocaleHelper.java
Labels: behavior verified

#4087 Switch camera after setting up CaptureManager
  collect_app/src/main/java/org/odk/collect/android/fragments/BarCodeScannerFragment.java
Labels: behavior verified

#4082 Fixed checking for spaces in underlying values
  collect_app/src/main/java/org/odk/collect/android/widgets/items/ListMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectMultiMinimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectMultiWidget.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/ListMultiWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/RankingWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectMultiImageMapWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectMultiMinimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectMultiWidgetTest.java
Labels: behavior verified

#4089 Fixed selecting answers in select_multiple minimal
  collect_app/src/main/java/org/odk/collect/android/adapters/SelectMultipleListAdapter.java
  collect_app/src/test/java/org/odk/collect/android/views/ChoicesRecyclerViewTest.java
Labels: behavior verified

#4091 Make sure a user can not open reset app dialog multiple times
  collect_app/src/main/java/org/odk/collect/android/preferences/AdminPreferencesFragment.java
Labels: behavior verified

#4098 Sanitize form version
  collect_app/src/main/java/org/odk/collect/android/openrosa/api/OpenRosaFormListApi.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
  collect_app/src/test/java/org/odk/collect/android/utilities/FileUtilsTest.java
Labels: behavior verified

#4100 Fixed downloading forms from an external app
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/tasks/DownloadFormListTaskTest.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormsDetailsFetcher.java
  collect_app/src/main/java/org/odk/collect/android/openrosa/OpenRosaXmlFetcher.java
  collect_app/src/main/java/org/odk/collect/android/openrosa/api/FormListApi.java
  collect_app/src/main/java/org/odk/collect/android/openrosa/api/OpenRosaFormListApi.java
  collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormListTask.java
  collect_app/src/main/java/org/odk/collect/android/utilities/DialogUtils.java
Labels: behavior verified

#4099 Stop server list being cleared on import
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ConfigureWithQRCodeTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/configure/qr/QRCodeUtilsTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ChangingServerUrlUtilsTest.java
  collect_app/src/main/java/org/odk/collect/android/application/CollectSettingsChangeHandler.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/CollectSettingsPreferenceMigrator.java
  collect_app/src/main/java/org/odk/collect/android/configure/ServerRepository.java
  collect_app/src/main/java/org/odk/collect/android/configure/SettingsChangeHandler.java
  collect_app/src/main/java/org/odk/collect/android/configure/SettingsImporter.java
  collect_app/src/main/java/org/odk/collect/android/configure/SharedPreferencesServerRepository.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/preferences/BasePreferenceFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/MetaKeys.java
  collect_app/src/main/java/org/odk/collect/android/preferences/ServerPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/utilities/ChangingServerUrlUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationResetter.java
  collect_app/src/test/java/org/odk/collect/android/application/CollectSettingsChangeHandlerTest.java
  collect_app/src/test/java/org/odk/collect/android/application/initialization/CollectSettingsPreferenceMigratorTest.java
  collect_app/src/test/java/org/odk/collect/android/configure/SettingsImporterTest.java
  collect_app/src/test/java/org/odk/collect/android/configure/SharedPreferencesServerRepositoryTest.java
  collect_app/src/test/java/org/odk/collect/android/utilities/ApplicationResetterTest.java
Labels: behavior verified

#4107 Fixed crash caused by deleted media folder
  collect_app/src/main/java/org/odk/collect/android/database/DatabaseMediaFileRepository.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FileUtil.java
  collect_app/src/test/java/org/odk/collect/android/database/DatabaseMediaFileRepositoryTest.java
  collect_app/src/test/java/org/odk/collect/android/utilities/FileUtilTest.java
Labels: behavior verified

#4109 Restore soft deleted forms that have been re added to the forms folder
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/DeleteBlankFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/SendFinalizedFormTest.java
  collect_app/src/main/java/org/odk/collect/android/dao/FormsDao.java
  collect_app/src/main/java/org/odk/collect/android/database/DatabaseConstants.java
  collect_app/src/main/java/org/odk/collect/android/database/DatabaseFormsRepository.java
  collect_app/src/main/java/org/odk/collect/android/database/FormDatabaseMigrator.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/main/java/org/odk/collect/android/provider/FormsProvider.java
  collect_app/src/main/java/org/odk/collect/android/provider/FormsProviderAPI.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormsDirDiskFormsSynchronizer.java
  collect_app/src/test/java/org/odk/collect/android/database/FormDatabaseMigratorTest.java
  docs/STATE.md
Labels: behavior verified

#4118 Prevent NPE in QuitFormDialogFragment
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryMenuDelegate.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/QuitFormDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/formentry/RequiresFormController.java
  collect_app/src/main/java/org/odk/collect/android/formentry/audit/IdentityPromptViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java
  collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java
Labels: high priority, needs testing

#4127 Fix flakey delete form test
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/DeleteBlankFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FillBlankFormPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.java
Labels: high priority

#4045 Fixed handling translations
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormDownloadListViewModel.java
  collect_app/src/main/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpec.java
  collect_app/src/main/java/org/odk/collect/android/backgroundwork/BackgroundWorkUtils.java
  collect_app/src/main/java/org/odk/collect/android/backgroundwork/SchedulerFormUpdateAndSubmitManager.java
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeScannerFragment.java
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeUtils.java
  collect_app/src/main/java/org/odk/collect/android/external/ExternalDataManagerImpl.java
  collect_app/src/main/java/org/odk/collect/android/external/ExternalDataUtil.java
  collect_app/src/main/java/org/odk/collect/android/external/ExternalSQLiteOpenHelper.java
  collect_app/src/main/java/org/odk/collect/android/external/handler/ExternalDataHandlerSearch.java
  collect_app/src/main/java/org/odk/collect/android/formentry/RefreshFormListDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/FormApiExceptionMapper.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDownloader.java
  collect_app/src/main/java/org/odk/collect/android/gdrive/GoogleDriveActivity.java
  collect_app/src/main/java/org/odk/collect/android/gdrive/InstanceGoogleSheetsUploader.java
  collect_app/src/main/java/org/odk/collect/android/gdrive/InstanceGoogleSheetsUploaderTask.java
  collect_app/src/main/java/org/odk/collect/android/geo/WebMapService.java
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceSubmitter.java
  collect_app/src/main/java/org/odk/collect/android/notifications/NotificationManagerNotifier.java
  collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceServerUploaderTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceSyncTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/SaveFormToDisk.java
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java
  collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormsDirDiskFormsSynchronizer.java
  collect_app/src/main/java/org/odk/collect/android/utilities/InstanceUploaderUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/MultiFormDownloader.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ToastUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/TranslationHandler.java
  collect_app/src/main/java/org/odk/collect/android/utilities/UrlUtils.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/FormApiExceptionMapperTest.java
Labels: behavior verified
