Repository getodk/collect, pull requests merged in 2020-06, with the labels that each got.

#3872 Exit form when instance file cannot be created/is null
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/loading/FormInstanceFileCreator.java
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/FormController.java
  collect_app/src/test/java/org/odk/collect/android/formentry/loading/FormInstanceFileCreatorTest.java
  collect_app/src/test/java/org/odk/collect/android/javarosawrapper/FormControllerTest.java
Labels: behavior verified, high priority

#3882 Updated work manager dependency to androidx
  collect_app/build.gradle
Labels: behavior verified, high priority

#3782 Used Dialog Fragment to retain Exit Form Dialog on Orientation Change
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/QuitFormDialog.java
  collect_app/src/main/java/org/odk/collect/android/formentry/QuitFormDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/test/java/org/odk/collect/android/formentry/QuitFormDialogFragmentTest.java
  collect_app/src/test/java/org/odk/collect/android/support/RobolectricHelpers.java
Labels: behavior verified

#3786 Retains Select Layer Dialog on changing the Orientation
  collect_app/src/main/java/org/odk/collect/android/preferences/CaptionedListPreference.java
  collect_app/src/main/java/org/odk/collect/android/preferences/MapsPreferences.java
Labels: behavior verified

#3824 Used Dialog Fragment to retain Change Admin Password Dialog on Orientation Change
  collect_app/src/main/java/org/odk/collect/android/preferences/AdminPreferencesActivity.java
  collect_app/src/main/java/org/odk/collect/android/preferences/AdminPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/ChangeAdminPasswordDialog.java
  collect_app/src/test/java/org/odk/collect/android/preferences/ChangeAdminPasswordDialogTest.java
Labels: behavior verified

#3858 Added Search View Style for Magenta Theme to remove Search Hint icon
  collect_app/src/main/res/values/magenta_theme.xml
Labels: behavior verified

#3851 Fixed Dialog Button for Experimental Magenta Theme
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormDownloadListViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/RefreshFormListDialogFragment.java
  collect_app/src/main/res/layout/progress_dialog.xml
  collect_app/src/test/java/org/odk/collect/android/formentry/RefreshFormListDialogFragmentTest.java
Labels: behavior verified

#3813 Remove KEYS_WE_SHOULD_NOT_RESET
  collect_app/src/androidTest/java/org/odk/collect/android/feature/externalintents/SplashScreenActivityTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/FormMetadataTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/dao/FormsDaoTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/settings/ResetAppStateTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/ResetStateRule.java
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/SplashScreenActivity.java
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
  collect_app/src/main/java/org/odk/collect/android/application/TestCollect.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/ApplicationInitializer.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/PrefMigrator.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/migration/KeyCombiner.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/migration/KeyMover.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/migration/KeyRenamer.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/migration/KeyTranslator.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/migration/Migration.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/migration/MigrationUtils.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/migration/Pair.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/migration/ValueTranslator.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/preferences/FormMetadataFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/FormMetadataMigrator.java
  collect_app/src/main/java/org/odk/collect/android/preferences/GeneralKeys.java
  collect_app/src/main/java/org/odk/collect/android/preferences/GeneralSharedPreferences.java
  collect_app/src/main/java/org/odk/collect/android/preferences/MapsPreferences.java
  collect_app/src/main/java/org/odk/collect/android/preferences/MetaKeys.java
  collect_app/src/main/java/org/odk/collect/android/preferences/PrefMigrator.java
  collect_app/src/main/java/org/odk/collect/android/preferences/ResetDialogPreference.java
  collect_app/src/main/java/org/odk/collect/android/storage/StoragePathProvider.java
  collect_app/src/main/java/org/odk/collect/android/storage/StorageStateProvider.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationResetter.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/NotificationUtils.java
  collect_app/src/test/java/org/odk/collect/android/activities/InstanceUploaderListActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/activities/SplashScreenActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/activities/support/AlwaysDenyStoragePermissionPermissionUtils.java
  collect_app/src/test/java/org/odk/collect/android/activities/support/AlwaysGrantStoragePermissionsPermissionUtils.java
  collect_app/src/test/java/org/odk/collect/android/application/initialization/PrefMigratorTest.java
  collect_app/src/test/java/org/odk/collect/android/application/initialization/migration/KeyCombinerTest.java
  collect_app/src/test/java/org/odk/collect/android/application/initialization/migration/KeyMoverTest.java
  collect_app/src/test/java/org/odk/collect/android/application/initialization/migration/KeyRemoverTest.java
  collect_app/src/test/java/org/odk/collect/android/application/initialization/migration/KeyRenamerTest.java
  collect_app/src/test/java/org/odk/collect/android/application/initialization/migration/KeyTranslatorTest.java
  collect_app/src/test/java/org/odk/collect/android/application/initialization/migration/SharedPreferenceUtils.java
  collect_app/src/test/java/org/odk/collect/android/preferences/FormMetadataMigratorTest.java
  collect_app/src/test/java/org/odk/collect/android/preferences/PrefMigratorTest.java
  collect_app/src/test/java/org/odk/collect/android/storage/migration/StorageMigratorTest.java
  collect_app/src/test/java/org/odk/collect/android/support/RobolectricHelpers.java
Labels: behavior verified

#3792 Retain Input Setting Dialog on GeoPolyActivity on orientation change
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPolyActivity.java
  collect_app/src/main/java/org/odk/collect/android/geo/SettingsDialogFragment.java
  collect_app/src/test/java/org/odk/collect/android/geo/SettingsDialogFragmentTest.java
Labels: behavior verified

#3904 Fixed FormEntryActivity.isQuestionRecalculated() method
  collect_app/src/androidTest/assets/forms/fieldlist-updates.xml
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FieldListUpdateTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
Labels: behavior verified

#3898 Keep swiping blocked until AddRepeatDialog is closed
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
Labels: behavior verified

#3927 Fixed selecting elements in no-button widgets
  collect_app/src/main/java/org/odk/collect/android/adapters/SelectMultipleListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/adapters/SelectOneListAdapter.java
Labels: behavior verified, high priority

#3888 Fixed Failed to find configured root that contains on huawei devices
  collect_app/src/androidTest/java/org/odk/collect/android/preferences/qr/ConfigureWithQRCodeTest.java
  collect_app/src/main/java/org/odk/collect/android/formentry/questions/AudioVideoImageTextLabel.java
  collect_app/src/main/java/org/odk/collect/android/preferences/qr/QRCodeTabsActivity.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ContentUriProvider.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
Labels: behavior verified

#3831 Rewriting URL widget
  collect_app/build.gradle
  collect_app/src/main/java/org/odk/collect/android/views/MultiClickSafeButton.java
  collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/main/res/layout/url_widget_answer.xml
  collect_app/src/test/java/org/odk/collect/android/widgets/UrlWidgetTest.java
  config/quality.gradle
Labels: behavior verified

#3917 Fixed bug in GeoPolyActivity.clear()
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPolyActivity.java
Labels: behavior verified

#3920 Fixed navigation buttons in form entry in Magenta theme
  collect_app/src/main/res/drawable/ic_navigate_back.xml
  collect_app/src/main/res/drawable/ic_navigate_forward.xml
  collect_app/src/main/res/layout/form_entry.xml
Labels: needs testing

#3912 Fixed back button behavior in FormHierarchyActivity
  collect_app/src/androidTest/assets/forms/repeat_groups.xml
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/DeletingRepeatGroupsTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEndPage.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
Labels: behavior verified

#3910 Implemented viewmodel for RankingWidgetDialog to solve the problem with serialization
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/RankingWidgetDialog.java
  collect_app/src/main/java/org/odk/collect/android/fragments/viewmodels/RankingViewModel.java
  collect_app/src/main/java/org/odk/collect/android/widgets/RankingWidget.java
Labels: behavior verified

#3932 Fixed search view colors
  collect_app/src/main/java/org/odk/collect/android/activities/AppListActivity.java
  collect_app/src/main/java/org/odk/collect/android/fragments/AppListFragment.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ThemeUtils.java
  collect_app/src/main/res/values/magenta_theme.xml
Labels: behavior verified

#3864 Instance map view improvements
  collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPointMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormMapViewModel.java
  collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/geo/MapFragment.java
  collect_app/src/main/java/org/odk/collect/android/geo/MapboxMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java
  collect_app/src/main/res/drawable/ic_room_blue_48dp.xml
  collect_app/src/main/res/drawable/ic_room_deep_purple_48dp.xml
  collect_app/src/main/res/drawable/ic_room_green_48dp.xml
  collect_app/src/main/res/drawable/ic_room_red_48dp.xml
  collect_app/src/main/res/values/strings.xml
  collect_app/src/test/java/org/odk/collect/android/activities/FormMapActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/geo/TestMapFragment.java
Labels: behavior verified
