Repository getodk/collect, pull requests merged in 2020-11, with the labels that each got.

#4183 Fix displaying recordings over an hour
  collect_app/src/main/java/org/odk/collect/android/audio/AudioControllerView.java
  collect_app/src/main/java/org/odk/collect/android/audio/LengthFormatter.java
  collect_app/src/test/java/org/odk/collect/android/audio/AudioControllerViewTest.java
  collect_app/src/test/java/org/odk/collect/android/audio/LengthFormatterTest.java
Labels: behavior verified

#4201 Fixed multiclick issue that gives a possibility to open multiple dialogs with choices
  collect_app/src/main/java/org/odk/collect/android/utilities/DialogUtils.java
  collect_app/src/main/java/org/odk/collect/android/views/MultiClickSafeTextInputEditText.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectMultiMinimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneMinimalWidget.java
  collect_app/src/main/res/layout/select_minimal_widget_answer.xml
Labels: behavior verified, high priority

#4188 Extend existing external application functionality to receive binary files in field-list groups
  collect_app/src/androidTest/assets/forms/intent-group.xml
  collect_app/src/androidTest/assets/media/sampleAudio.wav
  collect_app/src/androidTest/assets/media/sampleVideo.mp4
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/IntentGroupTest.java
  collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/formentry/questions/QuestionDetails.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DecimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DrawWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/IntegerWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SignatureWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/StringNumberWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/StringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ArbitraryFileWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/AudioWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/DecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/DrawWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ImageWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/IntegerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/SignatureWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/StringNumberWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/StringWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/VideoWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/GeneralExStringWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/GeneralStringWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/WidgetTest.java
Labels: behavior verified

#4191 Changes in metadata required to update the app to API 29
  collect_app/src/androidTest/assets/forms/CSVerrorForm.xml
  collect_app/src/androidTest/assets/forms/metadata.xml
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/FormMetadataTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/tasks/InstanceServerUploaderTaskTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderListActivity.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceSubmitter.java
  collect_app/src/main/java/org/odk/collect/android/logic/PropertyManager.java
  collect_app/src/main/java/org/odk/collect/android/preferences/FormMetadataFragment.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceServerUploaderTask.java
  collect_app/src/main/java/org/odk/collect/android/utilities/DeviceDetailsProvider.java
  collect_app/src/main/res/xml/form_metadata_preferences.xml
  collect_app/src/test/java/org/odk/collect/android/preferences/FormMetadataFragmentTest.java
  strings/src/main/res/values-cs/strings.xml
  strings/src/main/res/values-de/strings.xml
  strings/src/main/res/values-es/strings.xml
  strings/src/main/res/values-fi/strings.xml
  strings/src/main/res/values-fr/strings.xml
  strings/src/main/res/values-in/strings.xml
  strings/src/main/res/values/strings.xml
Labels: behavior verified

#4166 Define new style for Image Button in Magenta Theme
  collect_app/src/main/res/color/map_button_tint_list.xml
  collect_app/src/main/res/layout/geopoint_layout.xml
  collect_app/src/main/res/layout/geopoly_layout.xml
  collect_app/src/main/res/layout/instance_map_layout.xml
  collect_app/src/main/res/values/buttons.xml
  collect_app/src/main/res/values/light_theme.xml
  collect_app/src/main/res/values/themes.xml
Labels: behavior verified

#3937 Reworking Rating Widget
  collect_app/build.gradle
  collect_app/src/main/java/org/odk/collect/android/widgets/RatingWidget.java
  collect_app/src/main/res/drawable/ic_star.xml
  collect_app/src/main/res/drawable/ic_star_border.xml
  collect_app/src/main/res/layout/rating_widget_answer.xml
  collect_app/src/test/java/org/odk/collect/android/widgets/RatingWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/support/QuestionWidgetHelpers.java
Labels: behavior verified

#4195 Fixed map icon button
  collect_app/src/main/res/layout/form_chooser_list_item_map_button.xml
Labels: behavior verified

#4197 Show warning when importing legacy settings
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ConfigureWithLegacyFileTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/TestDependencies.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/OkDialog.java
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/java/org/odk/collect/android/configure/legacy/LegacySettingsFileImporter.java
  collect_app/src/main/java/org/odk/collect/android/configure/legacy/LegacySettingsFileReader.java
  collect_app/src/test/java/org/odk/collect/android/configure/LegacySettingsFileReaderTest.java
  strings/src/main/res/values/strings.xml
Labels: behavior verified

#4169 Fix sort by displaying unexpectedly issue after using map button or search icon
  collect_app/src/main/java/org/odk/collect/android/activities/AppListActivity.java
Labels: behavior verified

#4177 3780 restore exif data after rotate or resize
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ImageConverterTest.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java
Labels: behavior verified

#4203 Fixed columns-pack appearance
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ScreenUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/WidgetAppearanceUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectMultiMinimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneMinimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneWidget.java
  collect_app/src/test/java/org/odk/collect/android/utilities/WidgetAppearanceUtilsTest.java
Labels: behavior verified

#4200 Make clicking recording notification return to app
  audiorecorder/src/main/AndroidManifest.xml
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recording/internal/AudioRecorderService.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recording/internal/ReturnToAppActivity.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recording/internal/AudioRecorderServiceTest.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recording/internal/ReturnToAppActivityTest.kt
Labels: behavior verified

#4208 Try using the package manager to get a launch intent for external apps, support string uris for binary external widgets
  collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
Labels: behavior verified

#4227 Fixed the Record a point button
  collect_app/src/main/res/layout/geopoly_layout.xml
Labels: needs testing

#4196 Force storage migration
  build.gradle
  collect_app/build.gradle
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/ExternalDataFileNotFoundTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/storage/AutomaticStorageMigrationTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/storage/StorageMigrationCompletedBannerTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/storage/StorageMigrationTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/ResetStateRule.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/TestRuleChain.java
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/SplashScreenActivity.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/storage/StorageStateProvider.java
  collect_app/src/test/java/org/odk/collect/android/activities/MainMenuButtonsVisibilityTest.java
  collect_app/src/test/java/org/odk/collect/android/activities/SplashScreenActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/storage/StorageStateProviderTest.java
  strings/src/main/res/values/strings.xml
Labels: behavior verified

#4215 Stop user leaving recording
  .circleci/config.yml
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/DaggerSetup.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/RobolectricApplication.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recording/internal/AudioRecorderServiceTest.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recording/internal/RealAudioRecorderViewModelTest.kt
  audiorecorder/src/test/resources/robolectric.properties
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/AudioRecordingTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/OkDialog.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryMenuDelegate.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/formentry/QuitFormDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/formentry/RecordingWarningDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/FormController.java
  collect_app/src/main/java/org/odk/collect/android/listeners/SwipeHandler.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/BaseSelectListWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/SearchQueryViewModel.java
  collect_app/src/main/res/layout/select_list_widget_answer.xml
  collect_app/src/test/java/org/odk/collect/android/application/RobolectricApplication.java
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryMenuDelegateTest.java
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/support/RobolectricHelpers.java
  collect_app/src/test/resources/robolectric.properties
  strings/src/main/res/values/strings.xml
Labels: behavior verified

#4221 Don't always save media captured through Collect to the Media Store
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/dao/helpers/ContentResolverHelper.java
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java
  collect_app/src/main/java/org/odk/collect/android/preferences/UserInterfacePreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/provider/FormsProvider.java
  collect_app/src/main/java/org/odk/collect/android/provider/InstanceProvider.java
  collect_app/src/main/java/org/odk/collect/android/tasks/MediaLoadingTask.java
  collect_app/src/main/java/org/odk/collect/android/tasks/SaveFormToDisk.java
  collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtil.java
  collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DrawWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SignatureWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/FileWidgetUtils.java
  collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/utilities/MediaUtilsTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ArbitraryFileWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/VideoWidgetTest.java
Labels: needs testing

#4226 Trust root certificate that will root all certs issued by Let's Encrypt after Sept 2021
  collect_app/build.gradle
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/AboutActivity.java
  collect_app/src/main/java/org/odk/collect/android/openrosa/okhttp/OkHttpOpenRosaServerClientProvider.java
  collect_app/src/main/res/raw/isrgrootx1.pem
  collect_app/src/main/res/xml/network_security_config.xml
Labels: behavior verified

#4232 Use glide to display images in selects
  collect_app/build.gradle
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/adapters/AbstractSelectListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/adapters/SelectMultipleListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/adapters/SelectOneListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/formentry/questions/AudioVideoImageTextLabel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/questions/NoButtonsItem.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/res/drawable/select_item_border.xml
  collect_app/src/main/res/layout/no_buttons_item_layout.xml
  collect_app/src/main/res/values/dimens.xml
  collect_app/src/test/java/org/odk/collect/android/views/ChoicesRecyclerViewTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectMultiWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectOneWidgetTest.java
Labels: behavior verified

#4230 Expose more information in HEAD request error
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java
Labels: behavior verified

#4231 Show navigation buttons for new installs
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormNavigationButtonTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/NavigationButtonsTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/UserInterfacePage.java
  collect_app/src/main/java/org/odk/collect/android/preferences/GeneralKeys.java
Labels: behavior verified
