Repository getodk/collect, pull requests merged in 2020-05, with the labels that each got.

#3753 Update JavaRosa to v2.17.1
  collect_app/build.gradle
Labels: behavior verified

#3765 Friendly error message when submissions closed.
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java
Labels: behavior verified

#3743 Improved QRCode design
  collect_app/build.gradle
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/settings/QrCodeTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/preferences/qr/ConfigureWithQRCodeTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/MainMenuPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/QRCodeTabsActivityPage.java
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/ScanQRCodeActivity.java
  collect_app/src/main/java/org/odk/collect/android/analytics/AnalyticsEvents.java
  collect_app/src/main/java/org/odk/collect/android/fragments/ShowQRCodeFragment.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/preferences/AdminPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/qr/ObservableQRCodeGenerator.java
  collect_app/src/main/java/org/odk/collect/android/preferences/qr/QRCodeGenerator.java
  collect_app/src/main/java/org/odk/collect/android/preferences/qr/QRCodeTabsActivity.java
  collect_app/src/main/java/org/odk/collect/android/preferences/qr/QRCodeTabsAdapter.java
  collect_app/src/main/java/org/odk/collect/android/preferences/qr/QRScannerFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/qr/ShowQRCodeFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/utilities/SettingsUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/QRCodeUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/SharedPreferencesUtils.java
  collect_app/src/main/res/layout/fragment_scan.xml
  collect_app/src/main/res/layout/qrcode_tab.xml
  collect_app/src/main/res/layout/show_qrcode_fragment.xml
  collect_app/src/main/res/menu/settings_menu.xml
  collect_app/src/main/res/values-ar/strings.xml
  collect_app/src/main/res/values-ca/strings.xml
  collect_app/src/main/res/values-cs/strings.xml
  collect_app/src/main/res/values-de/strings.xml
  collect_app/src/main/res/values-es/strings.xml
  collect_app/src/main/res/values-fa/strings.xml
  collect_app/src/main/res/values-fi/strings.xml
  collect_app/src/main/res/values-fr/strings.xml
  collect_app/src/main/res/values-hi/strings.xml
  collect_app/src/main/res/values-in/strings.xml
  collect_app/src/main/res/values-it/strings.xml
  collect_app/src/main/res/values-ja/strings.xml
  collect_app/src/main/res/values-km/strings.xml
  collect_app/src/main/res/values-mr/strings.xml
  collect_app/src/main/res/values-ne-rNP/strings.xml
  collect_app/src/main/res/values-pl/strings.xml
  collect_app/src/main/res/values-pt/strings.xml
  collect_app/src/main/res/values-ru/strings.xml
  collect_app/src/main/res/values-sq/strings.xml
  collect_app/src/main/res/values-sr/strings.xml
  collect_app/src/main/res/values-sv-rSE/strings.xml
  collect_app/src/main/res/values-sw/strings.xml
  collect_app/src/main/res/values-te/strings.xml
  collect_app/src/main/res/values-uk/strings.xml
  collect_app/src/main/res/values-ur/strings.xml
  collect_app/src/main/res/values/strings.xml
  collect_app/src/test/java/org/odk/collect/android/activities/MainMenuActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/utilities/QRCodeUtilsTest.java
Labels: behavior verified

#3778 Provide submission summary when tapping a submission on the form map
  collect_app/src/main/java/org/odk/collect/android/activities/FormMapActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/FormMapViewModel.java
  collect_app/src/main/java/org/odk/collect/android/adapters/FileArrayAdapter.java
  collect_app/src/main/java/org/odk/collect/android/adapters/InstanceListCursorAdapter.java
  collect_app/src/main/java/org/odk/collect/android/adapters/InstanceUploaderAdapter.java
  collect_app/src/main/java/org/odk/collect/android/utilities/IconUtils.java
  collect_app/src/main/res/drawable/form_state_blank_circle.xml
  collect_app/src/main/res/drawable/form_state_finalized.xml
  collect_app/src/main/res/drawable/form_state_finalized_circle.xml
  collect_app/src/main/res/drawable/form_state_saved.xml
  collect_app/src/main/res/drawable/form_state_saved_circle.xml
  collect_app/src/main/res/drawable/form_state_submission_failed.xml
  collect_app/src/main/res/drawable/form_state_submission_failed_circle.xml
  collect_app/src/main/res/drawable/form_state_submited.xml
  collect_app/src/main/res/drawable/form_state_submitted_circle.xml
  collect_app/src/main/res/drawable/ic_edit.xml
  collect_app/src/main/res/drawable/ic_visibility.xml
  collect_app/src/main/res/layout/form_chooser_list_item_icon.xml
  collect_app/src/main/res/layout/instance_map_layout.xml
  collect_app/src/main/res/layout/submission_summary_layout.xml
  collect_app/src/test/java/org/odk/collect/android/activities/FormMapActivityTest.java
  collect_app/src/test/java/org/odk/collect/android/activities/FormMapViewModelTest.java
Labels: behavior verified

#3779 Add Material Banner implementation
  collect_app/build.gradle
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/MainMenuPage.java
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/audit/ChangesReasonPromptDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/formentry/audit/IdentifyUserPromptDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/storage/migration/StorageMigrationDialog.java
  collect_app/src/main/res/layout/main_menu.xml
  collect_app/src/main/res/layout/storage_migration_banner.xml
  collect_app/src/test/java/org/odk/collect/android/support/RobolectricHelpers.java
  material/.gitignore
  material/README.md
  material/build.gradle
  material/consumer-rules.pro
  material/proguard-rules.pro
  material/src/debug/res/layout/material_banner_attr_test.xml
  material/src/main/AndroidManifest.xml
  material/src/main/java/org/odk/collect/material/ContextUtils.java
  material/src/main/java/org/odk/collect/material/MaterialBanner.java
  material/src/main/java/org/odk/collect/material/MaterialFullScreenDialogFragment.java
  material/src/main/res/layout/material_banner.xml
  material/src/main/res/values/attrs.xml
  material/src/main/res/values/material_full_screen_dialog_theme.xml
  material/src/test/java/org/odk/collect/material/MaterialBannerTest.java
  settings.gradle
Labels: behavior verified

#2925 Enable strict mode for DEBUG builds to detect unclosed cursor/stream
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
  collect_app/src/main/java/org/odk/collect/android/utilities/CompressionUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormDefCache.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormListDownloader.java
Labels: needs testing

#3837 Fix app crashing during form load
  build.gradle
  collect_app/build.gradle
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/ProgressDialogFragment.java
Labels: behavior verified, high priority

#3835 Fixed scanning inverted QRCodes and refactored the way we scan codes
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/ScannerWithFlashlightActivity.java
  collect_app/src/main/java/org/odk/collect/android/fragments/BarcodeWidgetScannerFragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/BaseCodeScannerFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/qr/QRCodeScannerFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/qr/QRCodeTabsAdapter.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java
  collect_app/src/main/res/layout/activity_custom_scanner.xml
  collect_app/src/main/res/layout/custom_barcode_scanner.xml
  collect_app/src/main/res/layout/fragment_scan.xml
Labels: behavior verified

#3840 Fixed not tappable map area
  collect_app/src/main/res/layout/instance_map_layout.xml
Labels: behavior verified

#3845 Prevent crash when adding repeat from hierarchy
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
Labels: behavior verified, high priority

#3853 Don't try to initialize mapbox every time the main menu is displayed
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/java/org/odk/collect/android/preferences/GeneralKeys.java
Labels: behavior verified

#3871 Replace Open Data Kit with ODK
  collect_app/src/main/res/values/strings.xml
Labels: high priority

#3869 Check for null map field
  collect_app/src/main/java/org/odk/collect/android/activities/GeoPolyActivity.java
Labels: behavior verified, high priority

#3880 Don't allow clicking on symbols/lines if the clicklistener is not set (in GeoWidgets)
  collect_app/src/main/java/org/odk/collect/android/geo/MapboxMapFragment.java
Labels: behavior verified, high priority

#3876 Fixed camera permission required when opening QR code configuration screen
  collect_app/src/main/java/org/odk/collect/android/fragments/BaseCodeScannerFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/qr/QRCodeTabsActivity.java
Labels: behavior verified, high priority
