Repository getodk/collect, pull requests merged in 2021-10, with the labels that each got.

#4833 Updated icons in the 'About' screen
  collect_app/src/androidTest/java/org/odk/collect/android/regression/AboutPageTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/AboutActivity.java
  collect_app/src/main/res/drawable/ic_forum.xml
  collect_app/src/main/res/drawable/ic_outline_forum_24.xml
  collect_app/src/main/res/drawable/ic_outline_rate_review_24.xml
  collect_app/src/main/res/drawable/ic_outline_share_24.xml
  collect_app/src/main/res/drawable/ic_outline_stars_24.xml
  collect_app/src/main/res/drawable/ic_outline_website_24.xml
  collect_app/src/main/res/drawable/ic_review_rate.xml
  collect_app/src/main/res/drawable/ic_share.xml
  collect_app/src/main/res/drawable/ic_stars.xml
  collect_app/src/main/res/drawable/ic_website.xml
  collect_app/src/main/res/layout/about_item_layout.xml
Labels: behavior verified

#4837 Bump target version to API 30
  androidshared/src/main/java/org/odk/collect/androidshared/utils/ToastUtils.kt
  buildSrc/src/main/java/dependencies/Versions.kt
  download-robolectric-deps.sh
Labels: needs testing

#4830 Improved showing errors that might occur during downloading forms
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/DeleteBlankFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/GetBlankFormsTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/SwitchProjectTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ServerSettingsTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/smoke/BadServerTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/smoke/GetAndSubmitFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormsDownloadErrorPage.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormsDownloadResultPage.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/GetBlankFormPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.java
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java
  collect_app/src/main/java/org/odk/collect/android/errors/ErrorActivity.kt
  collect_app/src/main/java/org/odk/collect/android/errors/ErrorAdapter.kt
  collect_app/src/main/java/org/odk/collect/android/errors/ErrorItem.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/FormDownloadExceptionMapper.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/FormSourceExceptionMapper.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDetails.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDetails.kt
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/FormsDownloadResultDialog.kt
  collect_app/src/main/res/layout/activity_error.xml
  collect_app/src/main/res/layout/error_item.xml
  collect_app/src/test/java/org/odk/collect/android/fragments/dialogs/FormsDownloadResultDialogTest.kt
  forms/src/main/java/org/odk/collect/forms/ManifestFile.kt
  forms/src/main/java/org/odk/collect/forms/MediaFile.kt
  strings/src/main/res/values/strings.xml
Labels: behavior verified

#4849 Update test to use translations
  collect_app/src/androidTest/java/org/odk/collect/android/feature/smoke/BadServerTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/CollectTestRule.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/TranslatedStringBuilder.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.java
Labels: high priority

#4762 Show repeat in hierarchy view even if first instance has no relevant content
  collect_app/src/androidTest/assets/forms/Empty First Repeat.xml
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormHierarchyTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
Labels: behavior verified
