Repository getodk/collect, pull requests merged in 2021-01, with the labels that each got.

#4333 Make sure form is created in correct place during download
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDownloader.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormDownloaderTest.java
  collect_app/src/test/java/org/odk/collect/android/forms/FormsRepositoryTest.java
  collect_app/src/test/java/org/odk/collect/android/support/FormUtils.java
  collect_app/src/test/java/org/odk/collect/android/support/InMemFormsRepository.java
Labels: behavior verified, high priority

#4334 Clean up ReferenceManager if form can't be parsed
  collect_app/src/main/java/org/odk/collect/android/formmanagement/FormMetadataParser.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDownloader.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/FormMetadataParserTest.java
  config/pmd-ruleset.xml
Labels: behavior verified, high priority

#4331 Upgrade to new version of AudioRecordView with bug fix
  collect_app/build.gradle
  collect_app/src/main/java/org/odk/collect/android/audio/Waveform.java
Labels: behavior verified

#4286 Handle process death during filling a form
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/FormController.java
Labels: behavior verified

#4309 Removed redundant ChangingDatabasesByForksTest
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/database/ChangingDatabasesByForksTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/database/helpers/InstancesDatabaseHelperTest.java
  collect_app/src/main/java/org/odk/collect/android/database/DatabaseConstants.java
  collect_app/src/main/java/org/odk/collect/android/database/DatabaseMigrator.java
  collect_app/src/main/java/org/odk/collect/android/database/FormDatabaseMigrator.java
  collect_app/src/main/java/org/odk/collect/android/database/FormsDatabaseHelper.java
  collect_app/src/main/java/org/odk/collect/android/database/InstanceDatabaseMigrator.java
  collect_app/src/main/java/org/odk/collect/android/database/InstancesDatabaseHelper.java
  collect_app/src/main/java/org/odk/collect/android/provider/FormsProvider.java
  collect_app/src/main/java/org/odk/collect/android/provider/InstanceProvider.java
Labels: behavior verified

#4321 Catch ExternalDataException and display as a warning
  collect_app/src/main/java/org/odk/collect/android/widgets/items/ItemsWidget.java
Labels: behavior verified

#4270 Fix building select widgets
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/ListMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/ListWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectImageMapWidget.java
  collect_app/src/test/java/org/odk/collect/android/widgets/WidgetFactoryTest.java
Labels: behavior verified

#4339 Log server and parse errors during Match Exactly sync
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/GetBlankFormsTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java
  collect_app/src/main/java/org/odk/collect/android/analytics/AnalyticsUtils.java
  collect_app/src/main/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpec.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/BlankFormsListViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/FormSourceExceptionMapper.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDetails.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDownloader.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormsDetailsFetcher.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/matchexactly/ServerFormsSynchronizer.java
  collect_app/src/main/java/org/odk/collect/android/forms/FormSourceException.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/openrosa/HttpGetResult.java
  collect_app/src/main/java/org/odk/collect/android/openrosa/OpenRosaFormSource.java
  collect_app/src/main/java/org/odk/collect/android/openrosa/OpenRosaResponseParser.java
  collect_app/src/main/java/org/odk/collect/android/openrosa/OpenRosaResponseParserImpl.java
  collect_app/src/main/java/org/odk/collect/android/openrosa/OpenRosaXmlFetcher.java
  collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoUpdateTaskSpecTest.java
  collect_app/src/test/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpecTest.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/BlankFormsListViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/FormSourceExceptionMapperTest.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormDownloaderTest.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormsSynchronizerTest.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/SyncStatusRepositoryTest.java
  collect_app/src/test/java/org/odk/collect/android/notifications/NotificationManagerNotifierTest.java
  collect_app/src/test/java/org/odk/collect/android/openrosa/OpenRosaXmlFetcherTest.java
  collect_app/src/test/java/org/odk/collect/android/openrosa/api/OpenRosaFormSourceTest.java
  strings/src/main/res/values/strings.xml
Labels: behavior verified

#4357 Make sure redownloading the same form doesn't break anything
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDownloader.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormDownloaderTest.java
Labels: behavior verified, high priority

#4350 Allow other appearances to combine with field-list
  collect_app/src/main/java/org/odk/collect/android/adapters/AbstractSelectListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/formentry/media/PromptAutoplayer.java
  collect_app/src/main/java/org/odk/collect/android/fragments/BarCodeScannerFragment.java
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/FormController.java
  collect_app/src/main/java/org/odk/collect/android/utilities/Appearances.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormEntryPromptUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/BaseSelectListWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectMultiMinimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneMinimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/ActivityGeoDataRequester.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/DateTimeWidgetUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/StringWidgetUtils.java
  collect_app/src/test/java/org/odk/collect/android/javarosawrapper/FormControllerTest.java
  collect_app/src/test/java/org/odk/collect/android/utilities/AppearancesTest.java
  collect_app/src/test/java/org/odk/collect/android/views/ChoicesRecyclerViewTest.java
  collect_app/src/test/java/org/odk/collect/android/views/helpers/PromptAutoplayerTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/AudioWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/BarcodeWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/DecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExDecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExIntegerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/IntegerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/StringNumberWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectMultiWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectOneWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/utilities/ActivityGeoDataRequesterTest.java
Labels: behavior verified

#4365 Workaround paused recording Android bug
  audiorecorder/build.gradle
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/DaggerSetup.kt
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/mediarecorder/MediaRecorderRecordingResource.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/mediarecorder/AMRRecordingResourceTest.kt
Labels: high priority, needs testing

#4372 Stop pause/resume button causing multiclick problems
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recording/internal/AudioRecorderService.kt
  audiorecorder/src/test/java/org/odk/collect/audiorecorder/recording/internal/AudioRecorderServiceTest.kt
Labels: behavior verified
