Repository getodk/collect, pull requests merged in 2021-12, with the labels that each got.

#4897 Fixes #4480 Text added in angle brackets …
  collect_app/src/main/java/org/odk/collect/android/adapters/HierarchyListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/adapters/HierarchyListItemView.kt
  collect_app/src/main/res/layout/hierarchy_element.xml
  collect_app/src/test/java/org/odk/collect/android/adapters/HierarchyListItemViewTest.kt
Labels: behavior verified

#4922 Make internal recorder the default
  androidshared/src/main/res/layout/app_bar_layout.xml
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/AudioRecordingTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/ExternalAudioRecordingTest.java
  collect_app/src/main/java/org/odk/collect/android/preferences/keys/ProjectKeys.kt
  collect_app/src/main/res/layout/audio_recording_controller_fragment.xml
  collect_app/src/main/res/layout/changes_reason_dialog.xml
  collect_app/src/main/res/layout/form_entry.xml
  collect_app/src/main/res/layout/identify_user_dialog.xml
  collect_app/src/main/res/layout/manual_project_creator_dialog_layout.xml
  collect_app/src/main/res/layout/qr_code_project_creator_dialog_layout.xml
  collect_app/src/main/res/layout/select_minimal_dialog_layout.xml
Labels: behavior verified

#4928 Mark "run once" upgrades as run on fresh install
  collect_app/src/main/java/org/odk/collect/android/application/initialization/ExistingProjectMigrator.kt
  collect_app/src/test/java/org/odk/collect/android/projects/ExistingProjectMigratorTest.kt
Labels: high priority, behavior verified

#4932 Use localized strings in `DownloadFormsTask`
  collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormsTask.java
Labels: high priority, behavior verified

#4938 Prevent crashes when clicking Save Geopoint early
  geo/src/main/java/org/odk/collect/geo/GeoPointActivity.java
  geo/src/test/java/org/odk/collect/geo/GeoPointActivityTest.java
Labels: high priority, behavior verified

#4917 Fixed: EDIT action for forms will crash if there are no projects
  collect_app/src/androidTest/java/org/odk/collect/android/feature/external/FormEditActionTest.kt
  collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt
  collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt
  strings/src/main/res/values/strings.xml
Labels: behavior verified

#4944 Fix class reference
  collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt
Labels: high priority
