Repository getodk/collect, pull requests merged in 2022-01, with the labels that each got.

#4918 Make landing screen layout more robust to different button text lengths
  androidshared/src/main/java/org/odk/collect/androidshared/ui/GroupClickListener.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FirstLaunchActivity.kt
  collect_app/src/main/res/layout/first_launch_layout.xml
Labels: behavior verified

#4914 Use MaterialAlertDialogBuilder instead of AlertDialog.Builder across the app
  androidshared/src/main/java/org/odk/collect/androidshared/ui/ColorPickerDialog.kt
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/DrawActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderListActivity.java
  collect_app/src/main/java/org/odk/collect/android/audio/AudioRecordingErrorDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/audio/BackgroundAudioHelpDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/configure/qr/ShowQRCodeFragment.java
  collect_app/src/main/java/org/odk/collect/android/external/AndroidShortcutsActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/BackgroundAudioPermissionDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryMenuDelegate.java
  collect_app/src/main/java/org/odk/collect/android/formentry/QuitFormDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/formentry/RecordingWarningDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/formentry/repeats/AddRepeatDialog.java
  collect_app/src/main/java/org/odk/collect/android/formentry/repeats/DeleteRepeatDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/SaveAnswerFileErrorDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/BlankFormListFragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/SavedFormListFragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/CustomDatePickerDialog.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/ErrorDialog.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/LocationProvidersDisabledDialog.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/MovingBackwardsDialog.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/NumberPickerDialog.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/ProgressDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/RankingWidgetDialog.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/ResetSettingsResultDialog.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/SimpleDialog.java
  collect_app/src/main/java/org/odk/collect/android/gdrive/GoogleAccountNotSetDialog.java
  collect_app/src/main/java/org/odk/collect/android/gdrive/GoogleDriveActivity.java
  collect_app/src/main/java/org/odk/collect/android/gdrive/GoogleSheetsUploaderActivity.java
  collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/geo/OsmDroidMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/SplashClickListener.java
  collect_app/src/main/java/org/odk/collect/android/preferences/dialogs/AdminPasswordDialogFragment.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/dialogs/ChangeAdminPasswordDialog.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/dialogs/ServerAuthDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/ProjectManagementPreferencesFragment.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/ServerPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/utilities/AuthDialogUtility.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExAudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/OSMWidget.java
  collect_app/src/main/res/values/theme.xml
  geo/src/main/java/org/odk/collect/geo/GeoPolyActivity.java
  geo/src/main/java/org/odk/collect/geo/GeoPolySettingsDialogFragment.java
  geo/src/test/java/org/odk/collect/geo/GeoPolySettingsDialogFragmentTest.java
Labels: needs testing

#4664 Don't rotate images for display, instead preserve and use EXIF tag
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/BitmapScaledToDisplayTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ImageConverterTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ImageFileUtilsTest.kt
  collect_app/src/main/java/org/odk/collect/android/activities/DrawActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/viewmodels/SplashScreenViewModel.kt
  collect_app/src/main/java/org/odk/collect/android/configure/qr/CachingQRCodeGenerator.java
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/questions/WidgetViewUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ImageFileUtils.kt
  collect_app/src/main/java/org/odk/collect/android/views/DrawView.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/LabelWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/LikertWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/ListMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/ListWidget.java
  collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/DrawWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ImageWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/SignatureWidgetTest.java
Labels: behavior verified

#4936 Stop using localized strings in `DownloadFormsTask`
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/GetBlankFormsTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/smoke/GetAndSubmitFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/notifications/FormUpdatesDownloadedNotificationTest.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/FormUpdateDownloader.kt
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/FormsDownloadResultDialog.kt
  collect_app/src/main/java/org/odk/collect/android/listeners/DownloadFormsTaskListener.java
  collect_app/src/main/java/org/odk/collect/android/notifications/NotificationManagerNotifier.kt
  collect_app/src/main/java/org/odk/collect/android/notifications/Notifier.kt
  collect_app/src/main/java/org/odk/collect/android/notifications/builders/FormUpdatesDownloadedNotificationBuilder.kt
  collect_app/src/main/java/org/odk/collect/android/tasks/DownloadFormsTask.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormsDownloadResultInterpreter.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/FormUpdateDownloaderTest.kt
  collect_app/src/test/java/org/odk/collect/android/fragments/dialogs/FormsDownloadResultDialogTest.kt
  collect_app/src/test/java/org/odk/collect/android/utilities/FormsDownloadResultInterpreterTest.kt
Labels: behavior verified

#4969 Fix JCenter dependencies
  build.gradle
  buildSrc/src/main/java/dependencies/Dependencies.kt
  jcenter-local-m2/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.aar
  jcenter-local-m2/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom
  jcenter-local-m2/com/mapbox/mapboxsdk/mapbox-android-accounts/maven-metadata-local.xml
Labels: high priority

#4975 Make unacceptable accuracy threshold configurable
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ChangesReasonPromptPage.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormEntryPromptUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/ActivityGeoDataRequester.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/ActivityGeoDataRequester.kt
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/GeoWidgetUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/InternalRecordingRequester.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/RecordingRequesterProvider.java
  collect_app/src/test/java/org/odk/collect/android/widgets/utilities/ActivityGeoDataRequesterTest.java
  geo/src/main/java/org/odk/collect/geo/AccuracyStatusView.kt
  geo/src/main/java/org/odk/collect/geo/GeoPointAccuracy.kt
  geo/src/main/java/org/odk/collect/geo/GeoPointActivity.kt
  geo/src/main/java/org/odk/collect/geo/GeoPointDialogFragment.kt
  geo/src/main/java/org/odk/collect/geo/GeoPointViewModel.kt
  geo/src/test/java/org/odk/collect/geo/AccuracyStatusViewTest.kt
  geo/src/test/java/org/odk/collect/geo/GeoPointActivityTest.kt
  geo/src/test/java/org/odk/collect/geo/GeoPointDialogFragmentTest.kt
  geo/src/test/java/org/odk/collect/geo/LocationTrackerGeoPointViewModelTest.kt
Labels: needs testing

#4990 Prompt user to enable Location if not enabled
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormHierarchyPage.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/ActivityGeoDataRequester.kt
  permissions/src/main/java/org/odk/collect/permissions/PermissionsProvider.kt
Labels: behavior verified

#4980 Fixed the 'Reset app' dialog
  collect_app/src/main/java/org/odk/collect/android/preferences/dialogs/ResetDialogPreferenceFragmentCompat.java
  collect_app/src/main/java/org/odk/collect/android/preferences/dialogs/ResetProgressDialog.kt
  collect_app/src/test/java/org/odk/collect/android/preferences/dialogs/ResetProgressDialogTest.kt
Labels: behavior verified

#4986 Fix location tracking notification
  collect_app/src/main/java/org/odk/collect/android/notifications/builders/FormUpdatesAvailableNotificationBuilder.kt
  collect_app/src/main/java/org/odk/collect/android/notifications/builders/FormUpdatesDownloadedNotificationBuilder.kt
  collect_app/src/main/java/org/odk/collect/android/notifications/builders/FormsSubmissionNotificationBuilder.kt
  collect_app/src/main/java/org/odk/collect/android/notifications/builders/FormsSyncFailedNotificationBuilder.kt
  collect_app/src/main/java/org/odk/collect/android/utilities/IconUtils.java
  location/src/main/java/org/odk/collect/location/tracker/ForegroundServiceLocationTracker.kt
  location/src/main/res/drawable/ic_notification_small.xml
Labels: behavior verified

#4991 Implement Serializable in classes we serialize
  forms/src/main/java/org/odk/collect/forms/ManifestFile.kt
  forms/src/main/java/org/odk/collect/forms/MediaFile.kt
Labels: behavior verified
