Repository getodk/collect, pull requests merged in 2022-06, with the labels that each got.

#5149 Fixed duplicate forms
  collect_app/src/main/java/org/odk/collect/android/application/CollectSettingsChangeHandler.java
  collect_app/src/main/java/org/odk/collect/android/application/CollectSettingsChangeHandler.kt
  collect_app/src/main/java/org/odk/collect/android/database/DatabaseConstants.java
  collect_app/src/main/java/org/odk/collect/android/database/forms/DatabaseFormsRepository.java
  collect_app/src/main/java/org/odk/collect/android/database/forms/FormDatabaseMigrator.java
  collect_app/src/test/java/org/odk/collect/android/application/CollectSettingsChangeHandlerTest.java
  collect_app/src/test/java/org/odk/collect/android/application/CollectSettingsChangeHandlerTest.kt
  collect_app/src/test/java/org/odk/collect/android/database/FormDatabaseMigratorTest.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/FormDeleterTest.java
  formstest/src/main/java/org/odk/collect/formstest/FormUtils.java
  formstest/src/main/java/org/odk/collect/formstest/FormUtils.kt
  formstest/src/main/java/org/odk/collect/formstest/FormsRepositoryTest.java
  formstest/src/main/java/org/odk/collect/formstest/InMemFormsRepository.java
  formstest/src/main/java/org/odk/collect/formstest/InstanceUtils.java
  formstest/src/main/java/org/odk/collect/formstest/InstanceUtils.kt
  settings/src/main/java/org/odk/collect/settings/importing/SettingsImporter.kt
  settings/src/test/java/org/odk/collect/settings/ODKAppSettingsImporterTest.kt
  settings/src/test/java/org/odk/collect/settings/importing/SettingsImporterTest.kt
Labels: high priority, behavior verified

#5150 Add WRITE_EXTERNAL_STORAGE permission to fix problems with accessing storage
  collect_app/src/main/AndroidManifest.xml
Labels: high priority, behavior verified

#5158 Allow starting apps by package name on newer devices
  collect_app/src/main/AndroidManifest.xml
Labels: high priority, behavior verified

#5160 Support styling likert widget
  collect_app/src/androidTest/assets/forms/form_styling.xml
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormStylingTest.kt
  collect_app/src/main/java/org/odk/collect/android/widgets/items/LikertWidget.java
Labels: needs testing

#5155 Upgrade JavaRosa
  buildSrc/src/main/java/dependencies/Dependencies.kt
Labels: behavior verified

#5156 Fixed the dialog displayed when permission is denied
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeTabsActivity.java
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeTabsActivity.kt
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeTabsAdapter.java
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeTabsAdapter.kt
  permissions/src/main/java/org/odk/collect/permissions/PermissionDeniedDialog.kt
  permissions/src/main/java/org/odk/collect/permissions/PermissionsProvider.kt
  permissions/src/test/java/org/odk/collect/permissions/PermissionDeniedDialogTest.kt
Labels: behavior verified
