Repository getodk/collect, pull requests merged in 2022-08, with the labels that each got.

#5235 Stop early swipes causes crashes
  collect_app/src/main/java/org/odk/collect/android/listeners/SwipeHandler.java
Labels: high priority, behavior verified

#5237 Fall back to first project when no current project set
  collect_app/src/main/java/org/odk/collect/android/projects/CurrentProjectProvider.kt
  collect_app/src/test/java/org/odk/collect/android/projects/CurrentProjectProviderTest.kt
Labels: high priority, behavior verified

#5238 Fixed adding offline layers
  mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt
Labels: high priority, needs testing

#5250 Fix audit log event ordering
  collect_app/src/androidTest/assets/forms/location-audit.xml
  collect_app/src/androidTest/assets/forms/one-question-audit.xml
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/IdentifyUserTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/backgroundlocation/LocationAuditTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/backgroundlocation/LocationTrackingAuditTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/FormsAdbTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/PreviouslyDownloadedOnlyTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/forms/FormNavigationTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/tasks/FormLoaderTaskTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/FakeLocationClient.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/StorageUtils.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/WaitFor.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/IdentifyUserPromptPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/rules/FormActivityTestRule.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/backgroundlocation/BackgroundLocationViewModel.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  testshared/src/main/java/org/odk/collect/testshared/LocationTestUtils.kt
Labels: high priority, behavior verified

#5258 Cache BitmapDescriptor
  collect_app/src/main/java/org/odk/collect/android/geo/BitmapDescriptorCache.kt
  collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java
Labels: high priority, behavior verified

#5259 Prevent `ConcurrentModificationException` when logging or flushing the `AuditEventLogger`
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/audit/AuditEventLogger.java
Labels: high priority, behavior verified

#5182 Use the same icon in all notifications
  androidshared/build.gradle
  audiorecorder/build.gradle
  audiorecorder/src/main/java/org/odk/collect/audiorecorder/recording/internal/RecordingForegroundServiceNotification.kt
  collect_app/build.gradle
  geo/build.gradle
  icons/.gitignore
  icons/build.gradle
  icons/src/main/AndroidManifest.xml
  icons/src/main/res/drawable/ic_close_black_24dp.xml
  icons/src/main/res/drawable/ic_map_point.xml
  icons/src/main/res/drawable/ic_notification_small.xml
  icons/src/main/res/values/map_colors.xml
  location/build.gradle
  mapbox/build.gradle
  osmdroid/build.gradle
  settings.gradle
Labels: behavior verified

#5239 Make sure the value used in range widget is between rangeStart and rangeEnd
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/RangeWidgetUtils.java
  collect_app/src/test/java/org/odk/collect/android/widgets/utilities/RangeWidgetUtilsTest.java
Labels: behavior verified

#5269 Display newest forms by date
  collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/BlankFormListViewModel.kt
  collect_app/src/test/java/org/odk/collect/android/formlists/blankformlist/BlankFormListViewModelTest.kt
Labels: behavior verified
