Repository getodk/collect, pull requests merged in 2022-07, with the labels that each got.

#5154 Protect the app from importing keys and values that are not supported according to the json scheme
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/projects/ProjectCreator.kt
  collect_app/src/main/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialog.kt
  collect_app/src/test/java/org/odk/collect/android/projects/ManualProjectCreatorDialogTest.kt
  collect_app/src/test/java/org/odk/collect/android/projects/ProjectCreatorTest.kt
  collect_app/src/test/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialogTest.kt
  settings/src/main/java/org/odk/collect/settings/ODKAppSettingsImporter.kt
  settings/src/main/java/org/odk/collect/settings/importing/ProjectDetailsCreatorImpl.kt
  settings/src/main/java/org/odk/collect/settings/importing/SettingsImporter.kt
  settings/src/main/java/org/odk/collect/settings/validation/JsonSchemaSettingsValidator.kt
  settings/src/test/java/org/odk/collect/settings/ODKAppSettingsImporterTest.kt
  settings/src/test/java/org/odk/collect/settings/importing/ProjectDetailsCreatorImplTest.kt
  settings/src/test/java/org/odk/collect/settings/importing/SettingsImporterTest.kt
  settings/src/test/java/org/odk/collect/settings/validation/JsonSchemaSettingsValidatorTest.kt
Labels: behavior verified

#5164 Selection map cleanup
  androidshared/src/main/java/org/odk/collect/androidshared/ui/FragmentFactoryBuilder.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/maps/FormMapTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/FakeClickableMapFragment.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormMapPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/rules/ResetStateRule.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/rules/RetryOnDeviceErrorRule.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/formmap/FormMapViewModel.kt
  collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/geo/MapFragmentFactoryImpl.kt
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneFromMapDialogFragment.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/formmap/FormMapViewModelTest.kt
  collect_app/src/test/java/org/odk/collect/android/geo/TestMapFragment.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectChoicesMapDataTest.kt
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectOneFromMapDialogFragmentTest.kt
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectOneFromMapWidgetTest.kt
  collect_app/src/test/java/org/odk/collect/android/widgets/support/NoOpMapFragment.kt
  geo/src/main/java/org/odk/collect/geo/geopoint/GeoPointMapActivity.java
  geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyActivity.java
  geo/src/main/java/org/odk/collect/geo/selection/SelectionMapFragment.kt
  geo/src/main/res/layout/geopoint_layout.xml
  geo/src/main/res/layout/geopoly_layout.xml
  geo/src/main/res/layout/selection_map_layout.xml
  geo/src/test/java/org/odk/collect/geo/geopoint/GeoPointMapActivityTest.java
  geo/src/test/java/org/odk/collect/geo/geopoly/GeoPolyActivityTest.java
  geo/src/test/java/org/odk/collect/geo/selection/SelectionMapFragmentTest.kt
  geo/src/test/java/org/odk/collect/geo/support/FakeMapFragment.kt
  mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt
  maps/src/main/java/org/odk/collect/maps/MapFragment.java
  maps/src/main/java/org/odk/collect/maps/MapFragmentDelegate.kt
  maps/src/main/java/org/odk/collect/maps/MapFragmentFactory.kt
  material/src/main/java/org/odk/collect/material/BottomSheetBehavior.kt
  osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java
Labels: behavior verified

#5162 Add loading state when saving screen answers
  androidshared/src/main/java/org/odk/collect/androidshared/ui/Animations.kt
  collect_app/src/androidTest/assets/forms/two-question-required.xml
  collect_app/src/androidTest/assets/forms/two-question-save-incomplete-required.xml
  collect_app/src/androidTest/assets/forms/two-question-save-incomplete.xml
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/ContextMenuTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FieldListUpdateTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/QuickSaveTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/QuittingFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/SaveIncompleteTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/SwitchProjectTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormHierarchyPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ProjectSettingsDialogPage.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/rules/ResetStateRule.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryMenuDelegate.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormIndexAnimationHandler.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormIndexAnimationHandler.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/FormController.java
  collect_app/src/main/java/org/odk/collect/android/preferences/source/SharedPreferencesSettingsProvider.kt
  collect_app/src/main/java/org/odk/collect/android/views/TransparentProgressScreen.kt
  collect_app/src/main/res/layout/form_entry.xml
  collect_app/src/main/res/layout/transparent_progress_screen.xml
  collect_app/src/test/java/org/odk/collect/android/audio/AudioRecordingControllerFragmentTest.java
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryMenuDelegateTest.java
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectOneFromMapDialogFragmentTest.kt
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectOneFromMapWidgetTest.kt
  settings/src/main/java/org/odk/collect/settings/InMemSettingsProvider.kt
  settings/src/main/java/org/odk/collect/settings/SettingsProvider.kt
Labels: behavior verified

#5188 Selection summary redesign
  geo/src/main/java/org/odk/collect/geo/selection/SelectionMapFragment.kt
  geo/src/main/java/org/odk/collect/geo/selection/SelectionSummarySheet.kt
  geo/src/main/res/drawable/property_divider.xml
  geo/src/main/res/layout/property.xml
  geo/src/main/res/layout/selection_map_layout.xml
  geo/src/main/res/layout/selection_summary_sheet_layout.xml
  material/src/main/java/org/odk/collect/material/BottomSheetBehavior.kt
Labels: needs testing

#5204 Fixed sorting forms by name
  collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/BlankFormListViewModel.kt
  collect_app/src/test/java/org/odk/collect/android/formlists/blankformlist/BlankFormListViewModelTest.kt
Labels: behavior verified

#5194 Fix checking supported abis
  collect_app/src/main/java/org/odk/collect/android/application/MapboxClassInstanceCreator.kt
Labels: high priority, behavior verified

#5205 Removed unused code from DeleteSavedFormActivity
  collect_app/src/main/java/org/odk/collect/android/activities/DeleteSavedFormActivity.kt
Labels: behavior verified

#5197 Fixed setting formController objects in view models
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
Labels: behavior verified

#5206 Add markers all at once in Mapbox
  README.md
  collect_app/build.gradle
  collect_app/src/androidTest/java/org/odk/collect/android/support/FakeClickableMapFragment.kt
  collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java
  collect_app/src/test/java/org/odk/collect/android/widgets/support/NoOpMapFragment.kt
  geo/src/main/java/org/odk/collect/geo/selection/SelectionMapFragment.kt
  geo/src/test/java/org/odk/collect/geo/support/FakeMapFragment.kt
  mapbox/src/main/java/org/odk/collect/mapbox/MapUtils.kt
  mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt
  mapbox/src/main/java/org/odk/collect/mapbox/MarkerFeature.kt
  maps/src/main/java/org/odk/collect/maps/MapFragment.java
  osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java
Labels: behavior verified

#5207 Fix recording points stopping on rotate for geotrace/geoshape
  location/src/main/java/org/odk/collect/location/tracker/ForegroundServiceLocationTracker.kt
Labels: behavior verified

#5219 Retain accuracy for marker point in Mapbox
  mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt
Labels: high priority, behavior verified

#5221 Set up click listeners for OSM properly
  osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java
Labels: high priority, behavior verified

#5225 Fixed clearing lines in OSM
  osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java
Labels: behavior verified
