Repository getodk/collect, pull requests merged in 2023-07, with the labels that each got.

#5657 Increase select checkbox touch target size in Ready to send
  collect_app/src/main/java/org/odk/collect/android/adapters/InstanceUploaderAdapter.java
  collect_app/src/main/java/org/odk/collect/android/views/TwoItemMultipleChoiceView.java
  collect_app/src/main/res/layout/form_chooser_list_item_multiple_choice.xml
Labels: high priority, behavior verified

#5653 Don't start background recording when viewing forms
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/BackgroundAudioRecordingTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryViewModelFactory.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
Labels: high priority, behavior verified

#5649 Prevent opening for review encrypted forms after finalizing
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EncryptedFormTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderListActivity.java
  collect_app/src/main/java/org/odk/collect/android/database/instances/DatabaseInstanceColumns.kt
  collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt
  collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt
  collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuViewModel.kt
  collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt
  collect_app/src/test/java/org/odk/collect/android/mainmenu/MainMenuViewModelTest.kt
  forms/src/main/java/org/odk/collect/forms/instances/Instance.java
Labels: high priority, behavior verified

#5654 Add option to validate form
  collect_app/src/androidTest/assets/forms/requiredJR275.xml
  collect_app/src/androidTest/assets/forms/requiredQuestionInFieldList.xml
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/RequiredQuestionTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEndPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryMenuDelegate.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/FailedConstraint.java
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/FormController.kt
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/ValidationResult.kt
  collect_app/src/main/java/org/odk/collect/android/tasks/SaveFormToDisk.java
  collect_app/src/main/res/menu/form_menu.xml
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/utilities/DummyFormController.kt
  strings/src/main/res/values/strings.xml
Labels: high priority, behavior verified

#5640 Fixed range widgets
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/RangeWidgetUtils.java
  collect_app/src/test/java/org/odk/collect/android/widgets/range/RangeDecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/range/RangeIntegerWidgetTest.java
Labels: needs testing

#5636 Use the same location providers in every map engine + some tweaks
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
  collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java
  geo/src/main/java/org/odk/collect/geo/geopoint/GeoPointMapActivity.java
  geo/src/test/java/org/odk/collect/geo/geopoint/GeoPointMapActivityTest.java
  location/build.gradle
  location/src/main/java/org/odk/collect/location/GoogleFusedLocationClient.java
  mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt
  osmdroid/build.gradle
  osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java
Labels: behavior verified

#5560 Form error improvements
  collect_app/build.gradle
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/CatchFormDesignExceptionsTest.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormError.kt
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryViewModelTest.java
Labels: behavior verified

#5670 Allow editing finalized forms saved before October 1st 2023 UTC
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/BackgroundAudioRecordingTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormSavedSnackbarTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/SendFinalizedFormTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/SendFinalizedFormPage.java
  collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceExt.kt
  collect_app/src/main/java/org/odk/collect/android/utilities/InstancesRepositoryProvider.kt
  collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoUpdateTaskSpecTest.kt
  collect_app/src/test/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpecTest.kt
  collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt
Labels: high priority, behavior verified

#5672 Catch runtime exceptions that might occur during form validation
  collect_app/src/androidTest/assets/forms/RepeatCount.xml
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/AddRepeatTest.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java
Labels: high priority, behavior verified

#5624 Stop using WeakReference in BaseLocationClient
  collect_app/src/androidTest/java/org/odk/collect/android/support/FakeLocationClient.java
  collect_app/src/main/java/org/odk/collect/android/formentry/backgroundlocation/BackgroundLocationManager.java
  collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java
  collect_app/src/main/java/org/odk/collect/android/location/client/MaxAccuracyWithinTimeoutLocationClientWrapper.java
  collect_app/src/test/java/org/odk/collect/android/location/client/FakeLocationClient.java
  location/src/main/java/org/odk/collect/location/AndroidLocationClient.java
  location/src/main/java/org/odk/collect/location/BaseLocationClient.kt
  location/src/main/java/org/odk/collect/location/GoogleFusedLocationClient.java
  location/src/main/java/org/odk/collect/location/LocationClient.java
  location/src/main/java/org/odk/collect/location/tracker/ForegroundServiceLocationTracker.kt
  location/src/test/java/org/odk/collect/location/AndroidLocationClientTest.java
  location/src/test/java/org/odk/collect/location/GoogleFusedLocationClientTest.java
  location/src/test/java/org/odk/collect/location/tracker/ForegroundServiceLocationTrackerTest.kt
  mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt
  osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java
Labels: behavior verified

#5674 Remove +/- buttons from OSMDroidMap
  osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java
Labels: behavior verified

#5681 Show warning when editing finalized form
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormSavedSnackbarTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/SendFinalizedFormPage.java
  collect_app/src/main/java/org/odk/collect/android/analytics/AnalyticsEvents.kt
  collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryMenuDelegate.java
  collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt
  strings/src/main/res/values/strings.xml
Labels: high priority, behavior verified
