Repository getodk/collect, pull requests merged in 2023-05, with the labels that each got.

#5568 Improved text sizing in main menu
  collect_app/src/main/res/layout/main_menu_button.xml
  collect_app/src/main/res/layout/start_new_from_button.xml
  collect_app/src/main/res/values/attrs.xml
  collect_app/src/main/res/values/styles.xml
  collect_app/src/main/res/values/theme.xml
  collect_app/src/main/res/values/typography.xml
Labels: high priority

#5569 Refine form saving language
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/BackgroundAudioRecordingTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormFinalizingTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormLanguageTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/QuittingFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/SavePointTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/TrackChangesReasonTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/AutoSendTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/FormMetadataSettingsTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/regression/DrawWidgetTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/regression/FormValidationTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/regression/SignatureWidgetTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEndPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/SaveOrDiscardFormDialog.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/SaveOrIgnoreDialog.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/SaveOrIgnoreDrawingDialog.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryViewModelFactory.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/BackgroundAudioViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEndView.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEndViewModel.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/QuitFormDialog.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/AutoSendSettingsProvider.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/FormExt.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt
  collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoSendTaskSpecTest.kt
  collect_app/src/test/java/org/odk/collect/android/formentry/BackgroundAudioViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEndViewModelTest.kt
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEndViewTest.kt
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/formentry/FormSessionRepositoryTest.kt
  collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/formentry/support/InMemFormSessionRepository.kt
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/autosend/FormExtTest.kt
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcherTest.kt
  formstest/src/main/java/org/odk/collect/formstest/FormFixtures.kt
  strings/src/main/res/values/strings.xml
Labels: high priority, needs testing

#5571 Improved styling the Form end screen
  collect_app/src/main/res/layout/form_entry_end.xml
  collect_app/src/main/res/values/attrs.xml
  collect_app/src/main/res/values/theme.xml
  strings/src/main/res/values/strings.xml
Labels: high priority

#5589 When a control in "Access control" settings is unchecked, hide that control
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormFinalizingTest.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEndView.kt
  collect_app/src/main/res/layout/form_entry_end.xml
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEndViewTest.kt
Labels: behavior verified

#5597 Fix list view heights for delete lists
  collect_app/src/main/res/layout/delete_blank_form_layout.xml
  collect_app/src/main/res/layout/file_manager_list.xml
  collect_app/src/test/java/org/odk/collect/android/formlists/DeleteBlankFormFragmentTest.kt
  testshared/build.gradle
  testshared/src/main/java/org/odk/collect/testshared/ViewActions.kt
  testshared/src/main/java/org/odk/collect/testshared/ViewMatchers.kt
Labels: behavior verified

#5598 Change button icon and label for finalized forms on form map
  collect_app/src/main/java/org/odk/collect/android/formmanagement/formmap/FormMapViewModel.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/formmap/FormMapViewModelTest.kt
Labels: behavior verified

#5591 Update the end screen warning text based on the available actions
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEndView.kt
  collect_app/src/main/res/layout/form_entry_end.xml
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEndViewTest.kt
  strings/src/main/res/values/strings.xml
Labels: behavior verified
