Repository getodk/collect, pull requests merged in 2023-03, with the labels that each got.

#5468 Removed support for selfie video widget
  collect_app/src/androidTest/assets/forms/all-widgets.xml
  collect_app/src/androidTest/java/org/odk/collect/android/feature/smoke/AllWidgetsFormTest.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
  selfie-camera/src/main/java/org/odk/collect/selfiecamera/AnalyticsEvents.kt
  selfie-camera/src/main/java/org/odk/collect/selfiecamera/Camera.kt
  selfie-camera/src/main/java/org/odk/collect/selfiecamera/CameraXCamera.kt
  selfie-camera/src/main/java/org/odk/collect/selfiecamera/CaptureSelfieActivity.kt
  selfie-camera/src/main/java/org/odk/collect/selfiecamera/DaggerSetup.kt
  selfie-camera/src/test/java/org/odk/collect/selfiecamera/CaptureSelfieActivityTest.kt
  strings/src/main/res/values-ar/strings.xml
  strings/src/main/res/values-cs/strings.xml
  strings/src/main/res/values-de/strings.xml
  strings/src/main/res/values-es/strings.xml
  strings/src/main/res/values-fa/strings.xml
  strings/src/main/res/values-fi/strings.xml
  strings/src/main/res/values-fr/strings.xml
  strings/src/main/res/values-hi/strings.xml
  strings/src/main/res/values-in/strings.xml
  strings/src/main/res/values-it/strings.xml
  strings/src/main/res/values-ja/strings.xml
  strings/src/main/res/values-km/strings.xml
  strings/src/main/res/values-ne-rNP/strings.xml
  strings/src/main/res/values-pl/strings.xml
  strings/src/main/res/values-pt/strings.xml
  strings/src/main/res/values-ru/strings.xml
  strings/src/main/res/values-rw/strings.xml
  strings/src/main/res/values-sq/strings.xml
  strings/src/main/res/values-sr/strings.xml
  strings/src/main/res/values-sv-rSE/strings.xml
  strings/src/main/res/values-sw/strings.xml
  strings/src/main/res/values-te/strings.xml
  strings/src/main/res/values-uk/strings.xml
  strings/src/main/res/values-ur/strings.xml
  strings/src/main/res/values-zh/strings.xml
  strings/src/main/res/values/strings.xml
Labels: behavior verified

#5452 Fixed using languages with country codes
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/SettingLanguageTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/MainMenuPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/UserInterfacePage.java
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/UserInterfacePreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationConstants.java
  collect_app/src/main/java/org/odk/collect/android/utilities/LocaleHelper.java
  collect_app/src/main/java/org/odk/collect/android/utilities/LocaleHelper.kt
Labels: behavior verified

#5463 Improve selecting shapes/traces
  geo/src/main/java/org/odk/collect/geo/selection/SelectionMapFragment.kt
  geo/src/test/java/org/odk/collect/geo/geopoly/GeoPolyActivityTest.java
  geo/src/test/java/org/odk/collect/geo/selection/SelectionMapFragmentTest.kt
  geo/src/test/java/org/odk/collect/geo/support/FakeMapFragment.kt
  mapbox/src/main/java/org/odk/collect/mapbox/PolyFeature.kt
Labels: behavior verified

#5433 Reworked the way we display images in ImageWidgets
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/IntentGroupTest.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DrawWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SignatureWidget.java
  collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/DrawWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ImageWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/SignatureWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/support/SynchronousImageLoader.kt
Labels: behavior verified

#5391 Combine form entry view model factories and convert QuitFormDialogFragment to simple dialog
  .circleci/test_modules.txt
  audioclips/src/main/java/org/odk/collect/audioclips/AudioClipViewModel.kt
  collect_app/build.gradle
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryViewModelFactory.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/audio/AudioRecordingControllerFragment.java
  collect_app/src/main/java/org/odk/collect/android/formentry/BackgroundAudioPermissionDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/formentry/BackgroundAudioViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/formentry/QuitFormDialog.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/QuitFormDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/formentry/backgroundlocation/BackgroundLocationViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/repeats/DeleteRepeatDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/SaveAnswerFileErrorDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/SaveFormProgressDialogFragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/SelectMinimalDialog.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneFromMapDialogFragment.kt
  collect_app/src/test/java/org/odk/collect/android/audio/AudioRecordingControllerFragmentTest.java
  collect_app/src/test/java/org/odk/collect/android/formentry/BackgroundAudioPermissionDialogFragmentTest.java
  collect_app/src/test/java/org/odk/collect/android/formentry/QuitFormDialogFragmentTest.java
  collect_app/src/test/java/org/odk/collect/android/formentry/QuitFormDialogTest.kt
  collect_app/src/test/java/org/odk/collect/android/formentry/SaveFormProgressDialogFragmentTest.java
  collect_app/src/test/java/org/odk/collect/android/formentry/repeats/DeleteRepeatDialogFragmentTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectOneFromMapDialogFragmentTest.kt
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectOneFromMapWidgetTest.kt
  settings.gradle
  shadows/.gitignore
  shadows/README.md
  shadows/build.gradle.kts
  shadows/consumer-rules.pro
  shadows/src/main/AndroidManifest.xml
  shadows/src/main/java/org/odk/collect/shadows/ShadowAndroidXAlertDialog.kt
  shadows/src/test/java/org/odk/collect/shadows/ShadowAndroidXAlertDialogTest.kt
Labels: behavior verified

#5465 Fixed attaching gifs and scaling down images
  androidshared/build.gradle
  androidshared/src/androidTest/java/org/odk/collect/androidshared/bitmap/ImageCompressorTest.kt
  androidshared/src/androidTest/java/org/odk/collect/androidshared/bitmap/ImageFileUtilsTest.kt
  androidshared/src/main/java/org/odk/collect/androidshared/bitmap/ImageCompressor.kt
  androidshared/src/main/java/org/odk/collect/androidshared/bitmap/ImageFileUtils.kt
  buildSrc/src/main/java/dependencies/Dependencies.kt
  collect_app/build.gradle
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/ImageConverterTest.kt
  collect_app/src/main/java/org/odk/collect/android/configure/qr/CachingQRCodeGenerator.kt
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeViewModel.kt
  collect_app/src/main/java/org/odk/collect/android/draw/DrawActivity.java
  collect_app/src/main/java/org/odk/collect/android/draw/DrawView.kt
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/tasks/MediaLoadingTask.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ImageCompressionController.kt
  collect_app/src/main/java/org/odk/collect/android/utilities/ImageConverter.kt
  collect_app/src/main/java/org/odk/collect/android/widgets/items/LabelWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/LikertWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/ListMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/ListWidget.java
  collect_app/src/test/java/org/odk/collect/android/utilities/ImageCompressionControllerTest.kt
Labels: high priority, behavior verified

#5472 Improved user experience when using menu items in the form hierarchy view
  androidshared/src/main/java/org/odk/collect/androidshared/ui/multiclicksafe/MultiClickGuard.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
Labels: behavior verified

#5478 Add selectable shapes
  collect_app/src/androidTest/java/org/odk/collect/android/support/FakeClickableMapFragment.kt
  collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java
  collect_app/src/test/java/org/odk/collect/android/widgets/support/NoOpMapFragment.kt
  geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyActivity.java
  geo/src/main/java/org/odk/collect/geo/selection/SelectionMapFragment.kt
  geo/src/test/java/org/odk/collect/geo/geopoly/GeoPolyActivityTest.java
  geo/src/test/java/org/odk/collect/geo/selection/SelectionMapFragmentTest.kt
  geo/src/test/java/org/odk/collect/geo/support/FakeMapFragment.kt
  mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt
  mapbox/src/main/java/org/odk/collect/mapbox/PolyLineFeature.kt
  mapbox/src/main/java/org/odk/collect/mapbox/PolygonFeature.kt
  maps/src/main/java/org/odk/collect/maps/MapFragment.java
  osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java
Labels: high priority, behavior verified

#5474 Show different text for ignoring changes when editing or filling out a form
  collect_app/src/androidTest/java/org/odk/collect/android/feature/external/InstanceEditActionTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/BackgroundAudioRecordingTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormLanguageTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/QuickSaveTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/QuittingFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/SaveIncompleteTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/TrackChangesReasonTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/FormMetadataSettingsTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/regression/DrawWidgetTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/regression/FormValidationTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/regression/SignatureWidgetTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/SaveOrIgnoreDialog.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/QuitFormDialog.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/audit/AuditEventLogger.java
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/FormController.kt
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java
  collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/utilities/DummyFormController.kt
  strings/src/main/res/values/strings.xml
Labels: behavior verified

#5493 Fixed the text displayed when closing the draw activity
  collect_app/src/androidTest/java/org/odk/collect/android/regression/DrawWidgetTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/regression/SignatureWidgetTest.java
  collect_app/src/main/java/org/odk/collect/android/draw/DrawActivity.java
Labels: behavior verified

#5476 Remove ability to set Google account as server
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/SendFinalizedFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/AddNewProjectTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/GoogleDriveDeprecationTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/FormManagementSettingsTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ServerSettingsTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/CollectHelpers.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/MainMenuPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ManualProjectCreatorDialogPage.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ProjectManagementPage.kt
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeActivityResultDelegate.kt
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeScannerFragment.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/ProjectManagementPreferencesFragment.kt
  collect_app/src/main/java/org/odk/collect/android/projects/ManualProjectCreatorDialog.kt
  collect_app/src/main/java/org/odk/collect/android/projects/ProjectCreator.kt
  collect_app/src/main/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialog.kt
  collect_app/src/main/res/layout/manual_project_creator_dialog_layout.xml
  collect_app/src/main/res/xml/server_preferences.xml
  collect_app/src/test/java/org/odk/collect/android/configure/qr/QRCodeActivityResultDelegateTest.kt
  collect_app/src/test/java/org/odk/collect/android/projects/ManualProjectCreatorDialogTest.kt
  collect_app/src/test/java/org/odk/collect/android/projects/ProjectCreatorTest.kt
  collect_app/src/test/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialogTest.kt
  settings/src/main/java/org/odk/collect/settings/ODKAppSettingsImporter.kt
  settings/src/main/java/org/odk/collect/settings/importing/SettingsImporter.kt
  settings/src/main/java/org/odk/collect/settings/importing/SettingsImportingResult.kt
  settings/src/test/java/org/odk/collect/settings/ODKAppSettingsImporterTest.kt
  settings/src/test/java/org/odk/collect/settings/importing/SettingsImporterTest.kt
  strings/src/main/res/values-cs/strings.xml
  strings/src/main/res/values-de/strings.xml
  strings/src/main/res/values-es/strings.xml
  strings/src/main/res/values-fa/strings.xml
  strings/src/main/res/values-fi/strings.xml
  strings/src/main/res/values-fr/strings.xml
  strings/src/main/res/values-in/strings.xml
  strings/src/main/res/values-it/strings.xml
  strings/src/main/res/values-pt/strings.xml
  strings/src/main/res/values-rw/strings.xml
  strings/src/main/res/values-sw/strings.xml
  strings/src/main/res/values-tr/strings.xml
  strings/src/main/res/values-zh/strings.xml
  strings/src/main/res/values/strings.xml
Labels: needs testing

#5504 Improved handling default images
  collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java
  collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/DrawWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/SignatureWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/support/FakeQuestionMediaManager.java
Labels: high priority, behavior verified

#5501 Fix Google Drive banner and server switching
  collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/GoogleDriveDeprecationBannerTest.kt
  collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java
  collect_app/src/main/java/org/odk/collect/android/application/CollectSettingsChangeHandler.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/matchexactly/SyncStatusAppState.kt
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/test/java/org/odk/collect/android/application/CollectSettingsChangeHandlerTest.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/SyncStatusAppStateTest.java
Labels: high priority, behavior verified

#5506 Add warning when typing in instance name
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEndView.java
  collect_app/src/main/res/layout/form_entry_end.xml
  collect_app/src/main/res/values-night/colors.xml
  collect_app/src/main/res/values/colors.xml
  collect_app/src/main/res/values/theme.xml
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEndViewTest.kt
  strings/src/main/res/values/strings.xml
Labels: high priority, behavior verified

#5520 Update JavaRosa
  buildSrc/src/main/java/dependencies/Dependencies.kt
Labels: high priority

#5517 Fixed zooming to the current location in mapbox
  buildSrc/src/main/java/dependencies/Dependencies.kt
Labels: high priority, behavior verified

#5526 Show parsing error when receiving empty form list
  collect_app/src/main/java/org/odk/collect/android/openrosa/OpenRosaResponseParserImpl.kt
  collect_app/src/test/java/org/odk/collect/android/openrosa/OpenRosaResponseParserImplTest.kt
Labels: high priority

#5330 Remove untested and (believed to be) unnecessary updateAnswersForScreen calls
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormLanguageTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java
Labels: behavior verified

#5524 Improved scheduling auto-send jobs
  async/src/main/java/org/odk/collect/async/CoroutineAndWorkManagerScheduler.kt
Labels: needs testing

#5533 Improved handling invalid geo answers
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoPointMapWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoPointWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/ActivityGeoDataRequester.kt
  collect_app/src/test/java/org/odk/collect/android/widgets/GeoPointMapWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/GeoPointWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/utilities/ActivityGeoDataRequesterTest.java
Labels: high priority, behavior verified
