Repository getodk/collect, pull requests merged in 2023-09, with the labels that each got.

#5717 Remove grace period restriction time restriction from editing finalized forms
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/BackgroundAudioRecordingTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormSavedSnackbarTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/SendFinalizedFormTest.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderListActivity.java
  collect_app/src/main/java/org/odk/collect/android/dao/helpers/InstancesDaoHelper.java
  collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceExt.kt
  collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt
  collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuViewModel.kt
  collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt
  strings/src/main/res/values/strings.xml
Labels: high priority, behavior verified

#5707 Fixed missing audit events after navigating to settings
  collect_app/src/androidTest/assets/forms/one-question-audit-track-changes.xml
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryMenuDelegate.java
Labels: behavior verified

#5724 Move file in wrong place
  test-forms/src/main/resources/forms/one-question-audit-track-changes.xml
Labels: high priority

#5685 Only treat _ as markdown if separated by white space
  collect_app/src/main/java/org/odk/collect/android/utilities/HtmlUtils.java
  collect_app/src/test/java/org/odk/collect/android/utilities/HtmlUtilsTest.java
  test-forms/src/main/resources/forms/all-widgets.xml
Labels: behavior verified

#5700 Fix for #5634 Crash after zooming map
  collect_app/src/main/java/org/odk/collect/android/geo/GoogleMapFragment.java
Labels: behavior verified

#5712 Do not allow to attach gifs in AnnotateWidget
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java
  strings/src/main/res/values/strings.xml
Labels: behavior verified

#5693 Making the "Ready to Send" screen more actionable
  collect_app/src/androidTest/java/org/odk/collect/android/feature/external/InstanceUploadActionTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/SendFinalizedFormTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.kt
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/AppListActivity.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderActivity.java
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderListActivity.java
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/ReadyToSendBanner.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/ReadyToSendViewModel.kt
  collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt
  collect_app/src/main/java/org/odk/collect/android/notifications/builders/FormsSubmissionNotificationBuilder.kt
  collect_app/src/main/res/layout/instance_uploader_list.xml
  collect_app/src/main/res/layout/ready_to_send_banner.xml
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/send/ReadyToSendBannerTest.kt
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/send/ReadyToSendViewModelTest.kt
  collect_app/src/test/java/org/odk/collect/android/mainmenu/MainMenuActivityTest.kt
  formstest/src/main/java/org/odk/collect/formstest/InMemInstancesRepository.java
  shared/src/main/java/org/odk/collect/shared/TimeInMs.kt
  strings/src/main/java/org/odk/collect/strings/localization/LocalizedApplication.kt
  strings/src/main/res/values/strings.xml
Labels: behavior verified

#5729 Migrate usage of KEYCODE_BACK and onBackPressed()
  androidshared/src/main/java/org/odk/collect/androidshared/ui/OnBackPressedKeyListener.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/ViewOnlyFormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/WebViewActivity.java
  collect_app/src/main/java/org/odk/collect/android/draw/DrawActivity.java
  collect_app/src/main/java/org/odk/collect/android/listeners/OnBackPressedListener.java
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/ProjectPreferencesActivity.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/ServerPreferencesFragment.java
  geo/src/main/java/org/odk/collect/geo/geopoint/GeoPointDialogFragment.kt
  geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyActivity.java
Labels: behavior verified

#5708 Fixed missing „form resume” in audit log events when moving backward in not allowed in Collect settings
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
Labels: behavior verified
