Repository getodk/collect, pull requests merged in 2023-10, with the labels that each got.

#5742 Fixed: Doubled event in the audit log after saving a draft in Audit Test Location Background Audio form
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/RecordingHandler.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  test-forms/src/main/resources/forms/one-question-background-audio-audit.xml
Labels: behavior verified

#5747 Fixed importing QR codes
  qr-code/src/main/java/org/odk/collect/qrcode/QRCodeDecoder.kt
  qr-code/src/test/assets/qrScreenshotFromCollect.png
  qr-code/src/test/assets/qrSharedViaCollect.png
  qr-code/src/test/java/org/odk/collect/qrcode/QRCodeEncodeDecodeTest.kt
Labels: behavior verified

#5744 Fixed the order of events when location tracking is enabled
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
Labels: behavior verified

#5759 Improved handing fast clicking on different elements in the main menu
  androidshared/src/main/java/org/odk/collect/androidshared/ui/multiclicksafe/MultiClickGuard.kt
  collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt
  collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuButton.kt
  collect_app/src/main/java/org/odk/collect/android/mainmenu/StartNewFormButton.kt
  collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationConstants.java
Labels: behavior verified

#5760 Validate drafts when saved from end screen
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EncryptedFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormEndTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormSavedSnackbarTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/QuickSaveTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/QuittingFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/SaveIncompleteTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/IdentifyUserTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/TrackChangesReasonTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/BulkFinalizationTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/DeleteBlankFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/EditSavedFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/InstancesAdbTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/SendFinalizedFormTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/SwitchProjectTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/regression/ResetApplicationTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/MainMenuPage.java
  collect_app/src/main/java/org/odk/collect/android/dao/CursorLoaderFactory.java
  collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/InstancesDataService.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/formmap/FormMapViewModel.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceExt.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceListItemView.kt
  collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuViewModel.kt
  collect_app/src/main/java/org/odk/collect/android/tasks/SaveFormToDisk.java
  collect_app/src/main/res/layout/form_chooser_list_item.xml
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/InstanceExtKtTest.kt
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/InstanceListItemViewTest.kt
  forms/src/main/java/org/odk/collect/forms/instances/Instance.java
  strings/src/main/res/values/strings.xml
Labels: behavior verified

#5766 Prevent bulk finalization on instances with save points
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/BulkFinalizationTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/InstancesDataService.kt
Labels: behavior verified

#5775 Allow forms with dynamic preload data to be bulk finalized
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/DynamicPreLoadedDataPullTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/DynamicPreLoadedDataSelects.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/ExternalDataFileNotFoundTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/backgroundlocation/LocationTrackingAuditTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/forms/FormNavigationTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/forms/FormUtilsTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/tasks/FormLoaderTaskTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/rules/BlankFormTestRule.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/rules/FormEntryActivityTestRule.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormDefCache.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/CollectFormEntryControllerFactory.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/InstancesDataService.kt
  collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java
  collect_app/src/main/java/org/odk/collect/android/utilities/ExternalizableFormDefCache.java
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryUseCasesTest.kt
  formstest/src/main/java/org/odk/collect/formstest/FormFixtures.kt
  shared/src/main/java/org/odk/collect/shared/TempFiles.kt
  test-forms/src/main/resources/forms/formWithExternalFiles.xml
  test-forms/src/main/resources/forms/pull_data.xml
  test-forms/src/main/resources/media/formWithExternalFiles-media/fruits.csv
  test-forms/src/main/resources/media/formWithExternalFiles-media/fruits.xml
  test-forms/src/main/resources/media/formWithExternalFiles-media/itemsets.csv
  test-forms/src/main/resources/media/formWithExternalFiles-media/last-saved.xml
Labels: behavior verified

#5765 Implement Material 3 "pill" component
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceListItemView.kt
  collect_app/src/main/res/drawable/baseline_check_24.xml
  collect_app/src/main/res/drawable/baseline_error_24.xml
  collect_app/src/main/res/drawable/baseline_rule_24.xml
  collect_app/src/main/res/drawable/list_item_divider.xml
  collect_app/src/main/res/layout/deprecation_banner.xml
  collect_app/src/main/res/layout/form_chooser_list_item.xml
  collect_app/src/main/res/layout/form_entry_end.xml
  collect_app/src/main/res/values-night/colors.xml
  collect_app/src/main/res/values/attrs.xml
  collect_app/src/main/res/values/colors.xml
  collect_app/src/main/res/values/theme.xml
  material/build.gradle
  material/src/main/java/org/odk/collect/material/MaterialPill.kt
  material/src/main/res/layout/pill.xml
Labels: behavior verified

#5786 Fixed displaying valid and invalid drafts on a map
  collect_app/src/main/java/org/odk/collect/android/formmanagement/formmap/FormMapViewModel.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/formmap/FormMapViewModelTest.kt
Labels: behavior verified

#5780 Fixed memory leaks
  collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java
  collect_app/src/test/java/org/odk/collect/android/formentry/FormSessionRepositoryTest.kt
  collect_app/src/test/java/org/odk/collect/android/formentry/support/InMemFormSessionRepository.kt
Labels: behavior verified

#5785 Show dialog when the user sees the drafts screen for the first time
  collect_app/src/androidTest/java/org/odk/collect/android/feature/external/InstancePickActionTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/QuickSaveTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/QuittingFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/BulkFinalizationTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/SwitchProjectTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/regression/ResetApplicationTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/EditSavedFormPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/MainMenuPage.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java
  settings/src/main/java/org/odk/collect/settings/keys/MetaKeys.kt
  strings/src/main/res/values/strings.xml
Labels: behavior verified

#5776 Improvements to bulk finalize
  androidshared/src/main/java/org/odk/collect/androidshared/ui/SnackbarUtils.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/BulkFinalizationTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/BulkFinalizationConfirmationDialogPage.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/EditSavedFormPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.kt
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java
  collect_app/src/main/java/org/odk/collect/android/analytics/AnalyticsEvents.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEndViewModel.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/InstancesDataService.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/drafts/BulkFinalizationViewModel.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/drafts/DraftsMenuProvider.kt
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/FinalizeAllSnackbarPresenter.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/FormEntryAccessPreferencesFragment.kt
  collect_app/src/main/res/xml/form_entry_access_preferences.xml
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEndViewModelTest.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/drafts/DraftsMenuProviderTest.kt
  collect_app/src/test/java/org/odk/collect/android/preferences/screens/FormEntryAccessPreferencesFragmentTest.kt
  settings/src/main/java/org/odk/collect/settings/ODKAppSettingsMigrator.java
  settings/src/main/java/org/odk/collect/settings/keys/ProtectedProjectKeys.kt
  settings/src/main/resources/client-settings.schema.json
  settings/src/test/java/org/odk/collect/settings/ODKAppSettingsMigratorTest.java
  settings/src/test/java/org/odk/collect/settings/validation/OriginalJsonSchemaSettingsValidatorTest.kt
  strings/src/main/res/values/strings.xml
Labels: behavior verified

#5792 Block closing the notification permission dialog by tapping outside the bounds
  collect_app/src/main/java/org/odk/collect/android/analytics/AnalyticsEvents.kt
  collect_app/src/main/java/org/odk/collect/android/mainmenu/PermissionsDialogFragment.kt
  collect_app/src/test/java/org/odk/collect/android/mainmenu/PermissionsDialogFragmentTest.kt
Labels: high priority, behavior verified

#5797 Fixed searching in the list of drafts
  collect_app/src/main/java/org/odk/collect/android/dao/CursorLoaderFactory.java
Labels: high priority, behavior verified

#5799 Do not allow to delete projects with drafts no matter what their status is
  collect_app/src/main/java/org/odk/collect/android/projects/ProjectDeleter.kt
  collect_app/src/test/java/org/odk/collect/android/projects/ProjectDeleterTest.kt
Labels: high priority, behavior verified

#5795 Migrate old finalize key correctly
  settings/src/main/java/org/odk/collect/settings/ODKAppSettingsMigrator.java
  settings/src/test/java/org/odk/collect/settings/ODKAppSettingsMigratorTest.java
Labels: high priority, behavior verified

#5794 Revert 'Do not mark forms as failed to send before sending' in v2023.3
  collect_app/src/main/java/org/odk/collect/android/gdrive/InstanceGoogleSheetsUploader.java
  collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuViewModel.kt
  collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java
  collect_app/src/test/java/org/odk/collect/android/mainmenu/MainMenuViewModelTest.kt
Labels: high priority, behavior verified

#5813 Protect GeoJSONFeature from ProGuard alterations
  collect_app/proguard-rules.txt
Labels: high priority, needs testing
