Repository getodk/collect, pull requests merged in 2023-11, with the labels that each got.

#5773 Button styling improvements
  collect_app/src/main/java/org/odk/collect/android/formentry/questions/WidgetViewUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ArbitraryFileWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BearingWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DateTimeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/DrawWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExArbitraryFileWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExAudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExPrinterWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExVideoWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoPointMapWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoPointWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoShapeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/GeoTraceWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/OSMWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/RatingWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/SignatureWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/TimeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/TriggerWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/VideoWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/BaseSelectListWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/RankingWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectImageMapWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectMinimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneFromMapWidget.kt
  collect_app/src/main/java/org/odk/collect/android/widgets/range/RangeDecimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/range/RangeIntegerWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/range/RangePickerDecimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/range/RangePickerIntegerWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/QuestionFontSizeUtils.java
  collect_app/src/main/res/values/buttons.xml
  collect_app/src/main/res/values/theme.xml
  collect_app/src/test/java/org/odk/collect/android/widgets/ArbitraryFileWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExArbitraryFileWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExAudioWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExImageWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExVideoWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectOneFromMapWidgetTest.kt
Labels: behavior verified

#5770 Improved styling the project settings dialog
  collect_app/src/main/res/layout/project_settings_dialog_layout.xml
Labels: behavior verified

#5745 Maintain last-saved across form updates
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/FormUpdateTest.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDownloader.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormDownloaderUseCases.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/FormMediaDownloaderTest.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormDownloaderUseCasesTest.kt
  test-forms/src/main/resources/forms/one-question-last-saved-updated.xml
  test-forms/src/main/resources/forms/one-question-last-saved.xml
Labels: behavior verified

#5738 Allow custom camera app to be specified in a question
  collect_app/src/main/java/org/odk/collect/android/formentry/media/PromptAutoplayer.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormEntryPromptUtils.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/ActivityGeoDataRequester.kt
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/ImageCaptureIntentCreator.kt
  collect_app/src/test/java/org/odk/collect/android/support/MockFormEntryPromptBuilder.java
  collect_app/src/test/java/org/odk/collect/android/widgets/AnnotateWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ImageWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/WidgetTest.java
Labels: behavior verified

#5826 Updated messages displayed in empty lists
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FillBlankFormPage.java
  collect_app/src/main/res/layout/activity_blank_form_list.xml
  collect_app/src/main/res/layout/delete_blank_form_layout.xml
  collect_app/src/main/res/layout/file_manager_list.xml
  collect_app/src/main/res/layout/form_download_list.xml
  collect_app/src/main/res/layout/hierarchy_layout.xml
  collect_app/src/test/java/org/odk/collect/android/formlists/DeleteBlankFormFragmentTest.kt
  strings/src/main/res/values/strings.xml
Labels: behavior verified

#5802 Dependency updates for v2023.4
  .circleci/config.yml
  analytics/build.gradle
  build.gradle
  buildSrc/src/main/java/dependencies/Dependencies.kt
  buildSrc/src/main/java/dependencies/Versions.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/SwipeHandler.kt
  config/quality.gradle
  gradle/wrapper/gradle-wrapper.properties
  imageloader/src/main/java/org/odk/collect/imageloader/GlideImageLoader.kt
  imageloader/src/main/java/org/odk/collect/imageloader/svg/SvgSoftwareLayerSetter.kt
  location/src/main/java/org/odk/collect/location/BaseLocationClient.kt
  location/src/main/java/org/odk/collect/location/GoogleFusedLocationClient.java
  location/src/main/java/org/odk/collect/location/GoogleFusedLocationClient.kt
  location/src/test/java/org/odk/collect/location/GoogleFusedLocationClientTest.java
  location/src/test/java/org/odk/collect/location/GoogleFusedLocationClientTest.kt
Labels: behavior verified

#5761 Re-introduce app bar elevation
  androidshared/src/main/res/layout/app_bar_layout.xml
  androidshared/src/main/res/layout/app_bar_shadow.xml
  collect_app/src/main/res/layout/changes_reason_dialog.xml
  collect_app/src/main/res/layout/form_entry.xml
  collect_app/src/main/res/layout/identify_user_dialog.xml
  collect_app/src/main/res/layout/manual_project_creator_dialog_layout.xml
  collect_app/src/main/res/layout/qr_code_project_creator_dialog_layout.xml
  collect_app/src/main/res/layout/select_minimal_dialog_layout.xml
Labels: behavior verified

#5822 Removed Stamen maps
  collect_app/src/main/java/org/odk/collect/android/geo/MapConfiguratorProvider.java
  collect_app/src/main/java/org/odk/collect/android/geo/MapFragmentFactoryImpl.kt
  collect_app/src/test/java/org/odk/collect/android/geo/MapFragmentFactoryImplTest.kt
  settings/src/main/java/org/odk/collect/settings/ODKAppSettingsMigrator.java
  settings/src/main/java/org/odk/collect/settings/keys/ProjectKeys.kt
  settings/src/test/java/org/odk/collect/settings/ODKAppSettingsMigratorTest.java
  strings/src/main/res/values-ar/strings.xml
  strings/src/main/res/values-cs/strings.xml
  strings/src/main/res/values-da/strings.xml
  strings/src/main/res/values-de/strings.xml
  strings/src/main/res/values-es/strings.xml
  strings/src/main/res/values-et/strings.xml
  strings/src/main/res/values-fi/strings.xml
  strings/src/main/res/values-fr/strings.xml
  strings/src/main/res/values-hi/strings.xml
  strings/src/main/res/values-in/strings.xml
  strings/src/main/res/values-it/strings.xml
  strings/src/main/res/values-ja/strings.xml
  strings/src/main/res/values-km/strings.xml
  strings/src/main/res/values-mr/strings.xml
  strings/src/main/res/values-ne-rNP/strings.xml
  strings/src/main/res/values-pl/strings.xml
  strings/src/main/res/values-pt/strings.xml
  strings/src/main/res/values-ru/strings.xml
  strings/src/main/res/values-rw/strings.xml
  strings/src/main/res/values-sr/strings.xml
  strings/src/main/res/values-sv-rSE/strings.xml
  strings/src/main/res/values-sw/strings.xml
  strings/src/main/res/values-te/strings.xml
  strings/src/main/res/values-th-rTH/strings.xml
  strings/src/main/res/values-uk/strings.xml
  strings/src/main/res/values-ur/strings.xml
  strings/src/main/res/values-zh/strings.xml
  strings/src/main/res/values/strings.xml
  strings/src/main/res/values/untranslated.xml
Labels: behavior verified

#5824 Fix multi select widget with no-buttons appearance
  collect_app/src/main/java/org/odk/collect/android/adapters/SelectMultipleListAdapter.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectMultiWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectOneWidgetTest.java
Labels: behavior verified

#5665 Refactor prep for only creating database for search/pulldata if needed
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormMediaTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/SavePointTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/dynamicpreload/DynamicPreLoadedDataSelects.java
  collect_app/src/main/java/org/odk/collect/android/adapters/AbstractSelectListAdapter.java
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/ApplicationInitializer.kt
  collect_app/src/main/java/org/odk/collect/android/application/initialization/JavaRosaInitializer.kt
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/DynamicPreloadXFormParserFactory.kt
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/ExternalAnswerResolver.java
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/ExternalAppsUtils.java
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/ExternalDataHandler.java
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/ExternalDataManager.java
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/ExternalDataManagerImpl.java
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/ExternalDataReader.java
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/ExternalDataReaderImpl.java
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/ExternalDataUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/ExternalDataUtil.java
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/ExternalSQLiteOpenHelper.java
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/ExternalSelectChoice.java
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/handler/ExternalDataHandlerBase.java
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/handler/ExternalDataHandlerPull.java
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/handler/ExternalDataHandlerSearch.java
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/handler/ExternalDataSearchType.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/formentry/questions/SelectChoiceUtils.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/CollectFormEntryControllerFactory.kt
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java
  collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java
  collect_app/src/main/java/org/odk/collect/android/utilities/Appearances.kt
  collect_app/src/main/java/org/odk/collect/android/utilities/ExternalAppIntentProvider.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExDecimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExIntegerWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/LabelWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/LikertWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/ListMultiWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/ListWidget.java
  collect_app/src/test/java/org/odk/collect/android/dynamicpreload/DynamicPreloadExtraTest.kt
  collect_app/src/test/java/org/odk/collect/android/dynamicpreload/DynamicPreloadParseProcessorTest.kt
  collect_app/src/test/java/org/odk/collect/android/dynamicpreload/ExternalDataReaderTest.java
  collect_app/src/test/java/org/odk/collect/android/dynamicpreload/ExternalDataUseCasesTest.kt
  collect_app/src/test/java/org/odk/collect/android/dynamicpreload/ExternalDataUtilTest.java
  collect_app/src/test/java/org/odk/collect/android/utilities/ExternalAppUtilsTest.java
  test-forms/src/main/resources/media/external_data_10.zip
Labels: behavior verified

#5835 Handle not existing forms and form files during bulk finalize
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/InstancesDataService.kt
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryUseCasesTest.kt
Labels: behavior verified

#5844 Fix `WebView` workaround causing Activity to be shown with incorrect theme
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/ApplicationInitializer.kt
  collect_app/src/main/java/org/odk/collect/android/application/initialization/SystemThemeMismatchFixInitializer.kt
Labels: high priority, behavior verified

#5848 Specify when formIndex should be updated when there are errors during validating answers
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/RequiredQuestionTest.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/FormController.kt
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java
  collect_app/src/main/java/org/odk/collect/android/tasks/SaveFormToDisk.java
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/javarosawrapper/FormControllerTest.java
  collect_app/src/test/java/org/odk/collect/android/utilities/DummyFormController.kt
Labels: high priority, behavior verified

#5829 Extract Main Menu to Fragment to prevent lifecycle crashes
  collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt
  collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuFragment.kt
  collect_app/src/main/java/org/odk/collect/android/projects/ProjectSettingsDialog.kt
  collect_app/src/main/res/layout/main_menu_activity.xml
Labels: high priority, behavior verified

#5843 Fixed showing keyboard
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/utilities/SoftKeyboardController.java
  collect_app/src/main/java/org/odk/collect/android/utilities/SoftKeyboardController.kt
  collect_app/src/main/java/org/odk/collect/android/widgets/ExPrinterWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/items/RankingWidget.java
Labels: high priority, needs testing
