Repository getodk/collect, pull requests merged in 2024-11, with the labels that each got.

#6489 Fixed the bug with linearlayout's divider in RTL
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEndView.kt
  collect_app/src/main/res/drawable/margin_standard_list_divider.xml
  collect_app/src/main/res/layout/form_entry_end.xml
Labels: high priority, behavior verified

#6468 Reset savepoints when resetting instances
  collect_app/src/main/java/org/odk/collect/android/projects/ProjectResetter.kt
  collect_app/src/test/java/org/odk/collect/android/projects/ProjectResetterTest.kt
Labels: behavior verified

#6488 Block settings that restart the app when in form entry
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FillBlankFormWithRepeatGroupTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormNavigationTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormStylingTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/FormEntrySettingsTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryMenuProvider.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/ProjectPreferencesActivity.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/ProjectPreferencesFragment.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/UserInterfacePreferencesFragment.java
  collect_app/src/test/java/org/odk/collect/android/preferences/screens/ProjectPreferencesFragmentTest.kt
  strings/src/main/res/values/strings.xml
Labels: high priority, needs testing

#6497 Fix leaking form session when viewing submission
  collect_app/src/main/java/org/odk/collect/android/formhierarchy/ViewOnlyFormHierarchyActivity.kt
Labels: high priority, needs testing

#6494 Set usesEntities to true if there is an entityList attachment in the manifest
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/download/ServerFormDownloader.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormUseCasesTest.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/download/ServerFormDownloaderTest.java
Labels: high priority, needs testing

#6495 Fix property names clashing with DB column names
  collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
  collect_app/src/test/java/org/odk/collect/android/entities/DatabaseEntitiesRepositoryTest.kt
Labels: high priority, needs testing

#6503 Filter out case-insensitive duplicate properties
  collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
  collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt
  entities/src/main/java/org/odk/collect/entities/storage/InMemEntitiesRepository.kt
Labels: needs testing

#6515 Don't require a label for Entity updates
  entities/src/main/java/org/odk/collect/entities/LocalEntityUseCases.kt
  entities/src/test/java/org/odk/collect/entities/LocalEntityUseCasesTest.kt
Labels: needs testing

#6514 Do not format entity values that are build using XPath expressions
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EntityFormTest.kt
  entities/src/main/java/org/odk/collect/entities/javarosa/finalization/EntityFormFinalizationProcessor.java
  entities/src/main/java/org/odk/collect/entities/javarosa/spec/EntityFormParser.java
  test-forms/src/main/resources/forms/entities-with-dates-follow-up.xml
  test-forms/src/main/resources/forms/entities-with-dates-registration.xml
Labels: needs testing

#6527 Do not create entities with blank labels
  entities/src/main/java/org/odk/collect/entities/LocalEntityUseCases.kt
  entities/src/test/java/org/odk/collect/entities/LocalEntityUseCasesTest.kt
Labels: needs testing

#6530 Inflated missing menu
  collect_app/src/main/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialog.kt
  collect_app/src/test/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialogTest.kt
Labels: needs testing

#6523 Remove theme setting
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/FormEntrySettingsTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ResetProjectTest.kt
  collect_app/src/main/java/org/odk/collect/android/application/FeatureFlags.kt
  collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/UserInterfacePreferencesFragment.java
  collect_app/src/test/java/org/odk/collect/android/preferences/screens/UserInterfacePreferencesFragmentTest.kt
Labels: needs testing
