Repository getodk/collect, pull requests merged in 2024-04, with the labels that each got.

#6056 Fixed icon colors used in AudioVideoImageTextLabel
  collect_app/src/main/java/org/odk/collect/android/audio/AudioButton.java
  collect_app/src/main/java/org/odk/collect/android/formentry/questions/AudioVideoImageTextLabel.java
Labels: needs testing

#6058 Fixed creating savepoints for saved forms that were started from a blank form (not the list of already saved forms)
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/SavePointTest.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormSessionRepository.kt
  collect_app/src/test/java/org/odk/collect/android/formentry/support/InMemFormSessionRepository.kt
Labels: needs testing

#6067 Disable maxWidth attribute in the bottom sheet
  geo/src/main/res/layout/selection_map_layout.xml
Labels: needs testing

#6091 Use translations in test
  collect_app/src/androidTest/java/org/odk/collect/android/feature/smoke/AllWidgetsFormTest.kt
Labels: high priority

#6087 Updated icons used by external question types
  collect_app/src/main/res/layout/ex_arbitrary_file_widget_answer.xml
  collect_app/src/main/res/layout/ex_audio_widget_answer.xml
  collect_app/src/main/res/layout/ex_image_widget_answer.xml
  collect_app/src/main/res/layout/ex_video_widget_answer.xml
Labels: needs testing

#6090 Fixed setting marker icon in OSM
  osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java
Labels: needs testing

#6092 Automatically scroll when needed when clicking in tests
  collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/Interactions.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FirstLaunchPage.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.kt
Labels: high priority

#6093 Fixed cleaning instance dirs that are not needed
  collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt
  collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt
Labels: needs testing

#6095 Improved interpreting text as markdown
  collect_app/src/main/java/org/odk/collect/android/utilities/HtmlUtils.java
  collect_app/src/test/java/org/odk/collect/android/utilities/HtmlUtilsTest.java
Labels: needs testing

#6098 Fixed buttons that are blocked too long
  androidshared/src/main/java/org/odk/collect/androidshared/ui/multiclicksafe/MultiClickSafeMaterialButton.kt
  androidshared/src/main/res/values/attrs.xml
  collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuButton.kt
  collect_app/src/main/java/org/odk/collect/android/mainmenu/StartNewFormButton.kt
  collect_app/src/main/java/org/odk/collect/android/utilities/ApplicationConstants.java
  collect_app/src/main/res/layout/form_download_list.xml
  collect_app/src/main/res/layout/form_entry.xml
  collect_app/src/main/res/layout/form_entry_end.xml
  collect_app/src/main/res/layout/instance_uploader_list.xml
  collect_app/src/main/res/values/screen_names.xml
  lists/src/main/java/org/odk/collect/lists/EmptyListView.kt
  lists/src/main/res/layout/multi_select_controls_layout.xml
Labels: needs testing

#6083 Add support for styling lines and shapes in Select One from Map questions
  androidshared/src/main/java/org/odk/collect/androidshared/utils/ColorUtils.kt
  androidshared/src/test/java/org/odk/collect/androidshared/utils/ColorUtilsTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/FakeClickableMapFragment.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/formmap/FormMapViewModel.kt
  collect_app/src/main/java/org/odk/collect/android/widgets/items/SelectOneFromMapDialogFragment.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/formmap/FormMapViewModelTest.kt
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectChoicesMapDataTest.kt
  collect_app/src/test/java/org/odk/collect/android/widgets/items/SelectOneFromMapDialogFragmentTest.kt
  collect_app/src/test/java/org/odk/collect/android/widgets/support/NoOpMapFragment.kt
  geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyActivity.java
  geo/src/main/java/org/odk/collect/geo/selection/MappableSelectItem.kt
  geo/src/main/java/org/odk/collect/geo/selection/SelectionMapFragment.kt
  geo/src/main/java/org/odk/collect/geo/selection/SelectionSummarySheet.kt
  geo/src/test/java/org/odk/collect/geo/geopoly/GeoPolyActivityTest.java
  geo/src/test/java/org/odk/collect/geo/selection/SelectionMapFragmentTest.kt
  geo/src/test/java/org/odk/collect/geo/selection/SelectionSummarySheetTest.kt
  geo/src/test/java/org/odk/collect/geo/support/FakeMapFragment.kt
  geo/src/test/java/org/odk/collect/geo/support/Fixtures.kt
  google-maps/src/main/java/org/odk/collect/googlemaps/GoogleMapFragment.java
  icons/src/main/res/drawable/ic_map_point.xml
  icons/src/main/res/values/map_colors.xml
  mapbox/src/main/java/org/odk/collect/mapbox/DynamicPolyLineFeature.kt
  mapbox/src/main/java/org/odk/collect/mapbox/MapUtils.kt
  mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt
  mapbox/src/main/java/org/odk/collect/mapbox/StaticPolyLineFeature.kt
  mapbox/src/main/java/org/odk/collect/mapbox/StaticPolygonFeature.kt
  maps/build.gradle.kts
  maps/src/main/java/org/odk/collect/maps/LineDescription.kt
  maps/src/main/java/org/odk/collect/maps/MapConsts.kt
  maps/src/main/java/org/odk/collect/maps/MapFragment.java
  maps/src/main/java/org/odk/collect/maps/PolygonDescription.kt
  maps/src/main/java/org/odk/collect/maps/markers/MarkerIconDescription.kt
  maps/src/test/java/org/odk/collect/maps/LineDescriptionTest.kt
  maps/src/test/java/org/odk/collect/maps/MarkerIconDescriptionTest.kt
  maps/src/test/java/org/odk/collect/maps/PolygonDescriptionTest.kt
  osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java
Labels: behavior verified

#6088 Fixed issues caused by the new 'masked' appearance
  collect_app/src/main/java/org/odk/collect/android/utilities/Appearances.kt
  collect_app/src/main/java/org/odk/collect/android/views/WidgetAnswerText.kt
  collect_app/src/test/java/org/odk/collect/android/utilities/AppearancesTest.kt
  collect_app/src/test/java/org/odk/collect/android/widgets/DecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExDecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExIntegerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExStringWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/IntegerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/StringNumberWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/StringWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/GeneralExStringWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/GeneralStringWidgetTest.java
Labels: needs testing

#6107 Fixed displaying saved forms to delete
  collect_app/src/main/java/org/odk/collect/android/formlists/savedformlist/SavedFormListViewModel.kt
  collect_app/src/test/java/org/odk/collect/android/formlists/savedformlist/SavedFormListViewModelTest.kt
  forms-test/src/main/java/org/odk/collect/formstest/InstanceFixtures.kt
Labels: needs testing
