Repository getodk/collect, pull requests merged in 2024-05, with the labels that each got.

#6102 Fixed geotrace and geoshape widgets in read-only mode
  geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyActivity.java
  geo/src/test/java/org/odk/collect/geo/geopoly/GeoPolyActivityTest.java
  geo/src/test/java/org/odk/collect/geo/geopoly/GeoPolyActivityTest.kt
Labels: needs testing

#6049 Ignore expired savepoints
  collect_app/src/main/java/org/odk/collect/android/database/DatabaseConstants.java
  collect_app/src/main/java/org/odk/collect/android/database/forms/FormDatabaseMigrator.java
  collect_app/src/main/java/org/odk/collect/android/database/instances/InstanceDatabaseMigrator.java
  collect_app/src/test/java/org/odk/collect/android/database/FormDatabaseMigratorTest.java
  collect_app/src/test/java/org/odk/collect/android/database/InstanceDatabaseMigratorTest.kt
Labels: behavior verified

#6134 Fix potential ANR when saving form
  androidshared/src/main/java/org/odk/collect/androidshared/data/Consumable.kt
  collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuFragment.kt
  collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuViewModel.kt
  collect_app/src/test/java/org/odk/collect/android/mainmenu/MainMenuActivityTest.kt
  collect_app/src/test/java/org/odk/collect/android/mainmenu/MainMenuViewModelTest.kt
Labels: needs testing

#6068 Migrate old savepoints
  collect_app/src/main/java/org/odk/collect/android/application/initialization/SavepointsImporter.kt
  collect_app/src/main/java/org/odk/collect/android/application/initialization/upgrade/UpgradeInitializer.kt
  collect_app/src/main/java/org/odk/collect/android/database/DatabaseObjectMapper.kt
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/test/java/org/odk/collect/android/application/initialization/SavepointsImporterTest.kt
  settings/src/main/java/org/odk/collect/settings/keys/MetaKeys.kt
Labels: high priority, behavior verified

#6139 Delete savepoints when deleting blank forms they belong to
  collect_app/src/main/java/org/odk/collect/android/database/forms/DatabaseFormsRepository.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormsRepositoryProvider.kt
  collect_app/src/test/java/org/odk/collect/android/database/DatabaseFormsRepositoryTest.java
  collect_app/src/test/java/org/odk/collect/android/utilities/FormsRepositoryProviderTest.kt
  forms-test/src/main/java/org/odk/collect/formstest/FormsRepositoryTest.java
  forms-test/src/main/java/org/odk/collect/formstest/InMemFormsRepository.java
  forms-test/src/test/java/org/odk/collect/formstest/InMemFormsRepositoryTest.java
Labels: needs testing

#6103 Support updating dynamic required questions in field-list
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FieldListUpdateTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java
  collect_app/src/main/java/org/odk/collect/android/logic/ImmutableDisplayableQuestion.java
  test-forms/src/main/resources/forms/fieldlist-updates.xml
Labels: needs testing

#6150 Fix broken save point recovery translations
  .github/PULL_REQUEST_TEMPLATE.md
  strings/src/main/res/values-de/strings.xml
  strings/src/main/res/values-fr/strings.xml
  strings/src/test/java/org/odk/collect/strings/format/DateFormatsTest.kt
Labels: high priority

#6105 Fixed handling repeatable groups wrapped with regular ones
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormHierarchyTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormStylingTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormWithRepeatGroupTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormHierarchyPage.java
  collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/FormController.kt
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java
  collect_app/src/test/java/org/odk/collect/android/utilities/StubFormController.kt
  test-forms/src/main/resources/forms/repeat_group_wrapped_with_a_regular_group.xml
Labels: behavior verified

#6157 Fix nullable value
  collect_app/src/main/java/org/odk/collect/android/utilities/ImageCompressionController.kt
Labels: high priority
