Repository getodk/collect, pull requests merged in 2024-06, with the labels that each got.

#6121 Fix autosend scheduling
  analytics/src/main/java/org/odk/collect/analytics/Analytics.kt
  androidshared/src/main/java/org/odk/collect/androidshared/network/ConnectivityProvider.kt
  androidshared/src/main/java/org/odk/collect/androidshared/network/NetworkStateProvider.kt
  async/build.gradle.kts
  async/src/main/AndroidManifest.xml
  async/src/main/java/org/odk/collect/async/CoroutineAndWorkManagerScheduler.kt
  async/src/main/java/org/odk/collect/async/Scheduler.kt
  async/src/main/java/org/odk/collect/async/TaskSpec.kt
  async/src/main/java/org/odk/collect/async/TaskSpecWorker.kt
  async/src/main/java/org/odk/collect/async/WorkerAdapter.kt
  async/src/main/java/org/odk/collect/async/network/ConnectivityProvider.kt
  async/src/main/java/org/odk/collect/async/network/NetworkStateProvider.kt
  async/src/test/java/org/odk/collect/async/TaskSpecWorkerTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/BulkFinalizationTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/AutoSendTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ConfigureWithQRCodeTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/FakeNetworkStateProvider.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/TestDependencies.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/TestScheduler.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/MainMenuPage.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryViewModelFactory.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/ScheduledWorkUpgrade.kt
  collect_app/src/main/java/org/odk/collect/android/application/initialization/upgrade/UpgradeInitializer.kt
  collect_app/src/main/java/org/odk/collect/android/backgroundwork/AutoUpdateTaskSpec.kt
  collect_app/src/main/java/org/odk/collect/android/backgroundwork/FormUpdateAndInstanceSubmitScheduler.java
  collect_app/src/main/java/org/odk/collect/android/backgroundwork/InstanceSubmitScheduler.java
  collect_app/src/main/java/org/odk/collect/android/backgroundwork/SendFormsTaskSpec.kt
  collect_app/src/main/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpec.kt
  collect_app/src/main/java/org/odk/collect/android/backgroundwork/TaskData.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/BlankFormListActivity.kt
  collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/BlankFormListMenuProvider.kt
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstancesDataService.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/AutoSendSettingsProvider.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderListActivity.java
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/FormManagementPreferencesFragment.java
  collect_app/src/test/java/org/odk/collect/android/application/initialization/FormUpdatesUpgradeTest.kt
  collect_app/src/test/java/org/odk/collect/android/application/initialization/ScheduledWorkUpgradeTest.kt
  collect_app/src/test/java/org/odk/collect/android/backgroundwork/FormUpdateAndInstanceSubmitSchedulerTest.kt
  collect_app/src/test/java/org/odk/collect/android/backgroundwork/SendFormsTaskSpecTest.kt
  collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/formlists/blankformlist/BlankFormListMenuProviderTest.kt
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/InstancesDataServiceTest.kt
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/autosend/AutoSendSettingsProviderTest.kt
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcherTest.kt
  collect_app/src/test/java/org/odk/collect/android/preferences/screens/FormManagementPreferencesFragmentTest.kt
  mapbox/build.gradle.kts
  mapbox/src/main/java/org/odk/collect/mapbox/MapBoxInitializationFragment.kt
  test-forms/src/main/resources/forms/one-question-autosend-disabled.xml
Labels: needs testing

#6178 Use highest surface container color for rank items
  collect_app/src/main/res/layout/ranking_item.xml
Labels: needs testing

#6185 Maintain ranking item color when dragging
  collect_app/src/main/java/org/odk/collect/android/adapters/RankingListAdapter.java
Labels: needs testing

#6191 Fixed dependency modules
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/CollectGeoDependencyModule.kt
  collect_app/src/main/java/org/odk/collect/android/injection/config/CollectGoogleMapsDependencyModule.kt
  collect_app/src/main/java/org/odk/collect/android/injection/config/CollectOsmDroidDependencyModule.kt
  collect_app/src/main/java/org/odk/collect/android/injection/config/CollectProjectsDependencyModule.kt
  collect_app/src/main/java/org/odk/collect/android/injection/config/CollectSelfieCameraDependencyModule.kt
  maps/src/main/java/org/odk/collect/maps/layers/DirectoryReferenceLayerRepository.kt
  maps/src/test/java/org/odk/collect/maps/layers/DirectoryReferenceLayerRepositoryTest.kt
  maps/src/test/java/org/odk/collect/maps/layers/MapFragmentReferenceLayerUtilsTest.kt
Labels: high priority

#6184 Handle non-existing layers
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/MapsPreferencesFragment.kt
  collect_app/src/test/java/org/odk/collect/android/preferences/screens/MapsPreferencesFragmentTest.kt
Labels: high priority

#6190 Fixed deleting current layer
  maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersPicker.kt
  maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersStateViewModel.kt
  maps/src/test/java/org/odk/collect/maps/layers/OfflineMapLayersPickerTest.kt
Labels: high priority, needs testing

#6197 Fixed setting fragment factories
  geo/src/main/java/org/odk/collect/geo/geopoint/GeoPointMapActivity.java
  geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyActivity.java
  geo/src/test/java/org/odk/collect/geo/geopoint/GeoPointMapActivityTest.java
  geo/src/test/java/org/odk/collect/geo/geopoly/GeoPolyActivityTest.kt
  geo/src/test/java/org/odk/collect/geo/support/FakeMapFragment.kt
Labels: high priority, needs testing

#6188 Offline maps UI improvements
  maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersPicker.kt
  maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersViewModel.kt
  maps/src/main/res/layout/offline_map_layers_importer.xml
  maps/src/main/res/layout/offline_map_layers_picker_item.xml
  maps/src/test/java/org/odk/collect/maps/layers/OfflineMapLayersImporterTest.kt
  maps/src/test/java/org/odk/collect/maps/layers/OfflineMapLayersPickerTest.kt
  strings/src/main/res/values/strings.xml
Labels: needs testing

#6204 Fix rotation for read only polylines
  google-maps/src/main/java/org/odk/collect/googlemaps/GoogleMapFragment.java
  mapbox/src/main/java/org/odk/collect/mapbox/DynamicPolyLineFeature.kt
  mapbox/src/main/java/org/odk/collect/mapbox/LineFeature.kt
  mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt
  mapbox/src/main/java/org/odk/collect/mapbox/StaticPolyLineFeature.kt
  osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java
Labels: needs testing

#6186 Prevent double taps on multi select actions
  androidshared/src/main/java/org/odk/collect/androidshared/ui/multiclicksafe/DoubleClickSafeMaterialButton.kt
  androidshared/src/main/java/org/odk/collect/androidshared/ui/multiclicksafe/MultiClickGuard.kt
  lists/src/main/res/layout/multi_select_controls_layout.xml
Labels: needs testing

#6213 Fix autosend when using unsupported `auto-send` values
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/SelectMinimalDialogPage.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstancesDataService.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/FormExt.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcher.kt
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/autosend/FormExtTest.kt
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/autosend/InstanceAutoSendFetcherTest.kt
  forms/src/main/java/org/odk/collect/forms/Form.java
Labels: needs testing

#6215 Fix layers import view in landscape mode
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ChangesReasonPromptPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FillBlankFormPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FirstLaunchPage.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormHierarchyPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/MainMenuPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ManualProjectCreatorDialogPage.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/NotificationDrawer.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ProjectSettingsDialogPage.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/QRCodePage.java
  collect_app/src/test/java/org/odk/collect/android/activities/FormFillingActivityTest.kt
  maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersImporter.kt
  maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersPicker.kt
  maps/src/main/res/layout/offline_map_layers_importer.xml
  maps/src/test/java/org/odk/collect/maps/layers/OfflineMapLayersImporterTest.kt
  maps/src/test/java/org/odk/collect/maps/layers/OfflineMapLayersPickerTest.kt
  test-shared/src/main/java/org/odk/collect/testshared/AssertIntentsHelper.kt
  test-shared/src/main/java/org/odk/collect/testshared/Assertions.kt
  test-shared/src/main/java/org/odk/collect/testshared/EspressoHelpers.kt
  test-shared/src/main/java/org/odk/collect/testshared/Interactions.kt
  test-shared/src/main/java/org/odk/collect/testshared/WaitFor.kt
Labels: needs testing

#6216 Don't use masked appearance in text number widget
  collect_app/src/main/java/org/odk/collect/android/utilities/Appearances.kt
  collect_app/src/test/java/org/odk/collect/android/utilities/AppearancesTest.kt
  collect_app/src/test/java/org/odk/collect/android/widgets/DecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExDecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExIntegerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/IntegerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/StringNumberWidgetTest.java
Labels: needs testing

#6227 Fixed margins in offline layers
  maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersPickerAdapter.kt
  maps/src/main/res/layout/offline_map_layers_importer.xml
Labels: needs testing

#6230 Handle unsupported files when importing .mbtiles
  maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersImporter.kt
  maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersViewModel.kt
  maps/src/test/java/org/odk/collect/maps/layers/OfflineMapLayersImporterTest.kt
  strings/src/main/res/values/strings.xml
Labels: needs testing

#6238 Fixed displaying the number of unsupported layers
  maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersImporter.kt
  maps/src/test/java/org/odk/collect/maps/layers/OfflineMapLayersImporterTest.kt
Labels: needs testing

#6239 Fixed SingleSelectViewModel
  lists/src/main/java/org/odk/collect/lists/selects/SelectItem.kt
  lists/src/main/java/org/odk/collect/lists/selects/SingleSelectViewModel.kt
  lists/src/test/java/org/odk/collect/lists/selects/SingleSelectViewModelTest.kt
  maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersPicker.kt
Labels: needs testing
