Repository getodk/collect, pull requests merged in 2024-10, with the labels that each got.

#6428 Allow forms with parse errors to be downloaded, show errors at form open time
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/CatchFormDesignExceptionsTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EntityFormTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/InvalidFormTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/FormUpdateTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/regression/FillBlankFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/StubOpenRosaServer.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ErrorDialog.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ErrorDialog.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/MainMenuPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/FormMetadataParser.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/FormsDataService.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/LocalFormUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/download/ServerFormDownloader.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/metadata/FormMetadata.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/metadata/FormMetadataParser.kt
  collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FileUtils.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/FormMetadataParserTest.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/download/ServerFormDownloaderTest.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/metadata/FormMetadataParserTest.kt
  collect_app/src/test/java/org/odk/collect/android/utilities/FileUtilsTest.java
  entities/src/main/java/org/odk/collect/entities/javarosa/parse/EntityFormParseProcessor.java
  entities/src/main/java/org/odk/collect/entities/javarosa/spec/UnrecognizedEntityVersionException.kt
  strings/src/main/res/values/strings.xml
  test-forms/src/main/resources/forms/one-question-entity-registration-v2020.1.xml
Labels: needs testing

#6436 Improved loading images with Glide
  androidtest/src/main/java/org/odk/collect/androidtest/DrawableMatcher.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/questions/NoButtonsItem.java
  image-loader/src/main/java/org/odk/collect/imageloader/GlideImageLoader.kt
Labels: needs testing

#6429 Reworked the banner in Ready to send screen using card view
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/ReadyToSendBanner.kt
  collect_app/src/main/res/layout/instance_uploader_list.xml
  collect_app/src/main/res/layout/ready_to_send_banner.xml
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/send/ReadyToSendBannerTest.kt
Labels: needs testing

#6449 Update JavaRosa
  buildSrc/src/main/java/dependencies/Dependencies.kt
Labels: needs testing

#6448 Include DynamicPreloadExtra in formDef only if a form contains search or pulldata
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/DynamicPreloadXFormParserFactory.kt
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/ExternalDataUseCases.kt
  collect_app/src/test/java/org/odk/collect/android/dynamicpreload/DynamicPreloadExtraTest.kt
  collect_app/src/test/java/org/odk/collect/android/dynamicpreload/DynamicPreloadParseProcessorTest.kt
  collect_app/src/test/java/org/odk/collect/android/dynamicpreload/ExternalDataUseCasesTest.kt
Labels: needs testing

#6460 Prevent resetting finalized forms that modify entities
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ResetProjectTest.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstancesDataService.kt
  collect_app/src/main/java/org/odk/collect/android/projects/ProjectResetter.kt
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/InstancesDataServiceTest.kt
  forms-test/src/main/java/org/odk/collect/formstest/InstanceFixtures.kt
  strings/src/main/res/values/strings.xml
Labels: needs testing

#6467 Fixed issue with offline layer covering points
  buildSrc/src/main/java/dependencies/Dependencies.kt
  mapbox/src/main/java/org/odk/collect/mapbox/MapboxLocationCallback.kt
  mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt
  mapbox/src/main/java/org/odk/collect/mapbox/StaticPolygonFeature.kt
Labels: high priority, behavior verified

#6440 Prevent opening forms that use entities during form updates, and block form updates while filling out a form that uses entities
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EntityFormTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/MatchExactlyTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/PreviouslyDownloadedOnlyTest.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryViewModelFactory.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/database/DatabaseConstants.java
  collect_app/src/main/java/org/odk/collect/android/database/DatabaseObjectMapper.kt
  collect_app/src/main/java/org/odk/collect/android/database/forms/DatabaseFormColumns.kt
  collect_app/src/main/java/org/odk/collect/android/database/forms/DatabaseFormsRepository.java
  collect_app/src/main/java/org/odk/collect/android/database/forms/FormDatabaseMigrator.java
  collect_app/src/main/java/org/odk/collect/android/database/instances/DatabaseInstancesRepository.java
  collect_app/src/main/java/org/odk/collect/android/database/instances/InstanceDatabaseMigrator.java
  collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyActivity.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/FormsDataService.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/LocalFormUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/download/ServerFormDownloader.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/metadata/FormMetadata.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/metadata/FormMetadataParser.kt
  collect_app/src/main/java/org/odk/collect/android/utilities/ChangeLockProvider.kt
  collect_app/src/test/java/org/odk/collect/android/database/FormDatabaseMigratorTest.java
  collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt
  collect_app/src/test/java/org/odk/collect/android/external/FormsProviderTest.java
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/formlists/blankformlist/BlankFormListViewModelTest.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/FormsDataServiceTest.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormUseCasesTest.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/download/ServerFormDownloaderTest.java
  collect_app/src/test/java/org/odk/collect/android/formmanagement/metadata/FormMetadataParserTest.kt
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/InstancesDataServiceTest.kt
  collect_app/src/test/java/org/odk/collect/android/projects/ProjectDeleterTest.kt
  collect_app/src/test/java/org/odk/collect/android/projects/ProjectResetterTest.kt
  forms-test/src/main/java/org/odk/collect/formstest/FormUtils.kt
  forms/src/main/java/org/odk/collect/forms/Form.java
  shared/src/main/java/org/odk/collect/shared/locks/ChangeLock.kt
  shared/src/main/java/org/odk/collect/shared/locks/ReentrantLockChangeLock.kt
  shared/src/test/java/org/odk/collect/shared/locks/ThreadSafeBooleanChangeLockTest.kt
  strings/src/main/res/values/strings.xml
  test-shared/src/main/java/org/odk/collect/testshared/BooleanChangeLock.kt
Labels: high priority, needs testing

#6478 Upgrade JR to get randomize updates
  buildSrc/src/main/java/dependencies/Dependencies.kt
Labels: needs testing

#6477 Remove redundant files cleaning during resetting saved forms
  collect_app/src/main/java/org/odk/collect/android/projects/ProjectResetter.kt
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/InstancesDataServiceTest.kt
  collect_app/src/test/java/org/odk/collect/android/projects/ProjectResetterTest.kt
Labels: high priority, needs testing

#6487 Do not lock the forms db when a form uses entities but is started in view-only mode
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ViewFormPage.kt
  collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt
  collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt
Labels: needs testing
