Repository getodk/collect, pull requests merged in 2024-09, with the labels that each got.

#6376 Optimize redownloading entity forms
  collect_app/src/androidTest/java/org/odk/collect/android/benchmark/EntitiesBenchmarkTest.kt
  collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/LocalFormUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormsDetailsFetcher.kt
  collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/FormsDataServiceTest.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormUseCasesTest.kt
  entities/src/main/java/org/odk/collect/entities/LocalEntityUseCases.kt
  entities/src/main/java/org/odk/collect/entities/storage/EntitiesRepository.kt
  entities/src/main/java/org/odk/collect/entities/storage/Entity.kt
  entities/src/main/java/org/odk/collect/entities/storage/InMemEntitiesRepository.kt
  entities/src/test/java/org/odk/collect/entities/LocalEntityUseCasesTest.kt
  entities/src/test/java/org/odk/collect/entities/browser/EntityItemViewTest.kt
  entities/src/test/java/org/odk/collect/entities/javarosa/LocalEntitiesInstanceProviderTest.kt
  entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt
  shared/src/main/java/org/odk/collect/shared/strings/Md5.kt
  shared/src/test/java/org/odk/collect/shared/Md5Test.kt
Labels: high priority

#6394 Prevent local entity create/update from older spec version forms
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EntityFormTest.kt
  entities/src/main/java/org/odk/collect/entities/javarosa/finalization/EntityFormFinalizationProcessor.java
  entities/src/main/java/org/odk/collect/entities/javarosa/parse/EntityFormParseProcessor.java
  entities/src/test/java/org/odk/collect/entities/javarosa/EntitiesTest.java
  entities/src/test/java/org/odk/collect/entities/javarosa/EntityFormParseProcessorTest.java
  test-forms/src/main/resources/forms/one-question-entity-registration-v2023.1.xml
Labels: high priority

#6379 Show scale on map
  google-maps/src/main/java/org/odk/collect/googlemaps/GoogleMapFragment.java
  google-maps/src/main/java/org/odk/collect/googlemaps/scaleview/Drawer.java
  google-maps/src/main/java/org/odk/collect/googlemaps/scaleview/MapScaleModel.java
  google-maps/src/main/java/org/odk/collect/googlemaps/scaleview/MapScaleView.java
  google-maps/src/main/java/org/odk/collect/googlemaps/scaleview/Scale.java
  google-maps/src/main/java/org/odk/collect/googlemaps/scaleview/Scales.java
  google-maps/src/main/java/org/odk/collect/googlemaps/scaleview/ViewConfig.java
  google-maps/src/main/res/layout/map_layout.xml
  google-maps/src/main/res/values/attrs.xml
  mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt
  osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java
Labels: behavior verified

#6402 Fix bad queries after adding new propreties to entity list
  collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
  collect_app/src/main/java/org/odk/collect/android/database/forms/DatabaseFormsRepository.java
  collect_app/src/main/java/org/odk/collect/android/database/instances/DatabaseInstancesRepository.java
  collect_app/src/main/java/org/odk/collect/android/database/instances/InstanceDatabaseMigrator.java
  collect_app/src/main/java/org/odk/collect/android/database/savepoints/DatabaseSavepointsRepository.kt
  db/src/main/java/org/odk/collect/db/sqlite/DatabaseConnection.kt
  db/src/main/java/org/odk/collect/db/sqlite/SQLiteDatabaseExt.kt
  db/src/main/java/org/odk/collect/db/sqlite/SQLiteUtils.java
  db/src/main/java/org/odk/collect/db/sqlite/SynchronizedDatabaseConnection.kt
Labels: high priority

#6408 Order entities by insertion
  collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
  collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt
Labels: needs testing

#6406 Fixed importing savepoints
  collect_app/src/main/java/org/odk/collect/android/application/initialization/SavepointsImporter.kt
  collect_app/src/test/java/org/odk/collect/android/application/initialization/SavepointsImporterTest.kt
Labels: needs testing

#6403 Clear TilesOverlay correctly when not needed anymore
  osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java
Labels: needs testing

#6390 Fixed updating app bar color
  androidshared/src/main/java/org/odk/collect/androidshared/ui/ObviousProgressBar.kt
  androidshared/src/main/res/layout/app_bar_layout.xml
  collect_app/src/main/java/org/odk/collect/android/activities/AppListActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderListActivity.java
  collect_app/src/main/res/layout/form_chooser_list.xml
  collect_app/src/main/res/layout/form_download_list.xml
  collect_app/src/main/res/layout/instance_uploader_list.xml
  collect_app/src/main/res/layout/manual_project_creator_dialog_layout.xml
  collect_app/src/main/res/layout/qr_code_project_creator_dialog_layout.xml
  lists/src/main/java/org/odk/collect/lists/selects/MultiSelectListFragment.kt
Labels: needs testing

#6412 Do not proceed with LocalEntitiesFilterStrategy filtering if instanceId is null
  entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt
  entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt
Labels: needs testing

#6427 Fixed removing savepoints on finalize
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EncryptedFormTest.java
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java
Labels: needs testing

#6416 Allow deleting sent forms with entities
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/DeleteSavedFormTest.kt
  collect_app/src/main/java/org/odk/collect/android/formlists/savedformlist/DeleteSavedFormFragment.kt
  forms/src/main/java/org/odk/collect/forms/instances/Instance.java
  forms/src/test/java/org/odk/collect/forms/instances/InstanceTest.kt
Labels: needs testing

#6432 Improved caching images with Glide
  androidtest/src/main/java/org/odk/collect/androidtest/DrawableMatcher.kt
  collect_app/build.gradle
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/ImageLoadingTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/FileWidgetTest.java
  image-loader/build.gradle.kts
  image-loader/src/main/java/org/odk/collect/imageloader/GlideImageLoader.kt
  shared/src/main/java/org/odk/collect/shared/TempFiles.kt
  test-forms/src/main/resources/forms/form_with_images.xml
  test-forms/src/main/resources/media/rects_v1/rect.jpg
  test-forms/src/main/resources/media/rects_v1/rect.svg
  test-forms/src/main/resources/media/rects_v2/rect.jpg
  test-forms/src/main/resources/media/rects_v2/rect.svg
Labels: needs testing
