Repository getodk/collect, pull requests merged in 2024-08, with the labels that each got.

#6302 Clear cached forms on app upgrade
  collect_app/src/main/java/org/odk/collect/android/application/initialization/CachedFormsCleaner.kt
  collect_app/src/main/java/org/odk/collect/android/application/initialization/upgrade/UpgradeInitializer.kt
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/test/java/org/odk/collect/android/application/initialization/CachedFormsCleanerTest.kt
Labels: needs testing

#6299 Change in the way ranges look
  .kotlin/sessions/kotlin-compiler-10168212700024355037.salive
  collect_app/src/main/java/org/odk/collect/android/widgets/range/RangeDecimalWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/range/RangeIntegerWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/RangeWidgetUtils.java
  collect_app/src/main/res/color/slider_tick_tint_list.xml
  collect_app/src/main/res/color/slider_track_tint_list.xml
  collect_app/src/main/res/layout/range_widget_horizontal.xml
  collect_app/src/main/res/layout/range_widget_vertical.xml
  collect_app/src/main/res/values/slider_theme.xml
  collect_app/src/main/res/values/theme.xml
  collect_app/src/test/java/org/odk/collect/android/widgets/range/RangeDecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/range/RangeIntegerWidgetTest.java
Labels: behavior verified

#6342 Update JavaRosa to 4.4.1 for CSV parse improvements
  buildSrc/src/main/java/dependencies/Dependencies.kt
Labels: high priority

#6346 Add analytics for INSTANCE_UPLOAD
  collect_app/src/androidTest/java/org/odk/collect/android/feature/external/InstanceUploadActionTest.kt
  collect_app/src/main/java/org/odk/collect/android/analytics/AnalyticsEvents.kt
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java
Labels: high priority

#6341 Don't allow inserting instances with custom submission URI
  collect_app/src/main/java/org/odk/collect/android/external/FormsProvider.java
  collect_app/src/main/java/org/odk/collect/android/external/InstanceProvider.java
  collect_app/src/test/java/org/odk/collect/android/external/FormsProviderTest.java
  collect_app/src/test/java/org/odk/collect/android/external/InstanceProviderTest.java
Labels: high priority

#6353 Stream CSV when processing server entities
  buildSrc/src/main/java/dependencies/Dependencies.kt
  entities/src/main/java/org/odk/collect/entities/LocalEntityUseCases.kt
Labels: needs testing

#6357 Support symlink `dirPath` in `getAbsoluteFilePath`
  shared/src/main/java/org/odk/collect/shared/PathUtils.kt
  shared/src/main/java/org/odk/collect/shared/TempFiles.kt
  shared/src/test/java/org/odk/collect/shared/PathUtilsTest.kt
Labels: high priority

#6306 Implemented the new counter widget
  collect_app/src/main/java/org/odk/collect/android/utilities/Appearances.kt
  collect_app/src/main/java/org/odk/collect/android/widgets/CounterWidget.kt
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/main/res/drawable/counter_minus_button_background.xml
  collect_app/src/main/res/drawable/counter_plus_button_background.xml
  collect_app/src/main/res/drawable/counter_value_background.xml
  collect_app/src/main/res/layout/counter_widget.xml
  collect_app/src/main/res/values/theme.xml
  collect_app/src/test/java/org/odk/collect/android/widgets/CounterWidgetTest.kt
  collect_app/src/test/java/org/odk/collect/android/widgets/WidgetFactoryTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/WidgetFactoryTest.kt
  icons/src/main/res/drawable/ic_baseline_add_24.xml
  icons/src/main/res/drawable/ic_baseline_remove_24.xml
Labels: needs testing

#6332 Fixed displaying required questions with audio attachments
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/RequiredQuestionTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/RequiredQuestionTest.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/questions/AudioVideoImageTextLabel.java
  test-forms/src/main/resources/forms/requiredJR275.xml
  test-forms/src/main/resources/forms/required_question_with_audio.xml
  test-forms/src/main/resources/forms/required_question_with_custom_error_message.xml
Labels: needs testing

#6351 Fix property eq expressions for entities
  collect_app/build.gradle
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/utilities/CustomSQLiteQueryExecutionTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/rules/ResetStateRule.kt
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java
  collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
  collect_app/src/main/java/org/odk/collect/android/database/forms/DatabaseFormsRepository.java
  collect_app/src/main/java/org/odk/collect/android/database/forms/FormDatabaseMigrator.java
  collect_app/src/main/java/org/odk/collect/android/database/instances/DatabaseInstancesRepository.java
  collect_app/src/main/java/org/odk/collect/android/database/instances/InstanceDatabaseMigrator.java
  collect_app/src/main/java/org/odk/collect/android/database/savepoints/DatabaseSavepointsRepository.kt
  collect_app/src/main/java/org/odk/collect/android/database/savepoints/SavepointsDatabaseMigrator.kt
  collect_app/src/main/java/org/odk/collect/android/dynamicpreload/ExternalSQLiteOpenHelper.java
  collect_app/src/main/java/org/odk/collect/android/fastexternalitemset/ItemsetDbAdapter.java
  collect_app/src/main/java/org/odk/collect/android/projects/ProjectDeleter.kt
  collect_app/src/test/java/org/odk/collect/android/application/RobolectricApplication.java
  collect_app/src/test/java/org/odk/collect/android/database/DatabaseConnectionTest.kt
  collect_app/src/test/java/org/odk/collect/android/database/FormDatabaseMigratorTest.java
  collect_app/src/test/java/org/odk/collect/android/dynamicpreload/ExternalDataReaderTest.java
  collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt
  db/.gitignore
  db/build.gradle.kts
  db/src/main/AndroidManifest.xml
  db/src/main/java/org/odk/collect/db/sqlite/AltDatabasePathContext.kt
  db/src/main/java/org/odk/collect/db/sqlite/CursorExt.kt
  db/src/main/java/org/odk/collect/db/sqlite/CustomSQLiteQueryBuilder.java
  db/src/main/java/org/odk/collect/db/sqlite/CustomSQLiteQueryExecutor.java
  db/src/main/java/org/odk/collect/db/sqlite/DatabaseConnection.kt
  db/src/main/java/org/odk/collect/db/sqlite/DatabaseMigrator.java
  db/src/main/java/org/odk/collect/db/sqlite/SQLiteColumns.kt
  db/src/main/java/org/odk/collect/db/sqlite/SQLiteDatabaseExt.kt
  db/src/main/java/org/odk/collect/db/sqlite/SQLiteUtils.java
  db/src/test/java/org/odk/collect/db/sqlite/CustomSQLiteQueryBuilderTest.java
  db/src/test/java/org/odk/collect/db/sqlite/SQLiteUtilsTest.java
  db/src/test/java/org/odk/collect/db/sqlite/SqliteDatabaseExtTest.kt
  entities/src/main/java/org/odk/collect/entities/storage/InMemEntitiesRepository.kt
  settings.gradle
Labels: needs testing

#6356 Send and finalize forms in oldest first order
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/AutoSendTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/PartialSubmissionTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/SendFinalizedFormTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/StubOpenRosaServer.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/SendFinalizedFormPage.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/LocalFormUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceSubmitter.kt
  collect_app/src/main/java/org/odk/collect/android/openrosa/OpenRosaXmlFetcher.java
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryUseCasesTest.kt
  collect_app/src/test/java/org/odk/collect/android/openrosa/OpenRosaResponseParserImplTest.kt
  collect_app/src/test/java/org/odk/collect/android/openrosa/OpenRosaXmlFetcherTest.java
Labels: needs testing

#6370 Fixed the counter widget in rtl languages
  collect_app/src/main/res/drawable-ldrtl/counter_minus_button_background.xml
  collect_app/src/main/res/drawable-ldrtl/counter_plus_button_background.xml
Labels: behavior verified
