Repository getodk/collect, pull requests merged in 2024-02, with the labels that each got.

#5944 Make sure form end buttons grow together
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/audit/AuditTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/BulkFinalizationTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/ActivityHelpers.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/rules/CollectTestRule.kt
  collect_app/src/main/res/drawable/margin_standard_list_divider.xml
  collect_app/src/main/res/layout/form_entry_end.xml
Labels: needs testing

#5961 Fixed updating the list of questions with audio widgets
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/test/java/org/odk/collect/android/widgets/AudioWidgetTest.java
Labels: high priority, behavior verified

#5958 Update copy on end screen
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEndView.kt
  collect_app/src/main/res/layout/form_entry_end.xml
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEndViewTest.kt
  strings/src/main/res/values-ar/strings.xml
  strings/src/main/res/values-cs/strings.xml
  strings/src/main/res/values-de/strings.xml
  strings/src/main/res/values-es/strings.xml
  strings/src/main/res/values-fa-rAF/strings.xml
  strings/src/main/res/values-fa/strings.xml
  strings/src/main/res/values-fi/strings.xml
  strings/src/main/res/values-fr/strings.xml
  strings/src/main/res/values-ht/strings.xml
  strings/src/main/res/values-in/strings.xml
  strings/src/main/res/values-it/strings.xml
  strings/src/main/res/values-pt/strings.xml
  strings/src/main/res/values-ru/strings.xml
  strings/src/main/res/values-ur/strings.xml
  strings/src/main/res/values/strings.xml
Labels: high priority, needs testing

#5969 Fixed displaying answers in external widgets with thousands separator
  collect_app/src/main/java/org/odk/collect/android/views/WidgetAnswerText.kt
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/StringWidgetUtils.java
  collect_app/src/test/java/org/odk/collect/android/widgets/DecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExDecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExIntegerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/IntegerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/StringNumberWidgetTest.java
Labels: high priority, needs testing

#5975 Prevent concurrent modifications of audit log
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/audit/AuditEventLogger.java
  collect_app/src/main/java/org/odk/collect/android/formentry/audit/AuditUtils.kt
Labels: high priority

#5967 Fixed scrolling to the edited question in a list of questions
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FieldListUpdateTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  test-forms/src/main/resources/forms/fieldlist-updates.xml
Labels: high priority, behavior verified

#5979 Fixed saving audio answers
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FieldListUpdateTest.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/RecordingHandler.java
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
  collect_app/src/test/java/org/odk/collect/android/widgets/AudioWidgetTest.java
  test-forms/src/main/resources/forms/fieldlist-updates.xml
Labels: high priority, needs testing

#5985 Fixed decoding qr codes
  qr-code/src/main/java/org/odk/collect/qrcode/QRCodeDecoder.kt
Labels: high priority, needs testing
