Repository getodk/collect, pull requests merged in 2024-07, with the labels that each got.

#6235 Fixed displaying progress indicator while loading layers
  androidshared/src/main/java/org/odk/collect/androidshared/async/TrackableWorker.kt
  androidshared/src/test/java/org/odk/collect/androidshared/async/TrackableWorkerTest.kt
  maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersImporter.kt
  maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersPicker.kt
  maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersViewModel.kt
  test-shared/src/main/java/org/odk/collect/testshared/FakeScheduler.kt
Labels: needs testing

#6243 Dismiss the offline layers confirmation dialog on activity recreation
  maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersPicker.kt
  maps/src/test/java/org/odk/collect/maps/layers/OfflineMapLayersPickerTest.kt
Labels: needs testing

#6251 Fixed updating layers on changing basemaps
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/MapsPreferencesFragment.kt
  maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersPicker.kt
  maps/src/main/java/org/odk/collect/maps/layers/OfflineMapLayersViewModel.kt
  maps/src/test/java/org/odk/collect/maps/layers/OfflineMapLayersImporterTest.kt
  maps/src/test/java/org/odk/collect/maps/layers/OfflineMapLayersPickerTest.kt
Labels: high priority, behavior verified

#6269 Fix disappearing entity lists
  collect_app/src/main/java/org/odk/collect/android/entities/JsonFileEntitiesRepository.kt
  collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt
  entities/src/main/java/org/odk/collect/entities/storage/InMemEntitiesRepository.kt
Labels: needs testing

#6272 Let `Error`s crash the app during form loading
  collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java
Labels: needs testing

#6271 Text question type should allow new lines, wrap text, and respect the rows attribute
  collect_app/src/main/java/org/odk/collect/android/views/WidgetAnswerText.kt
  collect_app/src/test/java/org/odk/collect/android/widgets/DecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExDecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExIntegerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExStringWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/IntegerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/StringNumberWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/StringWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/GeneralStringWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/WidgetTest.java
Labels: high priority, behavior verified

#6275 Fixed memory leaks in form-filling
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryViewModelFactory.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/backgroundlocation/BackgroundLocationHelper.java
  collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyActivity.java
Labels: high priority, needs testing

#6273 Fixed hiding error in external widgets
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/GeneralExStringWidgetTest.java
Labels: high priority, needs testing

#6287 Removed the old printer widget
  collect_app/src/main/java/org/odk/collect/android/widgets/ExPrinterWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/main/res/layout/ex_printer_widget.xml
  collect_app/src/test/java/org/odk/collect/android/widgets/ExPrinterWidgetTest.java
  docs/ANALYTICS-QUESTIONS.md
  strings/src/main/res/values-af/strings.xml
  strings/src/main/res/values-am/strings.xml
  strings/src/main/res/values-ar/strings.xml
  strings/src/main/res/values-bn/strings.xml
  strings/src/main/res/values-ca/strings.xml
  strings/src/main/res/values-cs/strings.xml
  strings/src/main/res/values-da/strings.xml
  strings/src/main/res/values-de/strings.xml
  strings/src/main/res/values-es/strings.xml
  strings/src/main/res/values-et/strings.xml
  strings/src/main/res/values-fa-rAF/strings.xml
  strings/src/main/res/values-fa/strings.xml
  strings/src/main/res/values-fi/strings.xml
  strings/src/main/res/values-fr/strings.xml
  strings/src/main/res/values-hi/strings.xml
  strings/src/main/res/values-in/strings.xml
  strings/src/main/res/values-it/strings.xml
  strings/src/main/res/values-ja/strings.xml
  strings/src/main/res/values-ka/strings.xml
  strings/src/main/res/values-km/strings.xml
  strings/src/main/res/values-lo-rLA/strings.xml
  strings/src/main/res/values-lt/strings.xml
  strings/src/main/res/values-ml/strings.xml
  strings/src/main/res/values-mr/strings.xml
  strings/src/main/res/values-my/strings.xml
  strings/src/main/res/values-ne-rNP/strings.xml
  strings/src/main/res/values-nl/strings.xml
  strings/src/main/res/values-no/strings.xml
  strings/src/main/res/values-pl/strings.xml
  strings/src/main/res/values-pt/strings.xml
  strings/src/main/res/values-ro/strings.xml
  strings/src/main/res/values-ru/strings.xml
  strings/src/main/res/values-rw/strings.xml
  strings/src/main/res/values-sl/strings.xml
  strings/src/main/res/values-sq/strings.xml
  strings/src/main/res/values-sr/strings.xml
  strings/src/main/res/values-sv-rSE/strings.xml
  strings/src/main/res/values-sw-rKE/strings.xml
  strings/src/main/res/values-sw/strings.xml
  strings/src/main/res/values-te/strings.xml
  strings/src/main/res/values-th-rTH/strings.xml
  strings/src/main/res/values-tl/strings.xml
  strings/src/main/res/values-uk/strings.xml
  strings/src/main/res/values-ur-rPK/strings.xml
  strings/src/main/res/values-ur/strings.xml
  strings/src/main/res/values-vi/strings.xml
  strings/src/main/res/values-zh-rTW/strings.xml
  strings/src/main/res/values-zh/strings.xml
  strings/src/main/res/values-zu/strings.xml
  strings/src/main/res/values/strings.xml
Labels: needs testing

#6291 Target API 34
  audio-recorder/src/main/AndroidManifest.xml
  buildSrc/src/main/java/dependencies/Versions.kt
  location/src/main/AndroidManifest.xml
Labels: behavior verified
