Repository getodk/collect, pull requests merged in 2024-03, with the labels that each got.

#5992 Fixed playing audio
  audioclips/src/main/java/org/odk/collect/audioclips/AudioClipViewModel.kt
  audioclips/src/test/java/org/odk/collect/audioclips/AudioClipViewModelTest.kt
  collect_app/src/main/java/org/odk/collect/android/widgets/AudioWidget.java
Labels: high priority

#5998 Catch exception when preloading select choices
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/dynamicpreload/DynamicPreLoadedDataSelects.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
  test-forms/src/main/resources/forms/external-csv-search-broken.xml
Labels: high priority

#6004 Fixed margin margin between group name and list
  collect_app/src/main/res/layout/hierarchy_layout.xml
  collect_app/src/main/res/layout/odk_view.xml
Labels: needs testing

#6028 Revert "Migrate to FusedLocationProviderClient"
  buildSrc/src/main/java/dependencies/Dependencies.kt
  location/src/main/java/org/odk/collect/location/BaseLocationClient.kt
  location/src/main/java/org/odk/collect/location/GoogleFusedLocationClient.java
  location/src/main/java/org/odk/collect/location/GoogleFusedLocationClient.kt
  location/src/test/java/org/odk/collect/location/GoogleFusedLocationClientTest.java
  location/src/test/java/org/odk/collect/location/GoogleFusedLocationClientTest.kt
Labels: high priority, behavior verified

#6019 Apply M3 styling to user identity and change reason text fields
  collect_app/src/main/res/layout/changes_reason_dialog.xml
  collect_app/src/main/res/layout/identify_user_dialog.xml
  collect_app/src/main/res/layout/widget_answer_text.xml
  collect_app/src/main/res/values/colors.xml
Labels: needs testing

#6045 Ignore flakey test
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormNavigationTest.kt
Labels: high priority

#6050 Fixed applying proper theme in FormUriActivity
  collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt
Labels: needs testing
