Repository getodk/collect, pull requests merged in 2025-02, with the labels that each got.

#6585 Remove local entities setting
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EntityFormTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/MainMenuPage.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/JavaRosaInitializer.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/CollectFormEntryControllerFactory.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/Defaults.kt
  collect_app/src/main/res/xml/experimental_preferences.xml
  settings/src/main/java/org/odk/collect/settings/keys/ProjectKeys.kt
  strings/src/main/res/values-cs/strings.xml
  strings/src/main/res/values-de/strings.xml
  strings/src/main/res/values-es/strings.xml
  strings/src/main/res/values-fi/strings.xml
  strings/src/main/res/values-fr/strings.xml
  strings/src/main/res/values-it/strings.xml
  strings/src/main/res/values-pt/strings.xml
  strings/src/main/res/values-zh-rTW/strings.xml
  strings/src/main/res/values-zh/strings.xml
  strings/src/main/res/values/strings.xml
Labels: high priority, behavior verified

#6580 Do not limit the maximum zoom level to 22
  osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java
Labels: behavior verified

#6612 Fixed touch tracking in the range slider
  collect_app/src/main/java/org/odk/collect/android/views/TrackingTouchSlider.kt
Labels: high priority, behavior verified

#6601 Catch sqlite exceptions when filter entities
  collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
  collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt
  entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt
  entities/src/main/java/org/odk/collect/entities/storage/InMemEntitiesRepository.kt
  entities/src/main/java/org/odk/collect/entities/storage/QueryException.kt
  entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt
Labels: high priority, behavior verified

#6618 Prevent crashes after problems saving entities
  collect_app/src/androidTest/java/org/odk/collect/android/benchmark/EntitiesBenchmarkTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/benchmark/support/Benchmarker.kt
  collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
  db/src/main/java/org/odk/collect/db/sqlite/RowNumbers.kt
  db/src/main/java/org/odk/collect/db/sqlite/SQLiteColumns.kt
  db/src/test/java/org/odk/collect/db/sqlite/RowNumbersTest.kt
Labels: high priority, needs testing

#6620 Make the recovery dialog non-cancelable
  collect_app/src/main/java/org/odk/collect/android/external/FormUriActivity.kt
  collect_app/src/test/java/org/odk/collect/android/external/FormUriActivityTest.kt
Labels: high priority, needs testing

#6619 Fix handling of numbers in SQLite query arguments
  collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
  collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt
  db/src/main/java/org/odk/collect/db/sqlite/SqlQuery.kt
  db/src/test/java/org/odk/collect/db/sqlite/SqlQueryTest.kt
  entities/src/main/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategy.kt
  entities/src/main/java/org/odk/collect/entities/javarosa/filter/PullDataFunctionHandler.kt
  entities/src/main/java/org/odk/collect/entities/storage/InMemEntitiesRepository.kt
  entities/src/test/java/org/odk/collect/entities/javarosa/filter/LocalEntitiesFilterStrategyTest.kt
  shared/src/main/java/org/odk/collect/shared/Query.kt
Labels: high priority, behavior verified

#6573 Log filter times during form entry
  androidshared/src/main/java/org/odk/collect/androidshared/ui/ToastUtils.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormDownloadListActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/application/initialization/ApplicationInitializer.kt
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeMenuProvider.kt
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeScannerFragment.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/BlankFormListMenuProvider.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/CollectFormEntryControllerFactory.kt
  collect_app/src/main/java/org/odk/collect/android/fragments/BarCodeScannerFragment.java
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/send/InstanceUploaderListActivity.java
  collect_app/src/main/java/org/odk/collect/android/preferences/Defaults.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/SettingsExt.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/dialogs/AdminPasswordDialogFragment.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/dialogs/ChangeAdminPasswordDialog.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/ExperimentalPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/FormMetadataPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/ProjectManagementPreferencesFragment.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/screens/ServerPreferencesFragment.java
  collect_app/src/main/java/org/odk/collect/android/projects/ManualProjectCreatorDialog.kt
  collect_app/src/main/java/org/odk/collect/android/projects/ProjectSettingsDialog.kt
  collect_app/src/main/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialog.kt
  collect_app/src/main/java/org/odk/collect/android/utilities/MediaUtils.kt
  collect_app/src/main/java/org/odk/collect/android/widgets/AnnotateWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BarcodeWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/BearingWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExAudioWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExImageWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/ExVideoWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/UrlWidget.java
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/FileRequester.kt
  collect_app/src/main/java/org/odk/collect/android/widgets/utilities/RangeWidgetUtils.java
  collect_app/src/main/res/xml/dev_tools_preferences.xml
  geo/src/main/java/org/odk/collect/geo/GeoActivityUtils.kt
  geo/src/main/java/org/odk/collect/geo/geopoint/GeoPointMapActivity.java
  geo/src/main/java/org/odk/collect/geo/selection/SelectionMapFragment.kt
  google-maps/src/main/java/org/odk/collect/googlemaps/GoogleMapConfigurator.java
  google-maps/src/main/java/org/odk/collect/googlemaps/GoogleMapFragment.java
  mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapConfigurator.java
  selfie-camera/src/main/java/org/odk/collect/selfiecamera/CaptureSelfieActivity.kt
  selfie-camera/src/test/java/org/odk/collect/selfiecamera/CaptureSelfieActivityTest.kt
  selfie-camera/src/test/java/org/odk/collect/selfiecamera/support/RobolectricApplication.kt
  settings/src/main/java/org/odk/collect/settings/keys/ProjectKeys.kt
  strings/src/main/res/values/strings.xml
Labels: needs testing
