Repository getodk/collect, pull requests merged in 2025-03, with the labels that each got.

#6635 Don't create/update entities with non-relevant `save_to`
  entities/src/main/java/org/odk/collect/entities/javarosa/finalization/EntityFormFinalizationProcessor.java
  entities/src/test/java/org/odk/collect/entities/javarosa/EntityFormFinalizationProcessorTest.java
Labels: high priority, needs testing

#6623 Add hidden-answer appearance for string with external app
  collect_app/src/main/java/org/odk/collect/android/widgets/ExStringWidget.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExDecimalWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExIntegerWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/ExStringWidgetTest.java
  collect_app/src/test/java/org/odk/collect/android/widgets/base/GeneralExStringWidgetTest.java
Labels: needs testing

#6582 Set device_id and settings_json from MDM
  .circleci/test_modules.txt
  androidshared/src/main/java/org/odk/collect/androidshared/system/BroadcastReceiverRegister.kt
  collect_app/build.gradle
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EncryptedFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/GetBlankFormsTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/EditSavedFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/MobileDeviceManagementTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/smoke/GetAndSubmitFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/TestDependencies.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/TestDependencies.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/AccessControlPage.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/MainMenuSettingsPage.kt
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/FirstLaunchActivity.kt
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeActivityResultDelegate.kt
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeScannerFragment.kt
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuActivity.kt
  collect_app/src/main/java/org/odk/collect/android/projects/ManualProjectCreatorDialog.kt
  collect_app/src/main/java/org/odk/collect/android/projects/ProjectCreatorImpl.kt
  collect_app/src/main/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialog.kt
  collect_app/src/main/java/org/odk/collect/android/projects/SettingsConnectionMatcherImpl.kt
  collect_app/src/test/java/org/odk/collect/android/configure/qr/QRCodeActivityResultDelegateTest.kt
  collect_app/src/test/java/org/odk/collect/android/mainmenu/MainMenuActivityTest.kt
  collect_app/src/test/java/org/odk/collect/android/projects/ManualProjectCreatorDialogTest.kt
  collect_app/src/test/java/org/odk/collect/android/projects/ProjectCreatorImplTest.kt
  collect_app/src/test/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialogTest.kt
  collect_app/src/test/java/org/odk/collect/android/projects/SettingsConnectionMatcherImplTest.kt
  mobile-device-management/.gitignore
  mobile-device-management/build.gradle.kts
  mobile-device-management/src/main/AndroidManifest.xml
  mobile-device-management/src/main/java/org/odk/collect/mobiledevicemanagement/MDMConfigHandler.kt
  mobile-device-management/src/main/java/org/odk/collect/mobiledevicemanagement/MDMConfigObserver.kt
  mobile-device-management/src/main/res/xml/managed_configuration.xml
  mobile-device-management/src/test/java/org/odk/collect/mobiledevicemanagement/MDMConfigHandlerTest.kt
  mobile-device-management/src/test/java/org/odk/collect/mobiledevicemanagement/MDMConfigObserverTest.kt
  projects/src/main/java/org/odk/collect/projects/ProjectConfigurationResult.kt
  projects/src/main/java/org/odk/collect/projects/ProjectCreator.kt
  projects/src/main/java/org/odk/collect/projects/SettingsConnectionMatcher.kt
  settings.gradle
  settings/src/main/java/org/odk/collect/settings/ODKAppSettingsImporter.kt
  settings/src/main/java/org/odk/collect/settings/importing/SettingsImporter.kt
  settings/src/main/java/org/odk/collect/settings/importing/SettingsImportingResult.kt
  settings/src/test/java/org/odk/collect/settings/ODKAppSettingsImporterTest.kt
  settings/src/test/java/org/odk/collect/settings/importing/SettingsImporterTest.kt
  strings/src/main/res/values/strings.xml
  test-shared/src/main/java/org/odk/collect/testshared/FakeBroadcastReceiverRegister.kt
Labels: needs testing

#6627 Add support for `integrityUrl` checks
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EntityFormTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/StubOpenRosaServer.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/FormsDataService.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/OpenRosaClientProvider.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/download/ServerFormDownloader.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyComponent.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/injection/config/ProjectDependencyModuleFactory.kt
  collect_app/src/main/java/org/odk/collect/android/projects/ProjectDependencyModule.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/FormsDataServiceTest.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormUseCasesTest.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/download/ServerFormDownloaderTest.java
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/InstancesDataServiceTest.kt
  entities/src/main/java/org/odk/collect/entities/LocalEntityUseCases.kt
  entities/src/main/java/org/odk/collect/entities/server/EntitySource.kt
  entities/src/test/java/org/odk/collect/entities/LocalEntityUseCasesTest.kt
  forms/src/main/java/org/odk/collect/forms/MediaFile.kt
  open-rosa/build.gradle.kts
  open-rosa/src/main/java/org/odk/collect/openrosa/forms/EntityIntegrity.kt
  open-rosa/src/main/java/org/odk/collect/openrosa/forms/OpenRosaClient.kt
  open-rosa/src/main/java/org/odk/collect/openrosa/parse/Kxml2OpenRosaResponseParser.kt
  open-rosa/src/main/java/org/odk/collect/openrosa/parse/OpenRosaResponseParser.java
  open-rosa/src/main/java/org/odk/collect/openrosa/parse/OpenRosaResponseParser.kt
  open-rosa/src/test/java/org/odk/collect/openrosa/forms/OpenRosaClientTest.kt
  open-rosa/src/test/java/org/odk/collect/openrosa/parse/Kxml2OpenRosaResponseParserTest.kt
  open-rosa/src/test/java/org/odk/collect/openrosa/parse/OpenRosaResponseParserImplTest.kt
  test-forms/src/main/resources/forms/one-question-entity-registration-id.xml
Labels: needs testing

#6649 Fix back button handling in hierarchy view
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FormHierarchyTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.kt
  collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragment.java
  test-forms/src/main/resources/forms/two-questions-in-group.xml
Labels: needs testing

#6645 Fix metadata parsing for main instances with attributes
  collect_app/src/main/java/org/odk/collect/android/formmanagement/download/FormDownloadException.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/download/FormDownloadExceptionMapper.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/download/ServerFormDownloader.java
  collect_app/src/main/java/org/odk/collect/android/formmanagement/metadata/FormMetadataParser.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/download/FormDownloadExceptionMapperTest.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/metadata/FormMetadataParserTest.kt
  collect_app/src/test/java/org/odk/collect/android/utilities/FormsDownloadResultInterpreterTest.kt
  strings/src/main/res/values/strings.xml
Labels: high priority

#6653 Fix support for servers that have already introduced type to manifest
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EntityFormTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/StubOpenRosaServer.java
  open-rosa/src/main/java/org/odk/collect/openrosa/parse/Kxml2OpenRosaResponseParser.kt
  open-rosa/src/test/java/org/odk/collect/openrosa/parse/Kxml2OpenRosaResponseParserTest.kt
Labels: needs testing

#6664 Fix OOM crashes when viewing saved forms
  collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragment.java
Labels: high priority, needs testing

#6668 Fixed recording mocked accuracy in geotrace/geoshape questions with manual location recording mode
  geo/src/main/java/org/odk/collect/geo/geopoly/GeoPolyActivity.java
  geo/src/test/java/org/odk/collect/geo/geopoint/GeoPointMapActivityTest.java
  geo/src/test/java/org/odk/collect/geo/geopoly/GeoPolyActivityTest.kt
Labels: high priority, needs testing
