Repository getodk/collect, pull requests merged in 2025-09, with the labels that each got.

#6870 Show snackbar when confirming barcodes
  androidshared/src/main/java/org/odk/collect/androidshared/ui/SnackbarUtils.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/application/ComposeTheme.kt
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeScannerFragment.kt
  collect_app/src/main/java/org/odk/collect/android/configure/qr/SettingsBarcodeScannerViewFactory.kt
  collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragment.java
  collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/BlankFormListActivity.kt
  collect_app/src/main/java/org/odk/collect/android/fragments/BarCodeScannerFragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/BarCodeScannerFragment.kt
  collect_app/src/main/java/org/odk/collect/android/fragments/BarcodeWidgetScannerFragment.kt
  collect_app/src/main/java/org/odk/collect/android/mainmenu/MainMenuFragment.kt
  collect_app/src/main/res/layout/fragment_scan.xml
  collect_app/src/main/res/values-night/material_colors.xml
  collect_app/src/main/res/values/colors.xml
  collect_app/src/main/res/values/material_colors.xml
  gradle/libs.versions.toml
  qr-code/build.gradle.kts
  qr-code/src/main/java/org/odk/collect/qrcode/BarcodeFilter.kt
  qr-code/src/main/java/org/odk/collect/qrcode/BarcodeScannerViewContainer.kt
  qr-code/src/main/java/org/odk/collect/qrcode/FlashlightToggleView.kt
  qr-code/src/main/java/org/odk/collect/qrcode/ScannerOverlay.kt
  qr-code/src/main/java/org/odk/collect/qrcode/mlkit/MlKitBarcodeScannerViewFactory.kt
  qr-code/src/main/java/org/odk/collect/qrcode/mlkit/PlayServicesFallbackBarcodeScannerViewFactory.kt
  qr-code/src/main/java/org/odk/collect/qrcode/zxing/ZxingBarcodeScannerViewFactory.kt
  qr-code/src/test/java/org/odk/collect/qrcode/BarcodeFilterTest.kt
  strings/src/main/res/values/strings.xml
  test-shared/src/main/java/org/odk/collect/testshared/FakeBarcodeScannerView.kt
Labels: needs testing

#6873 Set JavaRosa version to 5.1.0
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java
  gradle/libs.versions.toml
Labels: high priority

#6875 Switch to ML Kit as default scanner
  collect_app/src/main/java/org/odk/collect/android/configure/qr/SettingsBarcodeScannerViewFactory.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/Defaults.kt
  collect_app/src/main/res/xml/dev_tools_preferences.xml
  collect_app/src/main/res/xml/experimental_preferences.xml
  settings/src/main/java/org/odk/collect/settings/keys/ProjectKeys.kt
  strings/src/main/res/values/strings.xml
Labels: high priority, needs testing

#6874 Notify the user when match exactly stops running because of Doze
  async/src/main/java/org/odk/collect/async/TaskSpec.kt
  async/src/main/java/org/odk/collect/async/TaskSpecWorker.kt
  async/src/test/java/org/odk/collect/async/TaskSpecWorkerTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/MatchExactlyTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/TestScheduler.kt
  collect_app/src/main/java/org/odk/collect/android/backgroundwork/AutoUpdateTaskSpec.kt
  collect_app/src/main/java/org/odk/collect/android/backgroundwork/SendFormsTaskSpec.kt
  collect_app/src/main/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpec.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/FormsDataService.kt
  collect_app/src/main/java/org/odk/collect/android/notifications/NotificationManagerNotifier.kt
  collect_app/src/main/java/org/odk/collect/android/notifications/Notifier.kt
  collect_app/src/main/java/org/odk/collect/android/notifications/builders/FormsSyncStoppedNotificationBuilder.kt
  collect_app/src/test/java/org/odk/collect/android/backgroundwork/AutoUpdateTaskSpecTest.kt
  collect_app/src/test/java/org/odk/collect/android/backgroundwork/SendFormsTaskSpecTest.kt
  collect_app/src/test/java/org/odk/collect/android/backgroundwork/SyncFormsTaskSpecTest.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/FormsDataServiceTest.kt
  collect_app/src/test/java/org/odk/collect/android/notifications/NotificationManagerNotifierTest.kt
  strings/src/main/res/values/strings.xml
  test-shared/src/main/java/org/odk/collect/testshared/FakeScheduler.kt
Labels: high priority, needs testing

#6881 Make delete trigger translatable
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ProjectManagementPage.kt
  collect_app/src/main/java/org/odk/collect/android/preferences/dialogs/DeleteProjectDialog.kt
  collect_app/src/main/res/layout/delete_project_dialog_layout.xml
  collect_app/src/test/java/org/odk/collect/android/preferences/dialogs/DeleteProjectDialogTest.kt
  strings/src/main/res/values/strings.xml
Labels: high priority, needs testing

#6883 Remove system stopped filtering
  async/src/main/java/org/odk/collect/async/TaskSpecWorker.kt
Labels: high priority, needs testing

#6893 Avoid crash when scanning barcode
  androidshared/src/main/java/org/odk/collect/androidshared/ui/SnackbarUtils.kt
  collect_app/src/main/java/org/odk/collect/android/fragments/BarCodeScannerFragment.kt
Labels: high priority, needs testing

#6903 Fix the DrawActivity theme
  collect_app/src/main/AndroidManifest.xml
Labels: needs testing
