Repository getodk/collect, pull requests merged in 2025-05, with the labels that each got.

#6697 Fixed displaying the list of forms while creating a shortcut
  androidshared/src/main/java/org/odk/collect/androidshared/livedata/LiveDataUtils.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/external/AndroidShortcutsTest.kt
  collect_app/src/main/java/org/odk/collect/android/external/AndroidShortcutsActivity.kt
  collect_app/src/main/java/org/odk/collect/android/formlists/blankformlist/BlankFormListViewModel.kt
Labels: behavior verified

#6637 Move map zoom and config logic to ViewModel
  collect_app/src/androidTest/java/org/odk/collect/android/support/FakeClickableMapFragment.kt
  collect_app/src/test/java/org/odk/collect/android/widgets/support/NoOpMapFragment.kt
  geo/src/test/java/org/odk/collect/geo/support/FakeMapFragment.kt
  google-maps/src/main/java/org/odk/collect/googlemaps/GoogleMapFragment.java
  mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt
  maps/src/main/java/org/odk/collect/maps/MapFragment.kt
  maps/src/main/java/org/odk/collect/maps/MapFragmentDelegate.kt
  maps/src/main/java/org/odk/collect/maps/MapViewModel.kt
  maps/src/main/java/org/odk/collect/maps/MapViewModelMapFragment.kt
  maps/src/main/java/org/odk/collect/maps/ZoomObserver.kt
  osmdroid/src/main/java/org/odk/collect/osmdroid/OsmDroidMapFragment.java
Labels: needs testing

#6698 Improve editing finalized forms
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EntityFormTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/EditSavedFormTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormHierarchyPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/SendFinalizedFormPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ViewFormPage.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/database/DatabaseConstants.java
  collect_app/src/main/java/org/odk/collect/android/database/DatabaseObjectMapper.kt
  collect_app/src/main/java/org/odk/collect/android/database/instances/DatabaseInstanceColumns.kt
  collect_app/src/main/java/org/odk/collect/android/database/instances/DatabaseInstancesRepository.java
  collect_app/src/main/java/org/odk/collect/android/database/instances/InstanceDatabaseMigrator.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEndView.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragment.java
  collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyViewModel.kt
  collect_app/src/main/java/org/odk/collect/android/formlists/savedformlist/SavedFormListItemView.kt
  collect_app/src/main/java/org/odk/collect/android/formlists/savedformlist/SavedFormListViewModel.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/formmap/FormMapViewModel.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceExt.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceListItemView.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstancesDataService.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/LocalInstancesUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/utilities/FormsUploadResultInterpreter.kt
  collect_app/src/main/java/org/odk/collect/android/utilities/InstanceUploaderUtils.java
  collect_app/src/main/res/drawable/ic_edit_off_24.xml
  collect_app/src/main/res/layout/form_entry_end.xml
  collect_app/src/test/java/org/odk/collect/android/database/DatabaseInstancesRepositoryTest.java
  collect_app/src/test/java/org/odk/collect/android/database/DatabaseInstancesRepositoryTest.kt
  collect_app/src/test/java/org/odk/collect/android/database/InstanceDatabaseMigratorTest.kt
  collect_app/src/test/java/org/odk/collect/android/external/InstanceProviderTest.java
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEndViewTest.kt
  collect_app/src/test/java/org/odk/collect/android/formlists/savedformlist/SavedFormListViewModelTest.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/formmap/FormMapViewModelTest.kt
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/LocalInstancesUseCasesTest.kt
  collect_app/src/test/java/org/odk/collect/android/utilities/InstanceUploaderUtilsTest.java
  db/src/main/java/org/odk/collect/db/sqlite/DatabaseConnection.kt
  forms-test/src/main/java/org/odk/collect/formstest/InMemInstancesRepository.java
  forms-test/src/main/java/org/odk/collect/formstest/InstanceFixtures.kt
  forms-test/src/main/java/org/odk/collect/formstest/InstancesRepositoryTest.java
  forms-test/src/main/java/org/odk/collect/formstest/InstancesRepositoryTest.kt
  forms-test/src/test/java/org/odk/collect/formstest/InMemInstancesRepositoryTest.java
  forms-test/src/test/java/org/odk/collect/formstest/InMemInstancesRepositoryTest.kt
  forms/src/main/java/org/odk/collect/forms/instances/Instance.java
  forms/src/main/java/org/odk/collect/forms/instances/InstancesRepository.java
  strings/src/main/res/values-bg/strings.xml
  strings/src/main/res/values-cs/strings.xml
  strings/src/main/res/values-de/strings.xml
  strings/src/main/res/values-es/strings.xml
  strings/src/main/res/values-fi/strings.xml
  strings/src/main/res/values-fr/strings.xml
  strings/src/main/res/values-it/strings.xml
  strings/src/main/res/values-pt/strings.xml
  strings/src/main/res/values-ru/strings.xml
  strings/src/main/res/values-sl/strings.xml
  strings/src/main/res/values-ur/strings.xml
  strings/src/main/res/values-zh-rTW/strings.xml
  strings/src/main/res/values-zh/strings.xml
  strings/src/main/res/values/strings.xml
  test-forms/src/main/resources/forms/one-question-entity-registration-editable.xml
  test-forms/src/main/resources/forms/one-question-entity-update-editable.xml
Labels: needs testing

#6694 Don't create local entities for accept/reject entity lists
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EntityFormTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/StubOpenRosaServer.java
  collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
  collect_app/src/main/java/org/odk/collect/android/database/forms/FormDatabaseMigrator.java
  collect_app/src/main/java/org/odk/collect/android/database/instances/InstanceDatabaseMigrator.java
  collect_app/src/main/java/org/odk/collect/android/database/savepoints/DatabaseSavepointsRepository.kt
  collect_app/src/main/java/org/odk/collect/android/database/savepoints/SavepointsDatabaseMigrator.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormUseCases.kt
  collect_app/src/test/java/org/odk/collect/android/database/entities/EntitiesDatabaseMigratorTest.kt
  collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/download/ServerFormDownloaderTest.java
  db/src/main/java/org/odk/collect/db/sqlite/CursorExt.kt
  db/src/main/java/org/odk/collect/db/sqlite/MigrationListDatabaseMigrator.kt
  db/src/main/java/org/odk/collect/db/sqlite/SQLiteDatabaseExt.kt
  db/src/main/java/org/odk/collect/db/sqlite/SQLiteUtils.java
  entities/build.gradle.kts
  entities/src/main/java/org/odk/collect/entities/LocalEntityUseCases.kt
  entities/src/main/java/org/odk/collect/entities/browser/EntitiesViewModel.kt
  entities/src/main/java/org/odk/collect/entities/javarosa/intance/LocalEntitiesInstanceAdapter.kt
  entities/src/main/java/org/odk/collect/entities/storage/EntitiesRepository.kt
  entities/src/main/java/org/odk/collect/entities/storage/EntityList.kt
  entities/src/main/java/org/odk/collect/entities/storage/InMemEntitiesRepository.kt
  entities/src/test/java/org/odk/collect/entities/LocalEntityUseCasesTest.kt
  entities/src/test/java/org/odk/collect/entities/javarosa/EntityFormFinalizationProcessorTest.java
  forms-test/src/main/java/org/odk/collect/formstest/FormFixtures.kt
  forms/src/main/java/org/odk/collect/forms/MediaFile.kt
  open-rosa/src/main/java/org/odk/collect/openrosa/parse/Kxml2OpenRosaResponseParser.kt
  open-rosa/src/test/java/org/odk/collect/openrosa/parse/Kxml2OpenRosaResponseParserTest.kt
  test-forms/src/main/resources/forms/entities-with-dates-follow-up.xml
  test-forms/src/main/resources/forms/entities-with-dates-registration.xml
Labels: needs testing

#6672 Replace Zxing with MLKit and CameraX
  .circleci/config.yml
  check-size.sh
  collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/AddNewProjectTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/LaunchScreenTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/projects/UpdateProjectTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ConfigureWithQRCodeTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/StubBarcodeViewDecoder.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/TestDependencies.kt
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/odk/collect/android/activities/FormEntryViewModelFactory.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/application/Collect.java
  collect_app/src/main/java/org/odk/collect/android/configure/qr/CachingQRCodeGenerator.kt
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeActivityResultDelegate.kt
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeScannerFragment.kt
  collect_app/src/main/java/org/odk/collect/android/configure/qr/QRCodeTabsActivity.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/PrinterWidgetViewModel.kt
  collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragmentHostActivity.kt
  collect_app/src/main/java/org/odk/collect/android/fragments/BarCodeScannerFragment.java
  collect_app/src/main/java/org/odk/collect/android/fragments/BarcodeWidgetScannerFragment.kt
  collect_app/src/main/java/org/odk/collect/android/injection/config/AppDependencyModule.java
  collect_app/src/main/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialog.kt
  collect_app/src/main/java/org/odk/collect/android/utilities/CodeCaptureManagerFactory.kt
  collect_app/src/main/java/org/odk/collect/android/views/BarcodeViewDecoder.kt
  collect_app/src/main/res/layout/fragment_scan.xml
  collect_app/src/main/res/layout/qr_code_project_creator_dialog_layout.xml
  collect_app/src/test/java/org/odk/collect/android/activities/FirstLaunchActivityTest.kt
  collect_app/src/test/java/org/odk/collect/android/configure/qr/QRCodeActivityResultDelegateTest.kt
  collect_app/src/test/java/org/odk/collect/android/formentry/PrinterWidgetViewModelTest.kt
  collect_app/src/test/java/org/odk/collect/android/projects/ProjectSettingsDialogTest.kt
  collect_app/src/test/java/org/odk/collect/android/projects/QrCodeProjectCreatorDialogTest.kt
  collect_app/src/test/java/org/odk/collect/android/widgets/PrinterWidgetTest.kt
  gradle/libs.versions.toml
  qr-code/build.gradle.kts
  qr-code/src/main/java/org/odk/collect/qrcode/BarcodeScannerViewContainer.kt
  qr-code/src/main/java/org/odk/collect/qrcode/mlkit/MlKitBarcodeScannerViewFactory.kt
  qr-code/src/main/java/org/odk/collect/qrcode/mlkit/PlayServicesFallbackBarcodeScannerViewFactory.kt
  qr-code/src/main/java/org/odk/collect/qrcode/zxing/QRCodeCreator.kt
  qr-code/src/main/java/org/odk/collect/qrcode/zxing/QRCodeDecoder.kt
  qr-code/src/main/java/org/odk/collect/qrcode/zxing/ZxingBarcodeScannerViewFactory.kt
  qr-code/src/main/res/layout/mlkit_barcode_scanner_layout.xml
  qr-code/src/main/res/layout/zxing_barcode_scanner_layout.xml
  qr-code/src/test/java/org/odk/collect/qrcode/QRCodeEncodeDecodeTest.kt
  test-shared/build.gradle.kts
  test-shared/src/main/java/org/odk/collect/testshared/FakeBarcodeScannerView.kt
Labels: behavior verified

#6709 Improve editing finalized forms [Part 2]
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/EncryptedFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/BulkFinalizationTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/DeleteBlankFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/FormsAdbTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formmanagement/GetBlankFormsTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/EditSavedFormTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/settings/ServerSettingsTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/smoke/BadServerTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/smoke/GetAndSubmitFormTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/forms/FormUtilsTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/instrumented/tasks/FormLoaderTaskTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/StubOpenRosaServer.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/StubOpenRosaServer.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/SubmissionParser.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/ViewFormPage.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/dao/CursorLoaderFactory.java
  collect_app/src/main/java/org/odk/collect/android/dao/helpers/InstancesDaoHelper.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormOpeningMode.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/QuitFormDialog.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/saving/FormSaveViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragment.java
  collect_app/src/main/java/org/odk/collect/android/formhierarchy/FormHierarchyFragmentHostActivity.kt
  collect_app/src/main/java/org/odk/collect/android/formlists/savedformlist/DeleteSavedFormFragment.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/CollectFormEntryControllerFactory.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/FormFillingIntentFactory.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/finalization/EditedFormFinalizationProcessor.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/formmap/FormMapViewModel.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceExt.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceListItemView.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstancesDataService.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/LocalInstancesUseCases.kt
  collect_app/src/main/java/org/odk/collect/android/projects/ProjectDeleter.kt
  collect_app/src/main/java/org/odk/collect/android/tasks/FormLoaderTask.java
  collect_app/src/main/res/layout/form_hierarchy_layout.xml
  collect_app/src/test/java/org/odk/collect/android/formentry/QuitFormDialogTest.kt
  collect_app/src/test/java/org/odk/collect/android/formentry/audit/FormSaveViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/formlists/savedformlist/DeleteSavedFormFragmentTest.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/formmap/FormMapViewModelTest.kt
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/InstanceExtKtTest.kt
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/InstanceListItemViewTest.kt
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/InstancesDataServiceTest.kt
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/LocalInstancesUseCasesTest.kt
  collect_app/src/test/java/org/odk/collect/android/projects/ProjectDeleterTest.kt
  forms/src/main/java/org/odk/collect/forms/instances/Instance.java
  forms/src/test/java/org/odk/collect/forms/instances/InstanceTest.kt
  strings/src/main/res/values/strings.xml
  test-shared/src/main/java/org/odk/collect/testshared/Assertions.kt
Labels: needs testing

#6712 Don't download already downloaded entity lists
  collect_app/src/androidTest/java/org/odk/collect/android/support/StubOpenRosaServer.kt
  collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
  collect_app/src/main/java/org/odk/collect/android/formmanagement/ServerFormUseCases.kt
  collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt
  collect_app/src/test/java/org/odk/collect/android/formmanagement/ServerFormUseCasesTest.kt
  entities/src/main/java/org/odk/collect/entities/LocalEntityUseCases.kt
  entities/src/main/java/org/odk/collect/entities/storage/InMemEntitiesRepository.kt
  entities/src/test/java/org/odk/collect/entities/LocalEntityUseCasesTest.kt
  open-rosa/src/test/java/org/odk/collect/openrosa/parse/Kxml2OpenRosaResponseParserTest.kt
Labels: high priority

#6725 Improve editing finalized forms [Part 3]
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/AutoSendTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/instancemanagement/SendFinalizedFormTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/StubOpenRosaServer.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/SendFinalizedFormPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/SendFinalizedFormPage.kt
  collect_app/src/main/java/org/odk/collect/android/database/DatabaseConstants.java
  collect_app/src/main/java/org/odk/collect/android/database/DatabaseObjectMapper.kt
  collect_app/src/main/java/org/odk/collect/android/database/instances/DatabaseInstanceColumns.kt
  collect_app/src/main/java/org/odk/collect/android/database/instances/DatabaseInstancesRepository.java
  collect_app/src/main/java/org/odk/collect/android/database/instances/InstanceDatabaseMigrator.java
  collect_app/src/main/java/org/odk/collect/android/database/savepoints/DatabaseSavepointsRepository.kt
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstanceSubmitter.kt
  collect_app/src/main/java/org/odk/collect/android/instancemanagement/InstancesDataService.kt
  collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploaderTask.java
  collect_app/src/test/java/org/odk/collect/android/database/InstanceDatabaseMigratorTest.kt
  collect_app/src/test/java/org/odk/collect/android/external/InstanceProviderTest.java
  collect_app/src/test/java/org/odk/collect/android/formentry/FormEntryViewModelTest.java
  collect_app/src/test/java/org/odk/collect/android/instancemanagement/InstancesDataServiceTest.kt
  forms-test/src/main/java/org/odk/collect/formstest/InMemInstancesRepository.java
  forms-test/src/main/java/org/odk/collect/formstest/InstancesRepositoryTest.kt
  forms/src/main/java/org/odk/collect/forms/instances/Instance.java
Labels: high priority, needs testing

#6732 Fix empty entity list syncs
  collect_app/src/main/java/org/odk/collect/android/database/entities/DatabaseEntitiesRepository.kt
  collect_app/src/test/java/org/odk/collect/android/entities/EntitiesRepositoryTest.kt
Labels: high priority, needs testing

#6696 Support an intent group nested one level inside a field-list
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/FieldListUpdateTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/IntentGroupTest.java
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/IntentGroupTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/feature/formentry/NestedIntentGroupTest.kt
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/FormEntryPage.java
  collect_app/src/androidTest/java/org/odk/collect/android/support/pages/Page.kt
  collect_app/src/main/java/org/odk/collect/android/activities/FormFillingActivity.java
  collect_app/src/main/java/org/odk/collect/android/formentry/FormEntryViewModel.java
  collect_app/src/main/java/org/odk/collect/android/formentry/ODKView.java
  collect_app/src/main/java/org/odk/collect/android/formentry/audit/AuditUtils.kt
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/FormController.kt
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/FormControllerExt.kt
  collect_app/src/main/java/org/odk/collect/android/javarosawrapper/JavaRosaFormController.java
  collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java
  collect_app/src/main/res/layout/launch_intent_button_layout.xml
  collect_app/src/main/res/layout/odk_view.xml
  collect_app/src/test/java/org/odk/collect/android/activities/FormFillingActivityTest.kt
  collect_app/src/test/java/org/odk/collect/android/formlists/savedformlist/DeleteSavedFormFragmentTest.kt
  collect_app/src/test/java/org/odk/collect/android/javarosawrapper/FakeFormController.java
  collect_app/src/test/java/org/odk/collect/android/utilities/StubFormController.kt
  collect_app/src/test/java/org/odk/collect/android/widgets/WidgetFactoryTest.kt
  collect_app/src/test/java/org/odk/collect/android/widgets/datetime/pickers/BuddhistDatePickerDialogTest.kt
  test-forms/src/main/resources/forms/nested-intent-group.xml
  test-shared/src/main/java/org/odk/collect/testshared/Assertions.kt
Labels: needs testing

#6743 Center buttons on the form end screen
  collect_app/src/main/res/layout/form_entry_end.xml
Labels: behavior verified

#6736 Updated bikram-sambat jar
  collect_app/build.gradle
  collect_app/libs/bikram-sambat-1.1.0.jar
  collect_app/libs/bikram-sambat-1.8.0.jar
Labels: behavior verified
